from app.models import db, User, environment, SCHEMA
from sqlalchemy.sql import text


# Adds a demo user, you can add other users here if you want
def seed_users():
    users = [
        User(
            # id=1,
            first_name='Ellie',
            last_name='Bellie',
            city='San Francisco',
            state='CA',
            email='demo@aa.io',
            password='password'),
        User(
            # id=2,
            first_name='Marnie',
            last_name='Barnie',
            city='Pittsburgh',
            state='PA',
            email='marnie@aa.io',
            password='password'),
        User(
            # id=3,
            first_name='Bobbie',
            last_name='Robbie',
            city='New York',
            state='NY',
            email='bobbie@aa.io',
            password='password'), 
        User(
            # id=4,
            first_name='Misty',
            last_name='Waterflower',
            city='San Mateo',
            state='CA',
            email='misty@aa.io',
            password='password'),
        User(
            # id=5,
            first_name='Simon',
            last_name='Krawa',
            city='Uniontown',
            state='PA',
            email='bssammel@gmail.com',
            password='password'),
        User(
            # id=6,
            first_name='John',
            last_name='Doe',
            city='New York',
            state='NY',
            email='john.doe@example.com',
            password='password'),
        User(
            # id=7,
            first_name='Jane',
            last_name='Smith',
            city='Los Angeles',
            state='CA',
            email='jane.smith@example.com',
            password='password'),
        User(
            # id=8,
            first_name='Alice',
            last_name='Johnson',
            city='Chicago',
            state='IL',
            email='alice.johnson@example.com',
            password='password'),
        User(
            # id=9,
            first_name='Bob',
            last_name='Brown',
            city='Houston',
            state='TX',
            email='bob.brown@example.com',
            password='password'),
        User(
            # id=10,
            first_name='Charlie',
            last_name='Davis',
            city='Phoenix',
            state='AZ',
            email='charlie.davis@example.com',
            password='password'),
        User(
            # id=11,
            first_name='Dana',
            last_name='Miller',
            city='Philadelphia',
            state='PA',
            email='dana.miller@example.com',
            password='password'),
        User(
            # id=12,
            first_name='Evan',
            last_name='Wilson',
            city='San Antonio',
            state='TX',
            email='evan.wilson@example.com',
            password='password'),
        User(
            # id=13,
            first_name='Fiona',
            last_name='Moore',
            city='San Diego',
            state='CA',
            email='fiona.moore@example.com',
            password='password'),
        User(
            # id=14,
            first_name='George',
            last_name='Taylor',
            city='Dallas',
            state='TX',
            email='george.taylor@example.com',
            password='password'),
        User(
            # id=15,
            first_name='Hannah',
            last_name='Anderson',
            city='San Jose',
            state='CA',
            email='hannah.anderson@example.com',
            password='password'),
        User(
            # id=16,
            first_name='Ian',
            last_name='Thomas',
            city='Austin',
            state='TX',
            email='ian.thomas@example.com',
            password='password'),
        User(
            # id=17,
            first_name='Julia',
            last_name='Jackson',
            city='Jacksonville',
            state='FL',
            email='julia.jackson@example.com',
            password='password'),
        User(
            # id=18,
            first_name='Kevin',
            last_name='White',
            city='Fort Worth',
            state='TX',
            email='kevin.white@example.com',
            password='password'),
        User(
            # id=19,
            first_name='Laura',
            last_name='Harris',
            city='Columbus',
            state='OH',
            email='laura.harris@example.com',
            password='password'),
        User(
            # id=20,
            first_name='Mike',
            last_name='Martin',
            city='Charlotte',
            state='NC',
            email='mike.martin@example.com',
            password='password'),
        User(
            # id=21,
            first_name='Nina',
            last_name='Thompson',
            city='San Francisco',
            state='CA',
            email='nina.thompson@example.com',
            password='password'),
        User(
            # id=22,
            first_name='Oliver',
            last_name='Garcia',
            city='Indianapolis',
            state='IN',
            email='oliver.garcia@example.com',
            password='password'),
        User(
            # id=23,
            first_name='Paula',
            last_name='Martinez',
            city='Seattle',
            state='WA',
            email='paula.martinez@example.com',
            password='password'),
        User(
            # id=24,
            first_name='Quinn',
            last_name='Robinson',
            city='Denver',
            state='CO',
            email='quinn.robinson@example.com',
            password='password'),
        User(
            # id=25,
            first_name='Rachel',
            last_name='Clark',
            city='Washington',
            state='DC',
            email='rachel.clark@example.com',
            password='password'),
        User(
            # id=26,
            first_name='Sam',
            last_name='Rodriguez',
            city='Boston',
            state='MA',
            email='sam.rodriguez@example.com',
            password='password'),
        User(
            # id=27,
            first_name='Tina',
            last_name='Lewis',
            city='El Paso',
            state='TX',
            email='tina.lewis@example.com',
            password='password'),
        User(
            # id=28,
            first_name='Uma',
            last_name='Walker',
            city='Detroit',
            state='MI',
            email='uma.walker@example.com',
            password='password'),
        User(
            # id=29,
            first_name='Victor',
            last_name='Hall',
            city='Nashville',
            state='TN',
            email='victor.hall@example.com',
            password='password'),
        User(
            # id=30,
            first_name='Wendy',
            last_name='Allen',
            city='Memphis',
            state='TN',
            email='wendy.allen@example.com',
            password='password'),
                    User(
            # id=31,
            first_name='Xander',
            last_name='Young',
            city='Portland',
            state='OR',
            email='xander.young@example.com',
            password='password'),
        User(
            # id=32,
            first_name='Yara',
            last_name='Hernandez',
            city='Las Vegas',
            state='NV',
            email='yara.hernandez@example.com',
            password='password'),
        User(
            # id=33,
            first_name='Zane',
            last_name='King',
            city='Louisville',
            state='KY',
            email='zane.king@example.com',
            password='password'),
        User(
            # id=34,
            first_name='Ava',
            last_name='Wright',
            city='Baltimore',
            state='MD',
            email='ava.wright@example.com',
            password='password'),
        User(
            # id=35,
            first_name='Benjamin',
            last_name='Lopez',
            city='Milwaukee',
            state='WI',
            email='benjamin.lopez@example.com',
            password='password'),
        User(
            # id=36,
            first_name='Catherine',
            last_name='Hill',
            city='Albuquerque',
            state='NM',
            email='catherine.hill@example.com',
            password='password'),
        User(
            # id=37,
            first_name='Daniel',
            last_name='Scott',
            city='Tucson',
            state='AZ',
            email='daniel.scott@example.com',
            password='password'),
        User(
            # id=38,
            first_name='Eliza',
            last_name='Green',
            city='Fresno',
            state='CA',
            email='eliza.green@example.com',
            password='password'),
        User(
            # id=39,
            first_name='Finn',
            last_name='Adams',
            city='Sacramento',
            state='CA',
            email='finn.adams@example.com',
            password='password'),
        User(
            # id=40,
            first_name='Grace',
            last_name='Baker',
            city='Kansas City',
            state='MO',
            email='grace.baker@example.com',
            password='password'),
        User(
            # id=41,
            first_name='Henry',
            last_name='Gonzalez',
            city='Long Beach',
            state='CA',
            email='henry.gonzalez@example.com',
            password='password'),
        User(
            # id=42,
            first_name='Isla',
            last_name='Nelson',
            city='Mesa',
            state='AZ',
            email='isla.nelson@example.com',
            password='password'),
        User(
            # id=43,
            first_name='Jack',
            last_name='Carter',
            city='Atlanta',
            state='GA',
            email='jack.carter@example.com',
            password='password'),
        User(
            # id=44,
            first_name='Kara',
            last_name='Mitchell',
            city='Omaha',
            state='NE',
            email='kara.mitchell@example.com',
            password='password'),
        User(
            # id=45,
            first_name='Leo',
            last_name='Perez',
            city='Colorado Springs',
            state='CO',
            email='leo.perez@example.com',
            password='password'),
        User(
            # id=46,
            first_name='Mia',
            last_name='Roberts',
            city='Raleigh',
            state='NC',
            email='mia.roberts@example.com',
            password='password'),
        User(
            # id=47,
            first_name='Nathan',
            last_name='Turner',
            city='Miami',
            state='FL',
            email='nathan.turner@example.com',
            password='password'),
        User(
            # id=48,
            first_name='Olivia',
            last_name='Phillips',
            city='Virginia Beach',
            state='VA',
            email='olivia.phillips@example.com',
            password='password'),
        User(
            # id=49,
            first_name='Patrick',
            last_name='Campbell',
            city='Oakland',
            state='CA',
            email='patrick.campbell@example.com',
            password='password'),
        User(
            # id=50,
            first_name='Quincy',
            last_name='Parker',
            city='Minneapolis',
            state='MN',
            email='quincy.parker@example.com',
            password='password'),
        User(
            # id=51,
            first_name='Rebecca',
            last_name='Evans',
            city='Tulsa',
            state='OK',
            email='rebecca.evans@example.com',
            password='password'),
        User(
            # id=52,
            first_name='Simon',
            last_name='Edwards',
            city='Arlington',
            state='TX',
            email='simon.edwards@example.com',
            password='password'),
        User(
            # id=53,
            first_name='Tara',
            last_name='Collins',
            city='New Orleans',
            state='LA',
            email='tara.collins@example.com',
            password='password'),
        User(
            # id=54,
            first_name='Ulysses',
            last_name='Stewart',
            city='Wichita',
            state='KS',
            email='ulysses.stewart@example.com',
            password='password'),
        User(
            # id=55,
            first_name='Valerie',
            last_name='Morris',
            city='Cleveland',
            state='OH',
            email='valerie.morris@example.com',
            password='password'),
        User(
            # id=56,
            first_name='Walter',
            last_name='Rogers',
            city='Tampa',
            state='FL',
            email='walter.rogers@example.com',
            password='password'),
        User(
            # id=57,
            first_name='Xena',
            last_name='Reed',
            city='Bakersfield',
            state='CA',
            email='xena.reed@example.com',
            password='password'),
        User(
            # id=58,
            first_name='Yvonne',
            last_name='Cook',
            city='Aurora',
            state='CO',
            email='yvonne.cook@example.com',
            password='password'),
        User(
            # id=59,
            first_name='Zachary',
            last_name='Morgan',
            city='Anaheim',
            state='CA',
            email='zachary.morgan@example.com',
            password='password'),
        User(
            # id=60,
            first_name='Aaron',
            last_name='Murphy',
            city='Honolulu',
            state='HI',
            email='aaron.murphy@example.com',
            password='password'),
        User(
            # id=61,
            first_name='Bella',
            last_name='Price',
            city='Santa Ana',
            state='CA',
            email='bella.price@example.com',
            password='password'),
        User(
            # id=62,
            first_name='Caleb',
            last_name='Nguyen',
            city='Riverside',
            state='CA',
            email='caleb.nguyen@example.com',
            password='password'),
        User(
            # id=63,
            first_name='Diana',
            last_name='Sanders',
            city='Corpus Christi',
            state='TX',
            email='diana.sanders@example.com',
            password='password'),
        User(
            # id=64,
            first_name='Edward',
            last_name='Perez',
            city='Lexington',
            state='KY',
            email='edward.perez@example.com',
            password='password'),
        User(
            # id=65,
            first_name='Felicity',
            last_name='Bailey',
            city='Stockton',
            state='CA',
            email='felicity.bailey@example.com',
            password='password'),
        User(
            # id=66,
            first_name='Gavin',
            last_name='Reyes',
            city='St. Louis',
            state='MO',
            email='gavin.reyes@example.com',
            password='password'),
        User(
            # id=67,
            first_name='Holly',
            last_name='Richardson',
            city='Saint Paul',
            state='MN',
            email='holly.richardson@example.com',
            password='password'),
        User(
            # id=68,
            first_name='Isaac',
            last_name='Ramirez',
            city='Cincinnati',
            state='OH',
            email='isaac.ramirez@example.com',
            password='password'),
        User(
            # id=69,
            first_name='Jenna',
            last_name='James',
            city='Greensboro',
            state='NC',
            email='jenna.james@example.com',
            password='password'),
        User(
            # id=70,
            first_name='Kyle',
            last_name='Watson',
            city='Henderson',
            state='NV',
            email='kyle.watson@example.com',
            password='password'),
        User(
            # id=71,
            first_name='Lily',
            last_name='Brooks',
            city='Plano',
            state='TX',
            email='lily.brooks@example.com',
            password='password'),
        User(
            # id=72,
            first_name='Mason',
            last_name='Kelly',
            city='Lincoln',
            state='NE',
            email='mason.kelly@example.com',
            password='password'),
        User(
            # id=73,
            first_name='Nora',
            last_name='Ward',
            city='Buffalo',
            state='NY',
            email='nora.ward@example.com',
            password='password'),
        User(
            # id=74,
            first_name='Owen',
            last_name='Torres',
            city='Fort Wayne',
            state='IN',
            email='owen.torres@example.com',
            password='password'),
        User(
            # id=75,
            first_name='Paige',
            last_name='Peterson',
            city='Chandler',
            state='AZ',
            email='paige.peterson@example.com',
            password='password'),
        User(
            # id=76,
            first_name='Ryan',
            last_name='Gray',
            city='Chula Vista',
            state='CA',
            email='ryan.gray@example.com',
            password='password'),
        User(
            # id=77,
            first_name='Sara',
            last_name='Ramirez',
            city='Madison',
            state='WI',
            email='sara.ramirez@example.com',
            password='password'),
        User(
            # id=78,
            first_name='Thomas',
            last_name='Foster',
            city='Reno',
            state='NV',
            email='thomas.foster@example.com',
            password='password'),
        User(
            # id=79,
            first_name='Uma',
            last_name='Henderson',
            city='Garland',
            state='TX',
            email='uma.henderson@example.com',
            password='password'),
        User(
            # id=80,
            first_name='Victor',
            last_name='Barnes',
            city='Glendale',
            state='AZ',
            email='victor.barnes@example.com',
            password='password'),
        User(
            # id=81,
            first_name='Wendy',
            last_name='Coleman',
            city='Lubbock',
            state='TX',
            email='wendy.coleman@example.com',
            password='password'),
        User(
            # id=82,
            first_name='Xavier',
            last_name='Jenkins',
            city='Hialeah',
            state='FL',
            email='xavier.jenkins@example.com',
            password='password'),
        User(
            # id=83,
            first_name='Yasmine',
            last_name='Perry',
            city='Richmond',
            state='VA',
            email='yasmine.perry@example.com',
            password='password'),
        User(
            # id=84,
            first_name='Zara',
            last_name='Powell',
            city='Boise',
            state='ID',
            email='zara.powell@example.com',
            password='password'),
        User(
            # id=85,
            first_name='Aiden',
            last_name='Long',
            city='Baton Rouge',
            state='LA',
            email='aiden.long@example.com',
            password='password'),
        User(
            # id=86,
            first_name='Brooke',
            last_name='Patterson',
            city='Des Moines',
            state='IA',
            email='brooke.patterson@example.com',
            password='password'),
        User(
            # id=87,
            first_name='Carter',
            last_name='Hughes',
            city='Spokane',
            state='WA',
            email='carter.hughes@example.com',
            password='password'),
        User(
            # id=88,
            first_name='Daisy',
            last_name='Flores',
            city='San Bernardino',
            state='CA',
            email='daisy.flores@example.com',
            password='password'),
        User(
            # id=89,
            first_name='Eli',
            last_name='Washington',
            city='Modesto',
            state='CA',
            email='eli.washington@example.com',
            password='password'),
        User(
            # id=90,
            first_name='Fiona',
            last_name='Murphy',
            city='Huntsville',
            state='AL',
            email='fiona.murphy@example.com',
            password='password'),
        User(
            # id=91,
            first_name='Graham',
            last_name='Price',
            city='Little Rock',
            state='AR',
            email='graham.price@example.com',
            password='password'),
        User(
            # id=92,
            first_name='Hannah',
            last_name='Nguyen',
            city='Mobile',
            state='AL',
            email='hannah.nguyen@example.com',
            password='password'),
        User(
            # id=93,
            first_name='Ian',
            last_name='Sanders',
            city='Knoxville',
            state='TN',
            email='ian.sanders@example.com',
            password='password'),
        User(
            # id=94,
            first_name='Jack',
            last_name='Perez',
            city='Grand Rapids',
            state='MI',
            email='jack.perez@example.com',
            password='password'),
        User(
            # id=95,
            first_name='Kara',
            last_name='Bailey',
            city='Shreveport',
            state='LA',
            email='kara.bailey@example.com',
            password='password'),
        User(
            # id=96,
            first_name='Liam',
            last_name='Reyes',
            city='Augusta',
            state='GA',
            email='liam.reyes@example.com',
            password='password'),
        User(
            # id=97,
            first_name='Mila',
            last_name='Richardson',
            city='Akron',
            state='OH',
            email='mila.richardson@example.com',
            password='password'),
        User(
            # id=98,
            first_name='Noah',
            last_name='Ramirez',
            city='Tallahassee',
            state='FL',
            email='noah.ramirez@example.com',
            password='password'),
        User(
            # id=99,
            first_name='Olivia',
            last_name='James',
            city='Sioux Falls',
            state='SD',
            email='olivia.james@example.com',
            password='password'),
        User(
            # id=100,
            first_name='Paul',
            last_name='Watson',
            city='Peoria',
            state='IL',
            email='paul.watson@example.com',
            password='password'),
        User(
            # id=101,
            first_name='Quinn',
            last_name='Brooks',
            city='Frisco',
            state='TX',
            email='quinn.brooks@example.com',
            password='password'),
        User(
            # id=102,
            first_name='Riley',
            last_name='Kelly',
            city='Yonkers',
            state='NY',
            email='riley.kelly@example.com',
            password='password'),
        User(
            # id=103,
            first_name='Sophia',
            last_name='Ward',
            city='Amarillo',
            state='TX',
            email='sophia.ward@example.com',
            password='password'),
        User(
            # id=104,
            first_name='Tyler',
            last_name='Torres',
            city='Glendale',
            state='AZ',
            email='tyler.torres@example.com',
            password='password'),
        User(
            # id=105,
            first_name='Uma',
            last_name='Peterson',
            city='Huntington Beach',
            state='CA',
            email='uma.peterson@example.com',
            password='password'),
        User(
            # id=106,
            first_name='Victoria',
            last_name='Gray',
            city='Salt Lake City',
            state='UT',
            email='victoria.gray@example.com',
            password='password'),
        User(
            # id=107,
            first_name='William',
            last_name='Ramirez',
            city='Grand Prairie',
            state='TX',
            email='william.ramirez@example.com',
            password='password'),
        User(
            # id=108,
            first_name='Xena',
            last_name='Foster',
            city='Overland Park',
            state='KS',
            email='xena.foster@example.com',
            password='password'),
        User(
            # id=109,
            first_name='Yvonne',
            last_name='Henderson',
            city='Cape Coral',
            state='FL',
            email='yvonne.henderson@example.com',
            password='password'),
        User(
            # id=110,
            first_name='Zachary',
            last_name='Barnes',
            city='Providence',
            state='RI',
            email='zachary.barnes@example.com',
            password='password'),
        User(
            # id=111,
            first_name='Aiden',
            last_name='Coleman',
            city='Vancouver',
            state='WA',
            email='aiden.coleman@example.com',
            password='password'),
        User(
            # id=112,
            first_name='Brooke',
            last_name='Jenkins',
            city='Tempe',
            state='AZ',
            email='brooke.jenkins@example.com',
            password='password'),
        User(
            # id=113,
            first_name='Carter',
            last_name='Perry',
            city='Springfield',
            state='MO',
            email='carter.perry@example.com',
            password='password'),
        User(
            # id=114,
            first_name='Daisy',
            last_name='Powell',
            city='Lancaster',
            state='CA',
            email='daisy.powell@example.com',
            password='password'),
        User(
            # id=115,
            first_name='Eli',
            last_name='Long',
            city='Eugene',
            state='OR',
            email='eli.long@example.com',
            password='password'),
        User(
            # id=116,
            first_name='Fiona',
            last_name='Patterson',
            city='Pembroke Pines',
            state='FL',
            email='fiona.patterson@example.com',
            password='password'),
        User(
            # id=117,
            first_name='Gavin',
            last_name='Hughes',
            city='Salem',
            state='OR',
            email='gavin.hughes@example.com',
            password='password'),
        User(
            # id=118,
            first_name='Holly',
            last_name='Flores',
            city='Palmdale',
            state='CA',
            email='holly.flores@example.com',
            password='password'),
        User(
            # id=119,
            first_name='Isaac',
            last_name='Washington',
            city='Corona',
            state='CA',
            email='isaac.washington@example.com',
            password='password'),
        User(
            # id=120,
            first_name='Jenna',
            last_name='Murphy',
            city='Salinas',
            state='CA',
            email='jenna.murphy@example.com',
            password='password'),
        User(
            # id=121,
            first_name='Kyle',
            last_name='Price',
            city='Springfield',
            state='MA',
            email='kyle.price@example.com',
            password='password'),
        User(
            # id=122,
            first_name='Lily',
            last_name='Nguyen',
            city='Pasadena',
            state='TX',
            email='lily.nguyen@example.com',
            password='password'),
        User(
            # id=123,
            first_name='Mason',
            last_name='Sanders',
            city='Hayward',
            state='CA',
            email='mason.sanders@example.com',
            password='password'),
        User(
            # id=124,
            first_name='Nora',
            last_name='Perez',
            city='Fort Collins',
            state='CO',
            email='nora.perez@example.com',
            password='password'),
        User(
            # id=125,
            first_name='Owen',
            last_name='Bailey',
            city='Macon',
            state='GA',
            email='owen.bailey@example.com',
            password='password'),
        User(
            # id=126,
            first_name='Paige',
            last_name='Reyes',
            city='Pomona',
            state='CA',
            email='paige.reyes@example.com',
            password='password'),
        User(
            # id=127,
            first_name='Ryan',
            last_name='Richardson',
            city='Cary',
            state='NC',
            email='ryan.richardson@example.com',
            password='password'),
        User(
            # id=128,
            first_name='Sarah',
            last_name='Ramirez',
            city='Rockford',
            state='IL',
            email='sarah.ramirez@example.com',
            password='password'),
        User(
            # id=129,
            first_name='Thomas',
            last_name='James',
            city='Alexandria',
            state='VA',
            email='thomas.james@example.com',
            password='password'),
        User(
            # id=130,
            first_name='Uma',
            last_name='Watson',
            city='Escondido',
            state='CA',
            email='uma.watson@example.com',
            password='password'),
        User(
            # id=131,
            first_name='Victor',
            last_name='Brooks',
            city='McKinney',
            state='TX',
            email='victor.brooks@example.com',
            password='password'),
        User(
            # id=132,
            first_name='Wendy',
            last_name='Kelly',
            city='Kansas City',
            state='KS',
            email='wendy.kelly@example.com',
            password='password'),
        User(
            # id=133,
            first_name='Xander',
            last_name='Ward',
            city='Joliet',
            state='IL',
            email='xander.ward@example.com',
            password='password'),
        User(
            # id=134,
            first_name='Yara',
            last_name='Torres',
            city='Sunnyvale',
            state='CA',
            email='yara.torres@example.com',
            password='password'),
        User(
            # id=135,
            first_name='Zane',
            last_name='Peterson',
            city='Hollywood',
            state='FL',
            email='zane.peterson@example.com',
            password='password'),
        User(
            # id=136,
            first_name='Ava',
            last_name='Gray',
            city='Surprise',
            state='AZ',
            email='ava.gray@example.com',
            password='password'),
        User(
            # id=137,
            first_name='Benjamin',
            last_name='Ramirez',
            city='Clarksville',
            state='TN',
            email='benjamin.ramirez@example.com',
            password='password'),
        User(
            # id=138,
            first_name='Catherine',
            last_name='Foster',
            city='Paterson',
            state='NJ',
            email='catherine.foster@example.com',
            password='password'),
        User(
            # id=139,
            first_name='Daniel',
            last_name='Henderson',
            city='Naperville',
            state='IL',
            email='daniel.henderson@example.com',
            password='password'),
        User(
            # id=140,
            first_name='Eliza',
            last_name='Barnes',
            city='Bridgeport',
            state='CT',
            email='eliza.barnes@example.com',
            password='password'),
        User(
            # id=141,
            first_name='Finn',
            last_name='Coleman',
            city='Mesquite',
            state='TX',
            email='finn.coleman@example.com',
            password='password'),
        User(
            # id=142,
            first_name='Grace',
            last_name='Jenkins',
            city='Killeen',
            state='TX',
            email='grace.jenkins@example.com',
            password='password'),
        User(
            # id=143,
            first_name='Henry',
            last_name='Perry',
            city='Savannah',
            state='GA',
            email='henry.perry@example.com',
            password='password'),
        User(
            # id=144,
            first_name='Isla',
            last_name='Powell',
            city='Bellevue',
            state='WA',
            email='isla.powell@example.com',
            password='password'),
        User(
            # id=145,
            first_name='Jack',
            last_name='Long',
            city='Hampton',
            state='VA',
            email='jack.long@example.com',
            password='password'),
        User(
            # id=146,
            first_name='Kara',
            last_name='Patterson',
            city='Pasadena',
            state='CA',
            email='kara.patterson@example.com',
            password='password'),
        User(
            # id=147,
            first_name='Leo',
            last_name='Hughes',
            city='Orange',
            state='CA',
            email='leo.hughes@example.com',
            password='password'),
        User(
            # id=148,
            first_name='Mia',
            last_name='Flores',
            city='Fullerton',
            state='CA',
            email='mia.flores@example.com',
            password='password'),
        User(
            # id=149,
            first_name='Nathan',
            last_name='Washington',
            city='Dayton',
            state='OH',
            email='nathan.washington@example.com',
            password='password'),
        User(
            # id=150,
            first_name='Olivia',
            last_name='Murphy',
            city='McAllen',
            state='TX',
            email='olivia.murphy@example.com',
            password='password'),
    ]

    db.session.add_all(users)
    db.session.commit()


# Uses a raw SQL query to TRUNCATE or DELETE the users table. SQLAlchemy doesn't
# have a built in function to do this. With postgres in production TRUNCATE
# removes all the data from the table, and RESET IDENTITY resets the auto
# incrementing primary key, CASCADE deletes any dependent entities.  With
# sqlite3 in development you need to instead use DELETE to remove all data and
# it will reset the primary keys for you as well.
def undo_users():
    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.users RESTART IDENTITY CASCADE;")
    else:
        db.session.execute(text("DELETE FROM users"))

    db.session.commit()
