from app.models import db, Business, environment, SCHEMA
from sqlalchemy.sql import text

def seed_businesses():
    businesses_3 = [
        Business(
            owner_id=10,
            category_id=1,
            address='1678 3rd Ave',
            city='New York',
            state='NY',
            zip_code='10128',
            name='The Barking Dog',
            description='The Barking Dog is a pet-friendly restaurant offering a variety of American dishes and outdoor seating for you and your pet.',
            website='http://www.barkingdognyc.com/',
            phone='2128311800',
            price='$$',
            set_hours="yes",
            mon_open='0700',
            mon_close='2300',
            tue_open='0700',
            tue_close='2300',
            wed_open='0700',
            wed_close='2300',
            thu_open='0700',
            thu_close='2300',
            fri_open='0700',
            fri_close='2300',
            sat_open='0800',
            sat_close='2300',
            sun_open='0800',
            sun_close='2300',
        ),  
        Business(
            owner_id=23,
            category_id=2,
            address='295 W 112th St',
            city='New York',
            state='NY',
            zip_code='10026',
            name='Uptown Veterinary Associates',
            description='Uptown Veterinary Associates provides comprehensive veterinary care services for your pets.',
            website='https://www.banfield.com/locations/veterinarians/ny/new-york/acn',
            phone='2122221221',
            set_hours="yes",
            mon_open='0800',
            mon_close='1800',
            tue_open='0800',
            tue_close='1800',
            wed_open='0800',
            wed_close='1800',
            thu_open='0800',
            thu_close='1800',
            fri_open='0800',
            fri_close='1800',
            sat_open='0800',
            sat_close='1800',
        ),   
        Business(
            owner_id=34,
            category_id=3,
            address='235 W 76th St',
            city='New York',
            state='NY',
            zip_code='10023',
            name='NYC Pooch',
            description='NYC POOCH - is NYC\'s loved and trusted dog walking and dog running company. They find the best people for the job and train them to be even better. ',
            website='https://nycpooch.com/',
            phone='2128746335',
            price='$$',
            set_hours="yes",
            mon_open='0730',
            mon_close='1800',
            tue_open='0730',
            tue_close='1800',
            wed_open='0730',
            wed_close='1800',
            thu_open='0730',
            thu_close='1800',
            fri_open='0730',
            fri_close='1800',
        ),
        Business(
            owner_id=45,
            category_id=4,
            address='235 E 9th St',
            city='New York',
            state='NY',
            zip_code='10003',
            name='Whiskers Holistic Petcare',
            description='Whiskers Holistic Petcare offers a range of natural and holistic pet foods and supplies.',
            website='https://www.1800whiskers.com/',
            phone='2129792532',
            price='$$',
            set_hours="yes",
            mon_open='1100',
            mon_close='1900',
            tue_open='1100',
            tue_close='1900',
            wed_open='1100',
            wed_close='1900',
            thu_open='1100',
            thu_close='1900',
            fri_open='1100',
            fri_close='1900',
            sat_open='1100',
            sat_close='1900',
            sun_open='1200',
            sun_close='1800',
        ),  
        Business(
            owner_id=12,
            category_id=5,
            address='851 6th Ave',
            city='New York',
            state='NY',
            zip_code='10001',
            name='Kimpton Hotel Eventi',
            description='Kimpton Hotel Eventi is a pet-friendly hotel in New York City offering luxurious accommodations and pet amenities.',
            website='https://www.hoteleventi.com/',
            phone='2125644567',
            price='$$$',
            set_hours="no",
        ),
        Business(
            owner_id=5,
            category_id=6,
            address='Central Park',
            city='New York',
            state='NY',
            zip_code='10024',
            name='Central Park',
            description='Central Park offers a large area for pet-friendly activities, including designated off-leash areas for dogs.',
            website='https://www.centralparknyc.org/',
            set_hours="no",
        ),
        Business(
            owner_id=29,
            category_id=7,
            address='326 E 110th St',
            city='New York',
            state='NY',
            zip_code='10029',
            name='Animal Care Centers of NYC',
            description='Animal Care Centers of NYC is dedicated to finding loving homes for dogs, cats, and other pets.',
            website='http://www.nycacc.org/',
            phone='2127884000',
            set_hours="yes",
            mon_open='1200',
            mon_close='1800',
            tue_open='1200',
            tue_close='1800',
            wed_open='1200',
            wed_close='1800',
            thu_open='1200',
            thu_close='1800',
            fri_open='1200',
            fri_close='1800',
            sat_open='1100',
            sat_close='1700',
            sun_open='1100',
            sun_close='1700',
        ),
        Business(
            owner_id=37,
            category_id=8,
            address='60 W 45th St',
            city='New York',
            state='NY',
            zip_code='10036',
            name='Midtown Manhattan Psychic',
            description='If you’re looking for Pet Psychic Readings near everything in NYC, you can’t beat our service!  If you’ve been thinking about having a pet psychic reading, you should know that there are many different options that can be catered to you and your beloved furry friend.',
            website='https://midtownmanhattanpsychic.com/pet-psychic-nyc/',
            phone='6468230833',
            price='$$',
            set_hours="no",
        )
    ]
    
    db.session.add_all(businesses_3)
    db.session.commit()



# Uses a raw SQL query to TRUNCATE or DELETE the users table. SQLAlchemy doesn't
# have a built in function to do this. With postgres in production TRUNCATE
# removes all the data from the table, and RESET IDENTITY resets the auto
# incrementing primary key, CASCADE deletes any dependent entities.  With
# sqlite3 in development you need to instead use DELETE to remove all data and
# it will reset the primary keys for you as well.
def undo_businesses():
    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.businesses RESTART IDENTITY CASCADE;")
    else:
        db.session.execute(text("DELETE FROM businesses"))

    db.session.commit()
