from app.models import db, Business, environment, SCHEMA
from sqlalchemy.sql import text

def seed_businesses():
    petagogy = Business(
        # id 1
        owner_id=1,
        category_id=4,
        address='5880 Ellsworth Ave',
        city='Pittsburgh',
        state='PA',
        zip_code='15232',
        name='Petagogy',
        description='Offering a great selection of premium and natural pet foods and supplies in the Pittsburgh area, Fido is welcome to come and sniff out deals on offer here. As well as food, Fido will also find collars, leashes, toys and more.',
        website='https://www.petagogy.com/',
        email='info@petagogy.com',
        phone='4123627387',
        price='$$$',
        set_hours="yes",
        mon_open='1000',
        mon_close='2000',
        tue_open='1000',
        tue_close='2000',
        wed_open='1000',
        wed_close='2000',
        thu_open='1000',
        thu_close='2000',
        fri_open='1000',
        fri_close='2000',
        sat_open='1000',
        sat_close='2000',
        sun_open='1100',
        sun_close='1600',
    )

    mishka = Business(
        # id 2
        owner_id=2,
        category_id=4,
        address='2124 Union St Ste A',
        city='San Francisco',
        state='CA',
        zip_code='94123',
        name='Mishka Dog Boutique',
        description='Mishka dog cakes made with no artificial colors, no preservatives! You can also find our full line of hand crafted, luxury dog clothing and accessories.',
        website='https://mishkacakes.com/',
        phone='6289000923',
        price='$$$$',
        set_hours="yes",
        mon_open='1100',
        mon_close='1700',
        tue_open='1100',
        tue_close='1800',
        wed_open='1100',
        wed_close='1800',
        thu_open='1100',
        thu_close='1800',
        fri_open='1100',
        fri_close='1800',
        sat_open='1000',
        sat_close='1800',
        sun_open='1000',
        sun_close='1800',
    )

    leo_j_ryan = Business(
        # id 3
        owner_id=3,
        category_id=6,
        address='650 Shell Blvd',
        city='Foster City',
        state='CA',
        zip_code='94404',
        name='Leo J Ryan Memorial Park',
        description='Leo J. Ryan Memorial Park is a dog-friendly park that offers 20 acres of lawn areas, lagoon access, a gazebo on the lagoon, and restroom facilities.',
        website='https://www.fostercity.org/parksrec/page/leo-j-ryan-park',
        phone='6502863380',
        set_hours="no"
    )

    dumpling_home = Business(
        # id 4
        owner_id=3,
        category_id=1,
        address='298 Gough St',
        city='San Francisco',
        state='CA',
        zip_code='94102',
        name='Dumpling Home',
        description='Casual, colorful eatery dishing up fried, steamed, or boiled dumplings, plus noodles and small plates, with a dog-friendly patio!',
        website='https://www.dumplinghome.com/',
        phone='4155031666',
	    price='$$',
        set_hours="yes",
        mon_open='1130',
        mon_close='2015',
        tue_open='1130',
        tue_close='2015',
        wed_open='1130',
        wed_close='2015',
        thu_open='1130',
        thu_close='2015',
        fri_open='1130',
        fri_close='2015',
        sat_open='1130',
        sat_close='2015'
    )

    bakery = Business(
        # id 5
        owner_id=1,
        category_id=4,
        address= "2402 Rice Blvd",
        city= "Houston",
        state= "TX",
        zip_code= "77005",
        name= "Three Dog Bakery Houston",
        description= "Three Dog Bakery is an unforgettable experience for dogs (and their two-legged parents). You will find a selection of treats that can only be found at Three Dog bakeries.",
        website= "https://www.threedogbakeryhtx.com/",
        email= "baker@threedogbakeryhtx.com",
        phone= "7135339933",
        price= "$$",
        set_hours="yes",
        wed_open='1000',
        wed_close='2000',
        thu_open='1000',
        thu_close='2000',
        fri_open='0900',
        fri_close='2000',
        sat_open='0900',
        sat_close='2000',
        sun_open='1000',
        sun_close='1900',
    )

    caroline = Business(
    # id 6
        owner_id= 4,
        category_id=8,
        address='3301 NE 1st Ave',
        city='Miami',
        state='FL',
        zip_code='33137',
        name='Caroline Twohill Photography',
        description='Caroline longs and strides to discovering and telling your dog’s unique story with beautiful, natural fine art images just begging to be displayed in your home and shared with family, friends and loved ones.',
        website='https://www.carolinetwohillphotography.com/',
        phone='6094252118',
        price='$$',
        set_hours="no"
    )

    exotic_vet = Business(
    # id 7
        owner_id= 5,
        category_id=2,
        address='10501 Aurora Ave North',
        city='Seattle',
        state='WA',
        zip_code='98133',
        name='Bird and Exotic Clinic of Seattle',
        description='Established in 1997 Bird & Exotic Clinic of Seattle is a full-service specialty exotic animal hospital and welcomes patients in need of routine and advanced medical, surgical, and dental care.',
        website='https://www.birdandexotic.com/',
        email= "birdandexoticclinicofseattle@gmail.com",
        phone='2067834538',
        price='$$',
        set_hours="yes",
        mon_open='0900',
        mon_close='1700',
        tue_open='0800',
        tue_close='2015',
        wed_open='1800',
        wed_close='2015',
        thu_open='1800',
        thu_close='2015',
        fri_open='1800',
        fri_close='2015',
        sat_open='0900',
        sat_close='1600'
    )

    perch= Business(
    # id 8
        owner_id=1,
        category_id=1,
        address='1932 W Division',
        city='Chicago',
        state='IL',
        zip_code='60622',
        name='The Perch',
        description='The Perch Kitchen and Tap is a partnership between 4 STAR Restaurant Group and Finch Beer Co. - Wicker Park\'s newest full service restaurant + bar with an onsite brewery.',
        website='https://theperchchicago.com',
        price='$$$',
        set_hours="yes",
        mon_open='1100',
        mon_close='2100',
        tue_open='0100',
        tue_close='2100',
        wed_open='1100',
        wed_close='2100',
        thu_open='1100',
        thu_close='2100',
        fri_open='1100',
        fri_close='2200',
        sat_open='0900',
        sat_close='2100',
        sun_open='0900',
        sun_close='2100'
    )

    salondog= Business(
    # id 9
        owner_id=3,
        category_id=3,
        address='2542 W Fullerton Ave',
        city='Chicago',
        state='IL',
        zip_code='60647',
        name='Salon Dog',
        description='Salon Dog is a team of experienced and caring pet groomers dedicated to providing top-quality grooming services for your beloved pets.',
        website='https://salondog.net/',
        set_hours="yes",
        mon_open='0900',
        mon_close='1800',
        wed_open='0900',
        wed_close='1800',
        thu_open='0900',
        thu_close='1800',
        fri_open='0900',
        fri_close='1800',
        sat_open='1000',
        sat_close='1800',
        sun_open='1000',
        sun_close='1800'
    )

    businesses_2 = [
        Business(
            # id 1
            owner_id=15,
            category_id=1,
            address='1 W Portal Ave',
            city='San Francisco',
            state='CA',
            zip_code='94127',
            name='Squat & Gobble',
            description='Squat & Gobble offers a heated, dog-friendly garden patio in addition to sidewalk seating. The menu includes a variety of breakfast, brunch, lunch, and dinner options, making it a great spot for you and your dog any time of day.',
            website='https://www.squatandgobble.com/',
            email='info@squatandgobble.com',
            phone='4156659900',
            price='$$',
            set_hours="yes",
            mon_open='0800',
            mon_close='2100',
            tue_open='0800',
            tue_close='2100',
            wed_open='0800',
            wed_close='2100',
            thu_open='0800',
            thu_close='2100',
            fri_open='0800',
            fri_close='2100',
            sat_open='0800',
            sat_close='2100',
            sun_open='0800',
            sun_close='2100',
        ),
        Business(
            # id 2
            owner_id=23,
            category_id=2,
            address='4382 Piedmont Ave',
            city='Oakland',
            state='CA',
            zip_code='94611',
            name='Holistic Veterinary Care',
            description='Holistic Veterinary Care offers integrative pet care with services like acupuncture, chiropractic care, and physical rehabilitation. They provide a welcoming environment for pets and their owners.',
            website='https://www.holisticvetcare.com/',
            email='info@holisticvetcare.com',
            phone='5103392600',
            price='$$$',
            set_hours="yes",
            mon_open='0900',
            mon_close='1800',
            tue_open='0900',
            tue_close='1800',
            wed_open='0900',
            wed_close='1800',
            thu_open='0900',
            thu_close='1800',
            fri_open='0900',
            fri_close='1800',
            sat_open='1000',
            sat_close='1600',
        ),
        Business(
            # id 3
            owner_id=7,
            category_id=3,
            address='1630 Curtis St Berkeley',
            city='Berkeley',
            state='CA',
            zip_code='94702',
            name='Well Loved Dogs',
            description='Well Loved Dogs offers quality doggie daycare and dog boarding in Berkeley, CA',
            website='https://www.wellloveddogs.com/',
            email='info@dogtalesdaycare.com',
            phone='5105018155',
            price='$$',
            set_hours="yes",
            mon_open='0700',
            mon_close='1900',
            tue_open='0700',
            tue_close='1900',
            wed_open='0700',
            wed_close='1900',
            thu_open='0700',
            thu_close='1900',
            fri_open='0700',
            fri_close='1900',
            sat_open='0900',
            sat_close='1700',
            ),
        Business(
            # id 4
            owner_id=10,
            category_id=4,
            address='1510 Walnut St',
            city='Berkeley',
            state='CA',
            zip_code='94709',
            name='Holistic Hound',
            description='Holistic Hound offers a wide range of natural and holistic pet products, including supplements, treats, and CBD products. Pets are welcome to join their owners while shopping.',
            website='https://www.holistichound.com/',
            email='info@holistichound.com',
            phone='5108432133',
            price='$$',
            set_hours="yes",
            mon_open='1000',
            mon_close='1800',
            tue_open='1000',
            tue_close='1800',
            wed_open='1000',
            wed_close='1800',
            thu_open='1000',
            thu_close='1800',
            fri_open='1000',
            fri_close='1800',
            sat_open='1000',
            sat_close='1800',
            sun_open='1200',
            sun_close='1700',
        ),
        Business(
            owner_id=22,
            category_id=4,
            address='1201 N Wells St',
            city='Chicago',
            state='IL',
            zip_code='60610',
            name='Bentley\'s Pet Stuff',
            description='Bentley\'s Pet Stuff is an all-natural pet food store committed to providing high-quality, nutritious pet food free from by-products, corn, soy, and wheat. They also offer a wide selection of pet toys, treats, and other supplies.',
            website='https://www.petstuff.com',
            phone='3122551955',
            price='$$',
            set_hours="yes",
            mon_open='1000',
            mon_close='1900',
            tue_open='1000',
            tue_close='1900',
            wed_open='1000',
            wed_close='1900',
            thu_open='1000',
            thu_close='1900',
            fri_open='1000',
            fri_close='1900',
            sat_open='1000',
            sat_close='1800',
            sun_open='1000',
            sun_close='1800',
            email='info@petstuff.com',
        ),
        Business(
            owner_id=17,
            category_id=4,
            address='3311 N Halsted St',
            city='Chicago',
            state='IL',
            zip_code='60657',
            name='Out of the Closet Thrift Store',
            description='Out of the Closet is the nation\'s largest not-for-profit retail fundraiser for HIV/AIDS medical care. 96¢ of every dollar directly funds AIDS Healthcare Foundation\'s HIV/AIDS programs and services in the U.S. and abroad.',
            website='https://www.outofthecloset.org/',
            phone='7734359584',
            set_hours="yes",
            mon_open='1000',
            mon_close='1900',
            tue_open='1000',
            tue_close='1900',
            wed_open='1000',
            wed_close='1900',
            thu_open='1000',
            thu_close='1900',
            fri_open='1000',
            fri_close='1900',
            sat_open='1000',
            sat_close='1900',
            sun_open='1000',
            sun_close='1900'
        ),
        Business(
            owner_id=42,
            category_id=5,
            address='1 Bennett St',
            city='Cambridge',
            state='MA',
            zip_code='02138',
            name='The Charles Hotel',
            description='A pet-friendly hotel located in the heart of Cambridge, The Charles Hotel welcomes pets and offers special pet packages, including pet beds and bowls.',
            website='https://www.charleshotel.com/',
            email='info@charleshotel.com',
            phone='6178641200',
            price='$$$$',
            set_hours="yes",
            mon_open='0000',
            mon_close='2359',
            tue_open='0000',
            tue_close='2359',
            wed_open='0000',
            wed_close='2359',
            thu_open='0000',
            thu_close='2359',
            fri_open='0000',
            fri_close='2359',
            sat_open='0000',
            sat_close='2359',
            sun_open='0000',
            sun_close='2359',
        ),
        Business(
            owner_id=45,
            category_id=2,
            address='1724 Massachusetts Ave',
            city='Cambridge',
            state='MA',
            zip_code='02138',
            name='Cambridge Veterinary Care',
            description='Full-service veterinary clinic offering comprehensive medical, surgical, and dental care for pets, with a dedicated team of professionals.',
            website='https://www.cambridgevetcare.com/',
            email='info@cambridgevetcare.com',
            phone='6176616255',
            price='$$$',
            set_hours="yes",
            mon_open='0800',
            mon_close='1800',
            tue_open='0800',
            tue_close='1800',
            wed_open='0800',
            wed_close='1800',
            thu_open='0800',
            thu_close='1800',
            fri_open='0800',
            fri_close='1800',
            sat_open='0900',
            sat_close='1300',
        ),
        Business(
            owner_id=38,
            category_id=3,
            address='1066 Washington St',
            city='Dorchester Center',
            state='MA',
            zip_code='02124',
            name='Argos Dog Training',
            description='Argos Dog Training provides online, in-person, and group training sessions in Boston, MA.',
            website='https://argostraining.com/',
            phone='7608467091',
            set_hours="yes",
            mon_open='0800',
            mon_close='2000',
            tue_open='0800',
            tue_close='2000',
            wed_open='0800',
            wed_close='2000',
            thu_open='0800',
            thu_close='2000',
            fri_open='0800',
            fri_close='2000',
            sat_open='0900',
            sat_close='1600',
            sun_open='0900',
            sun_close='1600',
        ),
        Business(
            owner_id=31,
            category_id=4,
            address='256 Shawmut Avenue',
            city='Boston',
            state='MA',
            zip_code='02118',
            name='Polka Dog Bakery',
            description='A specialty pet store offering gourmet dog treats and pet supplies, known for its unique and high-quality products.',
            website='https://www.polkadog.com/',
            email='info@polkadog.com',
            phone='6173385155',
            price='$$$',
            set_hours="yes",
            mon_open='1000',
            mon_close='2000',
            tue_open='1000',
            tue_close='2000',
            wed_open='1000',
            wed_close='2000',
            thu_open='1000',
            thu_close='2000',
            fri_open='1000',
            fri_close='2000',
            sat_open='1000',
            sat_close='2000',
            sun_open='1100',
            sun_close='1800',
        ),
        Business(
            owner_id=45,
            category_id=5,
            address='99 Erdman Way',
            city='Leominster',
            state='MA',
            zip_code='01453',
            name='DoubleTree by Hilton Hotel Leominster',
            description='A pet-friendly hotel offering comfortable accommodations and amenities for guests traveling with pets.',
            website='https://www.hilton.com/en/hotels/lsmzdt-doubltree-leominster/',
            email='info@hilton.com',
            phone='9785349000',
            price='$$$',
            set_hours="yes",
            mon_open='0000',
            mon_close='2359',
            tue_open='0000',
            tue_close='2359',
            wed_open='0000',
            wed_close='2359',
            thu_open='0000',
            thu_close='2359',
            fri_open='0000',
            fri_close='2359',
            sat_open='0000',
            sat_close='2359',
            sun_open='0000',
            sun_close='2359',
        ),
        Business(
            owner_id=47,
            category_id=6,
            address='2 Kirkland St',
            city='Cambridge',
            state='MA',
            zip_code='02138',
            name='Harvard Yard',
            description='A historic park and walking area that welcomes leashed pets, offering a scenic and pet-friendly environment for walks.',
            website='https://www.harvard.edu/visit/',
            email='info@harvard.edu',
            set_hours="no"
        ),
        Business(
            owner_id=40,
            category_id=7,
            address='347 Highland Ave',
            city='Salem',
            state='MA',
            zip_code='01970',
            name='Northeast Animal Shelter',
            description='An adoption center dedicated to rescuing and finding homes for homeless pets, providing shelter, medical care, and adoption services.',
            website='https://www.northeastanimalshelter.org/',
            email='info@northeastanimalshelter.org',
            phone='9787459888',
            set_hours="yes",
            mon_open='1100',
            mon_close='1900',
            tue_open='1100',
            tue_close='1900',
            wed_open='1100',
            wed_close='1900',
            thu_open='1100',
            thu_close='1900',
            fri_open='1100',
            fri_close='1900',
            sat_open='1000',
            sat_close='1700',
            sun_open='1000',
            sun_close='1700',
        ),
        Business(
            # id 8
            owner_id=25,
            category_id=8,
            address='10 Henshaw St',
            city='Woburn',
            state='MA',
            zip_code='01801',
            name='Petrichor Aquamation',
            description='Eco-friendly pet cremation service offering water-based cremation and memorial services for pets.',
            website='https://www.petrichoraquamation.com/',
            email='info@petrichoraquamation.com',
            phone='9785512699',
            set_hours="yes",
            mon_open='0900',
            mon_close='1700',
            tue_open='0900',
            tue_close='1700',
            wed_open='0900',
            wed_close='1700',
            thu_open='0900',
            thu_close='1700',
            fri_open='0900',
            fri_close='1700',
            sat_open='1000',
            sat_close='1400',
        ),
        Business(
            owner_id=47,
            category_id=1,
            address='941 Cole St',
            city='San Francisco',
            state='CA',
            zip_code='94117',
            name='Zazie',
            description='A popular French bistro that welcomes dogs on their heated patio. Offering delicious brunch options, and even a dog menu!',
            price='$$',
            website='https://zaziesf.com/',
            phone='4155645332',
            set_hours="yes",
            mon_open='0800',
            mon_close='1400',
            tue_open='0800',
            tue_close='1400',
            wed_open='0800',
            wed_close='1400',
            thu_open='0800',
            thu_close='1400',
            fri_open='0800',
            fri_close='1400',
            sat_open='0900',
            sat_close='1400',
            sun_open='0900',
            sun_close='1400',
        ),
        Business(
            owner_id=12,
            category_id=3,
            address='420 Hegenberger Rd',
            city='Oakland',
            state='CA',
            zip_code='94621',
            name='Citizen Canine',
            description='Offers all-suite overnight dog boarding and doggie daycare near Oakland International Airport, known for their luxurious care.',
            website='https://www.citizencanine.net/',
            phone='5105621750',
            set_hours="no"
        ),
        Business(
            owner_id=8,
            category_id=6,
            address='3300 Joaquin Miller Rd',
            city='Oakland',
            state='CA',
            zip_code='94602',
            name='Joaquin Miller Park',
            description='A dog-friendly park offering vast hiking trails, picnic areas, and an off-leash dog area. Perfect for outdoor activities with pets.',
            website='https://www.oaklandca.gov/parks/joaquin-miller-park',
            set_hours="no"
        ),
        Business(
            owner_id=19,
            category_id=7,
            address='1101 29th Ave',
            city='Oakland',
            state='CA',
            zip_code='94601',
            name='Oakland Animal Services',
            description='Oakland Animal Services provides adoption opportunities for pets, including dogs, cats, and small animals. They focus on rehoming and rescuing animals.',
            website='https://www.oaklandanimalservices.org/',
            phone='5105355602',
            set_hours="yes",
            wed_open='1600',
            wed_close='2000',
            thu_open='1600',
            thu_close='2000',
            fri_open='1600',
            fri_close='2000',
            sat_open='1200',
            sat_close='1700',
            sun_open='1200',
            sun_close='1700',
        ),
        Business(
            owner_id=33,
            category_id=2,
            address='720 Valencia St',
            city='San Francisco',
            state='CA',
            zip_code='94110',
            name='Mission Pet Hospital',
            description='A full-service veterinary hospital offering a range of services from wellness exams to surgery and dental care, committed to the health of pets.',
            website='https://www.missionpet.com/',
            phone='4155521969',
            set_hours="yes",
            mon_open='0800',
            mon_close='1800',
            tue_open='0800',
            tue_close='1800',
            wed_open='0800',
            wed_close='1800',
            thu_open='0800',
            thu_close='1800',
            fri_open='0800',
            fri_close='1800',
            sat_open='0800',
            sat_close='1700',
        ),
        Business(
            owner_id=3,
            category_id=1,
            address='1234 The Belt',
            city='Detroit',
            state='MI',
            zip_code='48226',
            name='The Skip',
            description='Pet-friendly cocktail bar offering a variety of drinks and a welcoming atmosphere for dogs.',
            website='https://www.theskipdetroit.com/',
            phone='3137243145',
            price='$$',
            set_hours="yes",
            mon_open='1500',
            mon_close='0200',
            tue_open='1500',
            tue_close='0200',
            wed_open='1500',
            wed_close='0200',
            thu_open='1500',
            thu_close='0200',
            fri_open='1500',
            fri_close='0200',
            sat_open='1500',
            sat_close='0200',
            sun_open='1500',
            sun_close='0200',
        ),
        Business(
            owner_id=12,
            category_id=2,
            address='3225 S Telegraph Rd',
            city='Dearborn',
            state='MI',
            zip_code='48124',
            name='VetSelect Animal Hospital',
            description='Full-service veterinary hospital providing care for pets in the Detroit area.',
            website='https://www.vetselect-dearborn.com/',
            phone='3135655566',
            set_hours="yes",
            mon_open='0900',
            mon_close='1700',
            tue_open='0900',
            tue_close='1700',
            wed_open='0900',
            wed_close='1700',
            thu_open='0900',
            thu_close='1700',
            fri_open='0900',
            fri_close='1700',
            sat_open='0900',
            sat_close='1200',
        ),
        Business(
            owner_id=8,
            category_id=3,
            address='1221 E 9 Mile Rd',
            city='Ferndale',
            state='MI',
            zip_code='48220',
            name='Canine To Five',
            description='Dog daycare, boarding, and grooming services with a friendly atmosphere for all pets.',
            website='https://www.caninetofive.com/',
            phone='2485565675',
            price='$$',
            set_hours="yes",
            mon_open='0700',
            mon_close='1900',
            tue_open='0700',
            tue_close='1900',
            wed_open='0700',
            wed_close='1900',
            thu_open='0700',
            thu_close='1900',
            fri_open='0700',
            fri_close='1900',
            sat_open='0900',
            sat_close='1700',
            sun_open='0900',
            sun_close='1700',
        ),
        Business(
            owner_id=15,
            category_id=4,
            address='18362 Fenkell St',
            city='Detroit',
            state='MI',
            zip_code='48223',
            name='Detroit K-9 Pet Supplies',
            description='Pet store offering a variety of pet supplies, food, and accessories.',
            website='https://www.citybarkdetroit.com/',
            phone='3133971097',
            price='$$',
            set_hours="yes",
            mon_open='1000',
            mon_close='1800',
            tue_open='1000',
            tue_close='1800',
            wed_open='1000',
            wed_close='1800',
            thu_open='1000',
            thu_close='1800',
            fri_open='1000',
            fri_close='1800',
            sat_open='1000',
            sat_close='1800',
        ),
        Business(
            owner_id=22,
            category_id=5,
            address='84 E Ferry St',
            city='Detroit',
            state='MI',
            zip_code='48202',
            name='The Inn on Ferry Street',
            description='Pet-friendly boutique hotel offering a unique and comfortable stay in Detroit.',
            website='http://innonferrystreetdetroit.com/',
            phone='8446200268',
            price='$$$',
            set_hours="yes",
            mon_open='0000',
            mon_close='2359',
            tue_open='0000',
            tue_close='2359',
            wed_open='0000',
            wed_close='2359',
            thu_open='0000',
            thu_close='2359',
            fri_open='0000',
            fri_close='2359',
            sat_open='0000',
            sat_close='2359',
            sun_open='0000',
            sun_close='2359',
        ),
        Business(
            owner_id=10,
            category_id=6,
            address='910 Merrill Plaisance St',
            city='Detroit',
            state='MI',
            zip_code='48203',
            name='Palmer Park',
            description='Public park offering trails, open spaces, and areas for dogs to play and explore.',
        ),
        Business(
            owner_id=5,
            category_id=7,
            address='24429 Grand River Ave',
            city='Detroit',
            state='MI',
            zip_code='48219',
            name='Detroit Dog Rescue',
            description='A nonprofit organization in Detroit is dedicated to rescuing, rehabilitating, and rehoming stray and homeless dogs.',
            website='https://detroitdogrescue.com/',
            phone='3134588014',
            set_hours="yes",
            mon_open='0900',
            mon_close='1700',
            tue_open='0900',
            tue_close='1700',
            wed_open='0900',
            wed_close='1700',
            thu_open='0900',
            thu_close='1700',
            fri_open='0900',
            fri_close='1700',
            sat_open='1000',
            sat_close='1400',
        ),
        Business(
            owner_id=19,
            category_id=8,
            city='Ann Arbor',
            state='MI',
            zip_code='48107',
            name='Kat Ku Modern Pet Photos',
            description='For those who LOVE their furry best friends. On-location & natural light photographer specializing in modern & candid pet photos. Serving Ann Arbor & Detroit, MI. Available for private and commercial work.',
            website='https://www.katkuphotography.com',
            phone='7344940160',
            set_hours="yes",
            mon_open='0900',
            mon_close='1700',
            tue_open='0900',
            tue_close='1700',
            wed_open='0900',
            wed_close='1700',
            thu_open='0900',
            thu_close='1700',
            fri_open='0900',
            fri_close='1700',
        ),
        Business(
            owner_id=38,
            category_id=1,
            address='6501 Aurora Ave N',
            city='Seattle',
            state='WA',
            zip_code='98103',
            name='Bongos',
            description='A beach-themed Caribbean restaurant near Green Lake with outdoor dining area filled with sand, allowing pets to join while you enjoy Caribbean and Cuban food.',
            website='https://www.bongosseattle.com/',
            phone='2064208548',
            price='$$',
            set_hours="yes",
            wed_open='1100',
            wed_close='2100',
            thu_open='1100',
            thu_close='2100',
            fri_open='1100',
            fri_close='2100',
            sat_open='1100',
            sat_close='2100',
            sun_open='1100',
            sun_close='2100',
        ),
        Business(
            owner_id=12,
            category_id=1,
            address='13310 Bel-Red Rd',
            city='Bellevue',
            state='WA',
            zip_code='98005',
            name='MOX Boarding House',
            description='A board game themed eatery offering a wide range of international and traditional cuisine with a free board game library, pets are welcome in the outdoor seating area.',
            website='https://www.moxboardinghouse.com/',
            phone='4253263050',
            price='$$',
            set_hours="yes",
            mon_open='1100',
            mon_close='2200',
            tue_open='1100',
            tue_close='2200',
            wed_open='1100',
            wed_close='2200',
            thu_open='1100',
            thu_close='2200',
            fri_open='1100',
            fri_close='2300',
            sat_open='1100',
            sat_close='2300',
            sun_open='1100',
            sun_close='2200',
        ),
        Business(
            owner_id=3,
            category_id=4,
            address='2119 1st Ave',
            city='Seattle',
            state='WA',
            zip_code='98121',
            name='Mud Bay',
            description='A pet store offering a wide range of pet food, supplies, and toys. Pets are welcome to shop with their owners.',
            website='https://www.mudbay.com/',
            phone='2067282405',
            price='$$',
            set_hours="yes",
            mon_open='0900',
            mon_close='2000',
            tue_open='0900',
            tue_close='2000',
            wed_open='0900',
            wed_close='2000',
            thu_open='0900',
            thu_close='2000',
            fri_open='0900',
            fri_close='2000',
            sat_open='0900',
            sat_close='2000',
            sun_open='1000',
            sun_close='1800',
        ),
        Business(
            owner_id=20,
            category_id=4,
            address='6511 California Ave SW',
            city='Seattle',
            state='WA',
            zip_code='98136',
            name='Pet Elements',
            description='A pet supply store providing natural and organic food options for pets. Pets are welcome in the store.',
            website='https://www.petelements.com/',
            phone='2069320457',
            price='$$',
            set_hours="yes",
            mon_open='0900',
            mon_close='1900',
            tue_open='0900',
            tue_close='1900',
            wed_open='0900',
            wed_close='1900',
            thu_open='0900',
            thu_close='1900',
            fri_open='0900',
            fri_close='1900',
            sat_open='1000',
            sat_close='1800',
            sun_open='1100',
            sun_close='1700',
        ),
        Business(
            owner_id=15,
            category_id=2,
            address='815 Rainier Ave S',
            city='Seattle',
            state='WA',
            zip_code='98144',
            name='Rainier Veterinary Hospital',
            description='Full-service veterinary hospital providing medical, surgical, and dental care for pets.',
            website='https://www.rainiervet.com/',
            phone='2063244144',
            set_hours="yes",
            mon_open='0800',
            mon_close='1800',
            tue_open='0800',
            tue_close='1800',
            wed_open='0800',
            wed_close='1800',
            thu_open='0800',
            thu_close='1800',
            fri_open='0800',
            fri_close='1800',
            sat_open='0800',
            sat_close='1600',
        ),
        Business(
            owner_id=7,
            category_id=3,
            address='5219 72nd St E,',
            city='Tacoma',
            state='WA',
            zip_code='98443',
            name='Dawg Tired Play Days',
            description='Providing dog walking, boarding, grooming, and pet sitting services in the Seattle area.',
            website='https://dawgtiredplaydays.com/',
            phone='2062255746',
            price='$$$',
            set_hours="yes",
            mon_open='0700',
            mon_close='1900',
            tue_open='0700',
            tue_close='1900',
            wed_open='0700',
            wed_close='1900',
            thu_open='0700',
            thu_close='1900',
            fri_open='0700',
            fri_close='1900',
            sat_open='0800',
            sat_close='1800',
            sun_open='0800',
            sun_close='1800',
        ),
        Business(
            owner_id=10,
            category_id=4,
            address='3401 Evanston Ave N',
            city='Seattle',
            state='WA',
            zip_code='98103',
            name='Fremont Sunday Street Market',
            description='All-year weekly spread of antique, art, clothes, tools & junk plus food trucks selling street food.',
            website='http://www.fremontmarket.com/',
            sun_open='1000',
            sun_close='1600',
        ),
        Business(
            owner_id=25,
            category_id=6,
            address='1635 11th Ave',
            city='Seattle',
            state='WA',
            zip_code='98122',
            name='Cal Anderson Park',
            description='A public park offering open spaces, a dog park, and various recreational activities for pets and their owners.',
            website='https://www.seattle.gov/parks/find/parks/cal-anderson-park',
            phone='2066844075',
            set_hours="yes",
            mon_open='0400',
            mon_close='2300',
            tue_open='0400',
            tue_close='2300',
            wed_open='0400',
            wed_close='2300',
            thu_open='0400',
            thu_close='2300',
            fri_open='0400',
            fri_close='2300',
            sat_open='0400',
            sat_close='2300',
            sun_open='0400',
            sun_close='2300',
        ),
        Business(
            owner_id=5,
            category_id=1,
            address='700 SE Washington Ave',
            city='Minneapolis',
            state='MN',
            zip_code='55414',
            name='Sally\'s Saloon',
            description='Sally\'s Saloon welcomes dogs on their outdoor patio. Enjoy a variety of bar fare and drinks with your furry friend.',
            website='https://salsumn.com/',
            phone='6122081388',
            price='$$',
            set_hours='yes',
            mon_open='1100',
            mon_close='0200',
            tue_open='1100',
            tue_close='0200',
            wed_open='1100',
            wed_close='0200',
            thu_open='1100',
            thu_close='0200',
            fri_open='1100',
            fri_close='0200',
            sat_open='1100',
            sat_close='0200',
            sun_open='1100',
            sun_close='0200',
        ),
        Business(
            owner_id=43,
            category_id=2,
            address='5669 Duluth St',
            city='Golden Valley',
            state='MN',
            zip_code='55422',
            name='VCA All About Pets Animal Hospital',
            description='VCA All About Pets provides comprehensive veterinary services and welcomes pets for routine check-ups, surgery, and emergency care.',
            website='https://vcahospitals.com/all-about-pets',
            phone='7635464452',
            set_hours='yes',
            mon_open='0700',
            mon_close='1900',
            tue_open='0700',
            tue_close='1900',
            wed_open='0700',
            wed_close='1900',
            thu_open='0700',
            thu_close='1900',
            fri_open='0700',
            fri_close='1900',
            sat_open='0800',
            sat_close='1600',
        ),
        Business(
            owner_id=9,
            category_id=3,
            address='7020 Walker St',
            city='St Louis Park',
            state='MN',
            zip_code='55418',
            name='Pampered Pooch Playground',
            description='Pampered Pooch Playground offers dog daycare, boarding, and grooming services with a focus on fun and safety for your pets.',
            website='https://www.pamperedpoochplayground.com',
            phone='3202787804',
            price='$$',
            set_hours='yes',
            mon_open='0630',
            mon_close='1900',
            tue_open='0630',
            tue_close='1900',
            wed_open='0630',
            wed_close='1900',
            thu_open='0630',
            thu_close='1900',
            fri_open='0630',
            fri_close='1900',
            sat_open='0900',
            sat_close='1800',
            sun_open='0900',
            sun_close='1800',
        ),
        Business(
            owner_id=22,
            category_id=4,
            address='2106 Lyndale Ave S',
            city='Minneapolis',
            state='MN',
            zip_code='55405',
            name='Urban Tails Pet Supply',
            description='Urban Tails Pet Supply Local Pet Food and Supply Store is a Healthy Pet Shop with everything you need for your Dogs & Cats.',
            website='https://urbantailspet.com/',
            phone='6128790709',
            price='$$',
            set_hours='yes',
            mon_open='0900',
            mon_close='2000',
            tue_open='0900',
            tue_close='2000',
            wed_open='0900',
            wed_close='2000',
            thu_open='0900',
            thu_close='2000',
            fri_open='0900',
            fri_close='2000',
            sat_open='0900',
            sat_close='1800',
            sun_open='1000',
            sun_close='1800',
        ),
        Business(
            owner_id=7,
            category_id=5,
            address='1001 Marquette Ave S',
            city='Minneapolis',
            state='MN',
            zip_code='55403',
            name='Hilton Minneapolis',
            description='Hilton Minneapolis is a pet-friendly hotel located in the heart of downtown, offering comfort for you and your pet during your stay.',
            website='https://www.hilton.com/en/hotels/mspmhhf-hilton-minneapolis',
            phone='6123761000',
            price='$$$',
            set_hours='yes',
            mon_open='0000',
            mon_close='2359',
            tue_open='0000',
            tue_close='2359',
            wed_open='0000',
            wed_close='2359',
            thu_open='0000',
            thu_close='2359',
            fri_open='0000',
            fri_close='2359',
            sat_open='0000',
            sat_close='2359',
            sun_open='0000',
            sun_close='2359',
        ),
        Business(
            owner_id=11,
            category_id=6,
            address='4801 Minnehaha Ave',
            city='Minneapolis',
            state='MN',
            zip_code='55417',
            name='Minnehaha Regional Park',
            description='Minnehaha Regional Park offers trails, picnic areas, and a dog park. It\'s a great spot for outdoor activities with your pet.',
            website='https://www.minneapolisparks.org/parks__destinations/parks__lakes/minnehaha_regional_park',
            set_hours='yes',
            mon_open='0600',
            mon_close='2200',
            tue_open='0600',
            tue_close='2200',
            wed_open='0600',
            wed_close='2200',
            thu_open='0600',
            thu_close='2200',
            fri_open='0600',
            fri_close='2200',
            sat_open='0600',
            sat_close='2200',
            sun_open='0600',
            sun_close='2200',
        ),
        Business(
            owner_id=19,
            category_id=7,
            address='845 Meadow Ln N',
            city='Golden Valley',
            state='MN',
            zip_code='55422',
            name='Animal Humane Society',
            description='The Animal Humane Society offers pet adoption services and also provides resources for pet owners in the community.',
            website='https://www.animalhumanesociety.org',
            phone='9524357738',
            set_hours='yes',
            mon_open='1200',
            mon_close='1800',
            tue_open='1200',
            tue_close='1800',
            wed_open='1200',
            wed_close='1800',
            thu_open='1200',
            thu_close='1800',
            fri_open='1200',
            fri_close='1800',
            sat_open='1200',
            sat_close='1800',
            sun_open='1200',
            sun_close='1800',
        ),
        Business(
            owner_id=3,
            category_id=3,
            city='Minneapolis',
            state='MN',
            zip_code='55417',
            name='Paw Print Pet Sitting',
            description='Paw Print Pet Sitting offers professional pet sitting and dog walking services to ensure your pet is well cared for while you are away.',
            website='https://www.pawprintpetsitting.com',
            phone='6122546176',
            price='$$',
            set_hours='no'
        ),
        Business(
            owner_id=34,
            category_id=1,
            address='3750 Main St STE 103',
            city='Riverside',
            state='CA',
            zip_code='92501',
            name='The Salted Pig',
            description='The Salted Pig is a gastropub that welcomes dogs on their outdoor patio.',
            phone='9517425664',
            price='$$',
            set_hours="yes",
            mon_open='1100',
            mon_close='2200',
            tue_open='1100',
            tue_close='2200',
            wed_open='1100',
            wed_close='2200',
            thu_open='1100',
            thu_close='2200',
            fri_open='1100',
            fri_close='2300',
            sat_open='1100',
            sat_close='2300',
            sun_open='1100',
            sun_close='2100',
        ),
        Business(
            owner_id=42,
            category_id=2,
            address='1327 W Colton Ave',
            city='Redlands',
            state='CA',
            zip_code='92373',
            name='Redlands Animal Hospital',
            description='Providing comprehensive veterinary care for pets in Redlands and the surrounding areas.',
            phone='9097932181',
            set_hours="yes",
            mon_open='0800',
            mon_close='1800',
            tue_open='0800',
            tue_close='1800',
            wed_open='0800',
            wed_close='1800',
            thu_open='0800',
            thu_close='1800',
            fri_open='0800',
            fri_close='1800',
            sat_open='0800',
            sat_close='1400',
        ),
        Business(
            owner_id=19,
            category_id=3,
            address='1512 Barton Rd',
            city='Redlands',
            state='CA',
            zip_code='92373',
            name='Flawless Pet Grooming',
            description='The Flawless School of Pet Grooming is dedicated to raising the standards of the grooming profession. The most modern, expert, and thorough methods are used.',
            website='https://www.flawlesspetgrooming.com/',
            phone='9097487779',
            set_hours="yes",
            mon_open='0700',
            mon_close='1800',
            tue_open='0700',
            tue_close='1800',
            wed_open='0700',
            wed_close='1800',
            thu_open='0700',
            thu_close='1800',
            fri_open='0700',
            fri_close='1800',
            sat_open='0700',
            sat_close='1800',
        ),
        Business(
            owner_id=5,
            category_id=4,
            address='5225 Canyon Crest Dr',
            city='Riverside',
            state='CA',
            zip_code='92507',
            name='Canyon Crest Towne Centre',
            description='An outdoor shopping center where pets are welcome in many of the stores.',
            phone='9516861222',
            price='$$',
            set_hours="yes",
            mon_open='1000',
            mon_close='2100',
            tue_open='1000',
            tue_close='2100',
            wed_open='1000',
            wed_close='2100',
            thu_open='1000',
            thu_close='2100',
            fri_open='1000',
            fri_close='2100',
            sat_open='1000',
            sat_close='2100',
            sun_open='1100',
            sun_close='1800',
        ),
        Business(
            owner_id=23,
            category_id=5,
            address='3500 Market St',
            city='Riverside',
            state='CA',
            zip_code='92501',
            name='Hyatt Place Riverside Downtown',
            description='A pet-friendly hotel in the heart of downtown Riverside.',
            phone='9513213500',
            price='$$$',
            set_hours="yes",
            mon_open='0000',
            mon_close='2359',
            tue_open='0000',
            tue_close='2359',
            wed_open='0000',
            wed_close='2359',
            thu_open='0000',
            thu_close='2359',
            fri_open='0000',
            fri_close='2359',
            sat_open='0000',
            sat_close='2359',
            sun_open='0000',
            sun_close='2359',
        ),
        Business(
            owner_id=11,
            category_id=6,
            address='4706 Mount Rubidoux Dr',
            city='Riverside',
            state='CA',
            zip_code='92506',
            name='Mount Rubidoux Park',
            description='A scenic park with hiking trails where dogs are welcome on leash.',
        )]
    
    db.session.add(petagogy)
    db.session.add(mishka)
    db.session.add(leo_j_ryan)
    db.session.add(dumpling_home)
    db.session.add(bakery)
    db.session.add(caroline)
    db.session.add(exotic_vet)
    db.session.add(perch)
    db.session.add(salondog)
    db.session.add_all(businesses_2)
    db.session.commit()



# Uses a raw SQL query to TRUNCATE or DELETE the users table. SQLAlchemy doesn't
# have a built in function to do this. With postgres in production TRUNCATE
# removes all the data from the table, and RESET IDENTITY resets the auto
# incrementing primary key, CASCADE deletes any dependent entities.  With
# sqlite3 in development you need to instead use DELETE to remove all data and
# it will reset the primary keys for you as well.
def undo_businesses():
    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.businesses RESTART IDENTITY CASCADE;")
    else:
        db.session.execute(text("DELETE FROM businesses"))

    db.session.commit()
