from app.models import db, Business, environment, SCHEMA
from sqlalchemy.sql import text

def seed_businesses_2():
    businesses_3 = [
        Business(
            owner_id=37,
            category_id=7,
            address='6165 Industrial Ave',
            city='Riverside',
            state='CA',
            zip_code='92504',
            name='Mary S. Roberts Pet Adoption Center',
            description='A non-profit organization dedicated to finding loving homes for pets',
            website='https://www.petsadoption.com/',
            phone='9516884340',
            set_hours="yes",
            mon_open='1200',
            mon_close='1800',
            tue_open='1200',
            tue_close='1800',
            wed_open='1200',
            wed_close='1800',
            thu_open='1200',
            thu_close='1800',
            fri_open='1200',
            fri_close='1800',
            sat_open='1200',
            sat_close='1800',
            sun_open='1200',
            sun_close='1600',
        ),
        Business(
            owner_id=28,
            category_id=8,
            address='2085 Rustin Ave',
            city='Riverside',
            state='CA',
            zip_code='92507',
            name='Pure Photography',
            description='Your fur kids are your family! No matter what type of critter you care for, we can create a gorgeous portrait.',
            website='https://www.mypurephotos.com/pets',
            phone='9515347457',
        ),
        Business(
            owner_id=25,
            category_id=1,
            address='1710 Millenia Avenue',
            city='Chula Vista',
            state='CA',
            zip_code='91915',
            name='Ayres Hotel San Diego South - Chula Vista',
            description='Pet-friendly hotel offering convenient accommodations with a $60 pet fee per reservation. Enjoy onsite amenities and explore local dining options nearby.',
            website='https://www.ayreshotels.com',
            phone='6198708400',
            mon_open='1500',
            mon_close='2300',
            tue_open='1500',
            tue_close='2300',
            wed_open='1500',
            wed_close='2300',
            thu_open='1500',
            thu_close='2300',
            fri_open='1500',
            fri_close='2300',
            sat_open='1500',
            sat_close='2300',
            sun_open='1500',
            sun_close='2300',
        ),
        Business(
            owner_id=5,
            category_id=3,
            # address='San Diego-Chula Vista-Carlsbad',
            city='San Diego',
            state='CA',
            zip_code='92129',
            name='Homeridge Mobile Vet',
            description='Mobile veterinary services offering convenience and comprehensive care for your pets at your home. Services include vaccinations, deworming, grooming, and more.',
            website='https://www.homeridgemobilevet.com',
            phone='8667601461',
            mon_open='1000',
            mon_close='1800',
            tue_open='1000',
            tue_close='1800',
            wed_open='1000',
            wed_close='1800',
            thu_open='1000',
            thu_close='1800',
            fri_open='1000',
            fri_close='1800',
            sat_open='1000',
            sat_close='1800',
            sun_open='1000',
            sun_close='1800',
        ),
        Business(
            owner_id=14,
            category_id=6,
            address='2710 Manchester Ave',
            city='Cardiff-by-the-Sea',
            state='CA',
            zip_code='92007',
            name='San Elijo Lagoon Ecological Reserve',
            description='A large tidal wetland offering nature trails for hiking, birdwatching, and enjoying natural beauty with your pets.',
            website='https://www.sdparks.org',
            phone='7606343026',
            mon_open='0700',
            mon_close='1900',
            tue_open='0700',
            tue_close='1900',
            wed_open='0700',
            wed_close='1900',
            thu_open='0700',
            thu_close='1900',
            fri_open='0700',
            fri_close='1900',
            sat_open='0700',
            sat_close='1900',
            sun_open='0700',
            sun_close='1900',
        ),
        Business(
            owner_id=9,
            category_id=1,
            address='641 S Coast Hwy 101',
            city='Encinitas',
            state='CA',
            zip_code='92024',
            name='The Bier Garden of Encinitas',
            description='Dog-friendly restaurant offering a variety of beers and a great atmosphere for pet owners.',
            website='https://www.biergardenencinitas.com',
            phone='7606322437',
            price='$$',
            mon_open='1100',
            mon_close='2100',
            tue_open='1100',
            tue_close='2100',
            wed_open='1100',
            wed_close='2100',
            thu_open='1100',
            thu_close='2100',
            fri_open='1100',
            fri_close='2200',
            sat_open='1000',
            sat_close='2200',
            sun_open='1000',
            sun_close='2100',
        ),
        Business(
            owner_id=11,
            category_id=4,
            address='123 N El Camino Real',
            city='Encinitas',
            state='CA',
            zip_code='92024',
            name='Carlsbad Pet & Feed',
            description='We want the best for your pets! We offer a wide variety of food & supplies to keep them happy and healthy.',
            website='https://carlsbadpetandfeed.net/',
            phone='7607048003',
            mon_open='0800',
            mon_close='1800',
            tue_open='0800',
            tue_close='1800',
            wed_open='0800',
            wed_close='1800',
            thu_open='0800',
            thu_close='1800',
            fri_open='0800',
            fri_close='1800',
            sat_open='0800',
            sat_close='1800',
            sun_open='1000',
            sun_close='1700',
        ),
        Business(
            owner_id=2,
            category_id=6,
            address='1943 Adams Ave',
            city='San Diego',
            state='CA',
            zip_code='92116',
            name='Old Trolley Barn Park',
            description='A pet-friendly park perfect for a casual stroll or a fun day out with your pets.',
            website='https://www.sandiego.gov/park-and-recreation',
            mon_open='0600',
            mon_close='2200',
            tue_open='0600',
            tue_close='2200',
            wed_open='0600',
            wed_close='2200',
            thu_open='0600',
            thu_close='2200',
            fri_open='0600',
            fri_close='2200',
            sat_open='0600',
            sat_close='2200',
            sun_open='0600',
            sun_close='2200',
        ),
        Business(
            owner_id=8,
            category_id=3,
            address='3949 Ohio St',
            city='San Diego',
            state='CA',
            zip_code='92104',
            name='South Bark Dog Wash',
            description='A self-service dog wash offering pet grooming and a variety of dog care products.',
            website='https://www.southbark.com',
            phone='6192327387',
            price='$$',
            mon_open='0900',
            mon_close='1700',
            tue_open='0900',
            tue_close='1700',
            wed_open='0900',
            wed_close='1700',
            thu_open='0900',
            thu_close='1700',
            fri_open='0900',
            fri_close='1700',
            sat_open='0900',
            sat_close='1700',
            sun_open='1000',
            sun_close='1600',
        ),
        Business(
            owner_id=23,
            category_id=1,
            address='2219 30th St',
            city='San Diego',
            state='CA',
            zip_code='92104',
            name='The Rose Wine Bar',
            description='Dog-friendly wine bar in South Park offering a selection of wines, craft beers, and small plates.',
            website='https://www.therosewinebar.com',
            price='$$',
            mon_open='1600',
            mon_close='2200',
            tue_open='1600',
            tue_close='2200',
            wed_open='1600',
            wed_close='2200',
            thu_open='1600',
            thu_close='2200',
            fri_open='1600',
            fri_close='2300',
            sat_open='1100',
            sat_close='2300',
            sun_open='1100',
            sun_close='2200',
        ),
        Business(
            owner_id=4,
            category_id=1,
            address='1810 N Highland Ave',
            city='Tampa',
            state='FL',
            zip_code='33602',
            name='Ulele',
            description='Popular Tampa Riverwalk hotspot showcasing Florida\'s best local flavors in a relaxed outdoor atmosphere.',
            website='https://www.ulele.com/',
            phone='8139994952',
            price='$$$',
            set_hours="yes",
            mon_open='1100',
            mon_close='2200',
            tue_open='1100',
            tue_close='2200',
            wed_open='1100',
            wed_close='2200',
            thu_open='1100',
            thu_close='2200',
            fri_open='1100',
            fri_close='2300',
            sat_open='1100',
            sat_close='2300',
            sun_open='1100',
            sun_close='2200',
        ),
        Business(
            owner_id=12,
            category_id=3,
            address='2900 Central Ave',
            city='St. Petersburg',
            state='FL',
            zip_code='33712',
            name='Mutts and Martinis',
            description='Craft cocktails, games on the big screens, and your furry friend splashing in the doggie water park.',
            website='https://muttsandmartinisoncentral.com',
            phone='7272846750',
            price='$$',
            set_hours="yes",
            mon_open='1600',
            mon_close='2200',
            tue_open='1600',
            tue_close='2200',
            wed_open='1600',
            wed_close='2200',
            thu_open='1600',
            thu_close='2200',
            fri_open='1600',
            fri_close='2300',
            sat_open='1200',
            sat_close='2300',
            sun_open='1200',
            sun_close='2100',
        ),
        Business(
            owner_id=21,
            category_id=1,
            address='1962 1st Ave S',
            city='St. Petersburg',
            state='FL',
            zip_code='33712',
            name='Pinellas Ale Works Brewery',
            description='Experience award-winning craft beer infused with canine-inspired charm in St. Petersburg\'s Grand Central District.',
            website='https://www.pawbeer.com/',
            phone='7272350970',
            price='$$',
            set_hours="yes",
            mon_open='1600',
            mon_close='2200',
            tue_open='1600',
            tue_close='2200',
            wed_open='1600',
            wed_close='2200',
            thu_open='1600',
            thu_close='2200',
            fri_open='1200',
            fri_close='2300',
            sat_open='1200',
            sat_close='2300',
            sun_open='1200',
            sun_close='2200',
        ),
        Business(
            owner_id=7,
            category_id=6,
            address='3500 Pinellas Bayway S',
            city='Tierra Verde',
            state='FL',
            zip_code='33715',
            name='Topwater Kayak Outpost',
            description='Dogs are welcome to join their owners on a kayaking adventure in the calm waters off of Fort De Soto Beach.',
            phone='7278641991',
            set_hours="yes",
            mon_open='0900',
            mon_close='1700',
            tue_open='0900',
            tue_close='1700',
            wed_open='0900',
            wed_close='1700',
            thu_open='0900',
            thu_close='1700',
            fri_open='0900',
            fri_close='1700',
            sat_open='0900',
            sat_close='1700',
            sun_open='0900',
            sun_close='1700',
        ),
        Business(
            owner_id=5,
            category_id=1,
            address='2300 Central Ave',
            city='St. Petersburg',
            state='FL',
            zip_code='33712',
            name='The Dog Bar',
            description='Sit. Stay. Drink. The Dog Bar is St. Pete\'s original dog lover\'s stomping ground, a sprawling venue that caters to four-legged guests and the humans who love them.',
            website='https://www.dogbarstpete.com/',
            phone='7273174968',
            price='$$',
            set_hours="yes",
            mon_open='1100',
            mon_close='0000',
            tue_open='1100',
            tue_close='0000',
            wed_open='1100',
            wed_close='0000',
            thu_open='1100',
            thu_close='0000',
            fri_open='1100',
            fri_close='0100',
            sat_open='1100',
            sat_close='0100',
            sun_open='1100',
            sun_close='0000',
        ),
        Business(
            owner_id=19,
            category_id=6,
            address='3500 Pinellas Bayway S',
            city='Tierra Verde',
            state='FL',
            zip_code='33715',
            name='Fort De Soto Dog Park & Beach',
            description='Unspoiled nature abounds—and Fido will love frolicking in the surf.',
            phone='7275822267',
            set_hours="yes",
            mon_open='0700',
            mon_close='1900',
            tue_open='0700',
            tue_close='1900',
            wed_open='0700',
            wed_close='1900',
            thu_open='0700',
            thu_close='1900',
            fri_open='0700',
            fri_close='1900',
            sat_open='0700',
            sat_close='1900',
            sun_open='0700',
            sun_close='1900',
        ),
        Business(
            owner_id=11,
            category_id=3,
            address='3001 Central Ave, St',
            city='St. Petersburg',
            state='FL',
            zip_code='33713',
            name='St. PetersBark Natural Pet Market',
            description='Specialty pet supply store offering natural and eco-friendly pet products.',
            website='https://www.stpetersbark.com/',
            phone='7273626165',
            set_hours="yes",
            mon_open='1000',
            mon_close='1800',
            tue_open='1000',
            tue_close='1800',
            wed_open='1000',
            wed_close='1800',
            thu_open='1000',
            thu_close='1800',
            fri_open='1000',
            fri_close='1800',
            sat_open='1000',
            sat_close='1800',
            sun_open='1200',
            sun_close='1700',
        ),
        Business(
            owner_id=14,
            category_id=6,
            address='400 2nd Ave NE Slip Q47',
            city='St. Petersburg',
            state='FL',
            zip_code='33701',
            name='Tampa Bay Sunset and Eco Tour',
            description='Private pontoon boat tours welcome dogs on board for a 2-hour cruise and sunset tour.',
            phone='7272914103',
            set_hours="yes",
            mon_open='0800',
            mon_close='2000',
            tue_open='0800',
            tue_close='2000',
            wed_open='0800',
            wed_close='2000',
            thu_open='0800',
            thu_close='2000',
            fri_open='0800',
            fri_close='2000',
            sat_open='0800',
            sat_close='2000',
            sun_open='0800',
            sun_close='2000',
        ),
        Business(
            owner_id=5,
            category_id=1,
            address='2339 W 44th Ave',
            city='Denver',
            state='CO',
            zip_code='80211',
            name='Sunny\'s',
            description='Sunny\'s is a dog-friendly breakfast joint serving organic and local ingredients with an extensive breakfast menu.',
            website='https://sunnysbreakfast.com/',
            phone='3034770005',
            price='$$',
            set_hours="yes",
            mon_open='0700',
            mon_close='1400',
            tue_open='0700',
            tue_close='1400',
            wed_open='0700',
            wed_close='1400',
            thu_open='0700',
            thu_close='1400',
            fri_open='0700',
            fri_close='1400',
            sat_open='0700',
            sat_close='1400',
            sun_open='0700',
            sun_close='1400',
        ),
        Business(
            owner_id=10,
            category_id=1,
            address='4363 Tennyson St',
            city='Denver',
            state='CO',
            zip_code='80212',
            name='Cozy Cottage',
            description='A small eatery with a dog-friendly seasonal outdoor patio, serving breakfast, brunch, and lunch with American and Mexican dishes.',
            website='https://cozyupdenver.com/',
            phone='3038559800',
            price='$$',
            set_hours="yes",
            mon_open='0700',
            mon_close='1400',
            tue_open='0700',
            tue_close='1400',
            wed_open='0700',
            wed_close='1400',
            thu_open='0700',
            thu_close='1400',
            fri_open='0700',
            fri_close='1400',
            sat_open='0700',
            sat_close='1400',
            sun_open='0700',
            sun_close='1400',
        ),
        Business(
            owner_id=15,
            category_id=6,
            address='1599 E 8th Ave',
            city='Denver',
            state='CO',
            zip_code='80218',
            name='Cheesman Park',
            description='A tranquil residential area, Cheesman Park centers on its namesake green space, with expansive lawns, shady jogging trails, a dramatic neoclassical pavilion and regular LGBT-oriented events.',
            set_hours="no"
        ),
        Business(
            owner_id=22,
            category_id=5,
            address='245 Columbine St',
            city='Denver',
            state='CO',
            zip_code='80206',
            name='Halcyon Hotel Cherry Creek',
            description='A dog-friendly boutique hotel in the fashionable Cherry Creek neighborhood with trendy restaurants and high-end shopping nearby.',
            website='https://www.halcyonhotelcherrycreek.com/',
            phone='7207725000',
            set_hours="no"
        ),
        Business(
            owner_id=7,
            category_id=3,
            address='3201 Walnut St',
            city='Denver',
            state='CO',
            zip_code='80205',
            name='Improper City',
            description='A venue with an outdoor patio welcoming well-behaved, leashed dogs, offering a rotating lineup of food trucks and craft cocktails.',
            website='https://www.impropercity.com/',
            phone='7206660043',
            price='$$',
            set_hours="yes",
            mon_open='0700',
            mon_close='1400',
            tue_open='0700',
            tue_close='1400',
            wed_open='0700',
            wed_close='1400',
            thu_open='0700',
            thu_close='1400',
            fri_open='0700',
            fri_close='1400',
            sat_open='0700',
            sat_close='1400',
            sun_open='0700',
            sun_close='1400',
        ),

        Business(
            owner_id=18,
            category_id=4,
            address='1503 Boulder St',
            city='Denver',
            state='CO',
            zip_code='80211',
            name='Three Dog Bakery',
            description='A bakery for dogs offering a wide selection of high-quality baked goods made of natural ingredients.',
            website='https://threedog.com/bakery/denver/',
            phone='3034770844',
            set_hours="yes",
            mon_open='0700',
            mon_close='1400',
            tue_open='0700',
            tue_close='1400',
            wed_open='0700',
            wed_close='1400',
            thu_open='0700',
            thu_close='1400',
            fri_open='0700',
            fri_close='1400',
            sat_open='0700',
            sat_close='1400',
            sun_open='0700',
            sun_close='1400',
        ),

        Business(
            owner_id=12,
            category_id=6,
            address='4201 S Parker Rd',
            city='Aurora',
            state='CO',
            zip_code='80014',
            name='Cherry Creek State Park',
            description='A large natural area offering hiking, swimming, cycling, camping, and more, with a fenced, off-leash 107-acre dog park.',
            phone='3036901166',
            website='https://cpw.state.co.us/placestogo/parks/CherryCreek',
            set_hours="no"
        ),

        Business(
            owner_id=29,
            category_id=1,
            address='2715 17th St',
            city='Denver',
            state='CO',
            zip_code='80211',
            name='Postino LoHi',
            description='A wine bar and brunch cafe with a spacious patio perfect for dogs, offering a long list of boutique wines and Italian dishes.',
            website='https://www.postinowinecafe.com/',
            phone='3034336363',
            price='$$$',
            set_hours="yes",
            mon_open='1100',
            mon_close='2300',
            tue_open='1100',
            tue_close='2300',
            wed_open='1100',
            wed_close='2300',
            thu_open='1100',
            thu_close='2300',
            fri_open='1100',
            fri_close='2300',
            sat_open='0900',
            sat_close='2300',
            sun_open='0900',
            sun_close='2300',
        ),
        Business(
            owner_id=14,
            category_id=1,
            address='2211 Market St',
            city='St. Louis',
            state='MO',
            zip_code='63103',
            name='Pear Tree Inn St. Louis Convention Center',
            description='Pet-friendly restaurant with a range of food options and a welcoming atmosphere for pets.',
            website='https://www.druryhotels.com',
            phone='3142413200',
            price='$$$$',
            set_hours="yes",
            mon_open='1100',
            mon_close='2100',
            tue_open='1100',
            tue_close='2100',
            wed_open='1100',
            wed_close='2100',
            thu_open='1100',
            thu_close='2100',
            fri_open='1100',
            fri_close='2200',
            sat_open='1100',
            sat_close='2200',
            sun_open='1100',
            sun_close='2000',
        ),
        Business(
            owner_id=22,
            category_id=5,
            address='400 Olive St',
            city='St. Louis',
            state='MO',
            zip_code='63102',
            name='The Pennywell St Louis Downtown',
            description='A pet-friendly hotel with a weight limit of 75 pounds, offering treats at the front desk and nearby potty spots.',
            website='https://www.thepennywellhotel.com',
            phone='3144360002',
            price='$$',
            set_hours="yes",
            mon_open='1600',
            mon_close='2300',
            tue_open='1600',
            tue_close='2300',
            wed_open='1600',
            wed_close='2300',
            thu_open='1600',
            thu_close='2300',
            fri_open='1600',
            fri_close='2300',
            sat_open='1600',
            sat_close='2300',
            sun_open='1600',
            sun_close='2300',
        ),
        Business(
            owner_id=7,
            category_id=8,
            address='5836 Macklind Ave',
            city='St. Louis',
            state='MO',
            zip_code='63109',
            name='Lynn Terry Photography',
            description='Lynn Terry is a seasoned professional bringing over 20 years of creative experience to the table.',
            website='https://www.lynnterry.com/',
            phone='3147495153',
            set_hours="no",
        ),
        Business(
            owner_id=19,
            category_id=6,
            address='13725 Marine Ave',
            city='St. Louis',
            state='MO',
            zip_code='63146',
            name='Creve Coeur Lake Memorial Park',
            description='A large park offering trails, a lake, and open areas for dogs to explore and enjoy outdoor activities.',
            set_hours="yes",
            mon_open='0600',
            mon_close='2100',
            tue_open='0600',
            tue_close='2100',
            wed_open='0600',
            wed_close='2100',
            thu_open='0600',
            thu_close='2100',
            fri_open='0600',
            fri_close='2100',
            sat_open='0600',
            sat_close='2100',
            sun_open='0600',
            sun_close='2100',
        ),
        Business(
            owner_id=10,
            category_id=2,
            address='132 N Meramec Ave',
            city='St. Louis',
            state='MO',
            zip_code='63105',
            name='VCA Clayton Animal Hospital',
            description='Providing comprehensive veterinary services including wellness exams, vaccinations, and emergency care.',
            phone='3148632400',
            set_hours="yes",
            mon_open='0800',
            mon_close='1800',
            tue_open='0800',
            tue_close='1800',
            wed_open='0800',
            wed_close='1800',
            thu_open='0800',
            thu_close='1800',
            fri_open='0800',
            fri_close='1800',
            sat_open='0800',
            sat_close='1300',
        ),
        Business(
            owner_id=25,
            category_id=1,
            address='One South Broadway',
            city='St. Louis',
            state='MO',
            zip_code='63102',
            name='Three Sixty Rooftop Bar',
            description='A pet-friendly rooftop bar offering panoramic views of the city along with a menu of drinks and small plates.',
            website='https://www.360-stl.com',
            phone='3142418439',
            price='$$$',
            set_hours="yes",
            mon_open='1500',
            mon_close='2300',
            tue_open='1500',
            tue_close='2300',
            wed_open='1500',
            wed_close='2300',
            thu_open='1500',
            thu_close='2300',
            fri_open='1500',
            fri_close='0100',
            sat_open='1500',
            sat_close='0100',
            sun_open='1500',
            sun_close='2300',
        ),
        Business(
            owner_id=8,
            category_id=6,
            address='345 North Rd W',
            city='St. Louis',
            state='MO',
            zip_code='63125',
            name='Jefferson Barracks Historical Park',
            description='A spacious park featuring walking trails, picnic areas, and open spaces where dogs can be on leash.',
            set_hours="yes",
            mon_open='0700',
            mon_close='1900',
            tue_open='0700',
            tue_close='1900',
            wed_open='0700',
            wed_close='1900',
            thu_open='0700',
            thu_close='1900',
            fri_open='0700',
            fri_close='1900',
            sat_open='0700',
            sat_close='1900',
            sun_open='0700',
            sun_close='1900',
        ),
        Business(
            owner_id=5,
            category_id=3,
            address='5210 Chippewa St',
            city='St Louis',
            state='MO',
            zip_code='63109',
            name='A Walk in the Park',
            description='Offering dog walking, pet sitting, and overnight care services with a personalized touch.',
            website='http://www.awalkintheparkgrooming.com/',
            phone='3148750087',
            set_hours="yes",
            mon_open='0800',
            mon_close='2000',
            tue_open='0800',
            tue_close='2000',
            wed_open='0800',
            wed_close='2000',
            thu_open='0800',
            thu_close='2000',
            fri_open='0800',
            fri_close='2000',
            sat_open='0900',
            sat_close='1700',
            sun_open='0900',
            sun_close='1700',
        )
    ]

    
    db.session.add_all(businesses_3)
    db.session.commit()



# Uses a raw SQL query to TRUNCATE or DELETE the users table. SQLAlchemy doesn't
# have a built in function to do this. With postgres in production TRUNCATE
# removes all the data from the table, and RESET IDENTITY resets the auto
# incrementing primary key, CASCADE deletes any dependent entities.  With
# sqlite3 in development you need to instead use DELETE to remove all data and
# it will reset the primary keys for you as well.
def undo_businesses_2():
    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.businesses RESTART IDENTITY CASCADE;")
    else:
        db.session.execute(text("DELETE FROM businesses"))

    db.session.commit()
