from app.models import db, Business, environment, SCHEMA
from sqlalchemy.sql import text

def seed_businesses_2B():
    businesses_3 = [
        Business(
            owner_id=45,
            category_id=1,
            address='523 8th St SE',
            city='Washington',
            state='DC',
            zip_code='20003',
            name='Ambar',
            description='A modern, rustic restaurant offering small plates inspired by the Danube River, Ambar warmly welcomes pets in their outdoor seating area.',
            website='https://www.ambarrestaurant.com',
            phone='2028133039',
            price='$',
            set_hours="yes",
            mon_open='1100',
            mon_close='2200',
            tue_open='1100',
            tue_close='2200',
            wed_open='1100',
            wed_close='2200',
            thu_open='1100',
            thu_close='2200',
            fri_open='1100',
            fri_close='2300',
            sat_open='1000',
            sat_close='2300',
            sun_open='1000',
            sun_close='2200',
        ),
        Business(
            owner_id=12,
            category_id=2,
            address='4105 Brandywine St NW',
            city='Washington',
            state='DC',
            zip_code='20016',
            name='Friendship Hospital for Animals',
            description='Full-service veterinary hospital providing comprehensive healthcare services, allowing pets in the lobby and designated waiting areas.',
            website='https://www.friendshiphospital.com',
            phone='2023637300',
            set_hours="no",
        ),
        Business(
            owner_id=8,
            category_id=3,
            address='4904 Wisconsin Ave NW',
            city='Washington',
            state='DC',
            zip_code='20016',
            name='Happy Paws',
            description='Offering dog walking, boarding, grooming, and pet sitting services, ensuring your pets are pampered and well taken care of.',
            website='https://www.happypawsdc.com',
            phone='2023637297',
            set_hours="yes",
            mon_open='0700',
            mon_close='1900',
            tue_open='0700',
            tue_close='1900',
            wed_open='0700',
            wed_close='1900',
            thu_open='0700',
            thu_close='1900',
            fri_open='0700',
            fri_close='1900',
            sat_open='0900',
            sat_close='1700',
        ),
        Business(
            owner_id=14,
            category_id=4,
            address='2772 S. Arlington Mill Dr.',
            city='Arlington',
            state='VA',
            zip_code='22206',
            name='Dogma Dog Bakery & Boutique',
            description='At Dogma Bakery & Boutique our passion and love for animals is part of everything we do. From the food and products we carry, to our fresh store baked treats to our grooming salons, we work to ensure your pets are treated like members of our family. ',
            website='https://www.dogmabakery.com/',
            email='shirlington@dogmabakery.com',
            phone='5714220370',
            price='$',
            set_hours="yes",
            mon_open='1000',
            mon_close='2000',
            tue_open='1000',
            tue_close='2000',
            wed_open='1000',
            wed_close='2000',
            thu_open='1000',
            thu_close='2000',
            fri_open='1000',
            fri_close='2000',
            sat_open='1000',
            sat_close='2000',
            sun_open='1100',
            sun_close='1800',
        ),
        Business(
            owner_id=21,
            category_id=5,
            address='1150 22nd St NW',
            city='Washington',
            state='DC',
            zip_code='20037',
            name='The Ritz-Carlton, Washington, D.C.',
            description='Luxurious pet-friendly hotel providing plush accommodations for both you and your pet, located in the heart of Washington, D.C.',
            website='https://www.ritzcarlton.com/en/hotels/washington-dc',
            phone='2028350500',
            price='$$$',
            set_hours="yes",
            mon_open='0000',
            mon_close='2359',
            tue_open='0000',
            tue_close='2359',
            wed_open='0000',
            wed_close='2359',
            thu_open='0000',
            thu_close='2359',
            fri_open='0000',
            fri_close='2359',
            sat_open='0000',
            sat_close='2359',
            sun_open='0000',
            sun_close='2359',
        ),
        Business(
            owner_id=3,
            category_id=6,
            address='5200 Glover Rd NW',
            city='Washington',
            state='DC',
            zip_code='20015',
            name='Rock Creek Park',
            description='Vast urban park offering numerous trails and recreational opportunities, welcoming pets to explore the natural beauty alongside their owners.',
            website='https://www.nps.gov/rocr/index.htm',
            set_hours="yes",
            mon_open='0600',
            mon_close='2000',
            tue_open='0600',
            tue_close='2000',
            wed_open='0600',
            wed_close='2000',
            thu_open='0600',
            thu_close='2000',
            fri_open='0600',
            fri_close='2000',
            sat_open='0600',
            sat_close='2000',
            sun_open='0600',
            sun_close='2000',
        ),
        Business(
            owner_id=27,
            category_id=7,
            address='71 Oglethorpe St NW',
            city='Washington',
            state='DC',
            zip_code='20011',
            name='Humane Rescue Alliance',
            description='Animal shelter and adoption center dedicated to rescuing and rehoming pets in the D.C. area, with various programs to support pet adoption.',
            website='https://www.humanerescuealliance.org',
            phone='2027235730',
            set_hours="yes",
            mon_open='1200',
            mon_close='2000',
            tue_open='1200',
            tue_close='2000',
            wed_open='1200',
            wed_close='2000',
            thu_open='1200',
            thu_close='2000',
            fri_open='1200',
            fri_close='2000',
            sat_open='1200',
            sat_close='1800',
            sun_open='1200',
            sun_close='1800',
        ),
        Business(
            owner_id=38,
            category_id=8,
            city='Washington',
            state='DC',
            zip_code='20001',
            name='Bright Eyes Photos by Julie Gould',
            description='Capture the unique spirit of your dog or cat with photos that show emotion and action! Professional pet photographer specializing in outdoor settings for sessions in the Washington-VA-MD metro area',
            website='https://www.petphotofun.com',
            email='Julie@BrightEyesPhotosDC.com',
            set_hours="no",
        ),
        Business(
            owner_id=47,
            category_id=1,
            address='3030 Holiday Dr',
            city='Fort Lauderdale',
            state='FL',
            zip_code='33316',
            name='Ocean Bar',
            description='A refined seafood spot with a chic bar offering ocean views. Pets are welcome at the outdoor seating area.',
            website='https://www.marriott.com/hotels/hotel-information/restaurant/fllsb-fort-lauderdale-marriott-harbor-beach-resort-and-spa/',
            phone='9547653041',
            price='$$$$',
            set_hours="yes",
            mon_open='1800',
            mon_close='2200',
            tue_open='1800',
            tue_close='2200',
            wed_open='1800',
            wed_close='2200',
            thu_open='1800',
            thu_close='2200',
            fri_open='1800',
            fri_close='2200',
            sat_open='1800',
            sat_close='2200',
            sun_open='1800',
            sun_close='2200',
        ),
        Business(
            owner_id=35,
            category_id=3,
            address='10401 Orange Dr,',
            city='Davie',
            state='FL',
            zip_code='33328',
            name='Pet Paradise Fort Lauderdale',
            description='Offering boarding, day camp, grooming, and veterinary services for pets.',
            website='https://www.petparadise.com/fort-lauderdale',
            email='info@petparadise.com',
            phone='9548881866',
            price='$',
            set_hours="yes",
            mon_open='0700',
            mon_close='1900',
            tue_open='0700',
            tue_close='1900',
            wed_open='0700',
            wed_close='1900',
            thu_open='0700',
            thu_close='1900',
            fri_open='0700',
            fri_close='1900',
            sat_open='0800',
            sat_close='1700',
            sun_open='0800',
            sun_close='1700',
        ),
        Business(
            owner_id=3,
            category_id=4,
            address='801 E Sunrise Blvd',
            city='Fort Lauderdale',
            state='FL',
            zip_code='33334',
            name='Pet Supermarket',
            description='Large chain retailer offering a variety of pet supplies, food, and services including grooming.',
            website='https://www.petsupermarket.com/',
            phone='9547636095',
            price='$$',
            set_hours="yes",
            mon_open='0900',
            mon_close='2100',
            tue_open='0900',
            tue_close='2100',
            wed_open='0900',
            wed_close='2100',
            thu_open='0900',
            thu_close='2100',
            fri_open='0900',
            fri_close='2100',
            sat_open='0900',
            sat_close='2100',
            sun_open='1000',
            sun_close='1900',
        ),
        Business(
            owner_id=21,
            category_id=5,
            address='620 E Las Olas Blvd',
            city='Fort Lauderdale',
            state='FL',
            zip_code='33301',
            name='Riverside Hotel Fort Lauderdale',
            description='Elegant hotel offering dog-friendly accommodations and amenities, including pet beds and bowls.',
            website='https://www.riversidehotel.com/',
            phone='9544670671',
            price='$$$',
            set_hours="yes",
            mon_open='0000',
            mon_close='2359',
            tue_open='0000',
            tue_close='2359',
            wed_open='0000',
            wed_close='2359',
            thu_open='0000',
            thu_close='2359',
            fri_open='0000',
            fri_close='2359',
            sat_open='0000',
            sat_close='2359',
            sun_open='0000',
            sun_close='2359',
        ),
        Business(
            owner_id=42,
            category_id=6,
            address='3109 E Sunrise Blvd',
            city='Fort Lauderdale',
            state='FL',
            zip_code='33304',
            name='Hugh Taylor Birch State Park',
            description='Pet-friendly park offering trails, picnic areas, and beach access.',
            website='https://www.floridastateparks.org/parks-and-trails/hugh-taylor-birch-state-park',
            phone='9545644521',
        ),
        Business(
            owner_id=9,
            category_id=7,
            address='1137 NE 9th Ave',
            city=' Fort Lauderdale',
            state='FL',
            zip_code='33304',
            name='Abandoned Pet Rescue',
            description='A no-kill animal shelter dedicated to rescuing and rehabilitating pets in need.',
            website='https://www.abandonedpetrescue.org/',
            email='info@abandonedpetrescue.org',
            phone='9547289010',
        ),
        Business(
            owner_id=18,
            category_id=8,
            address='2618 NW 4th St',
            city='Fort Lauderdale',
            state='FL',
            zip_code='33311',
            name='Peaceful Paws Memorial Services',
            description='Providing pet cremation services with care and respect for your beloved pets.',
            website='https://www.peacefulpawsmemorial.com',
            phone='7866737297',
        ),
        Business(
            owner_id=26,
            category_id=2,
            address='1630 E Oakland Park Blvd',
            city='Oakland Park',
            state='FL',
            zip_code='33301',
            name='Animal Hospital of Ft Lauderdale',
            description='Full-service veterinary clinic offering medical, dental, and surgical care for pets.',
            website='https://ahofl.com/',
            phone='9545618777',
            set_hours="yes",
            mon_open='0730',
            mon_close='1800',
            tue_open='0730',
            tue_close='1800',
            wed_open='0730',
            wed_close='1800',
            thu_open='0730',
            thu_close='1800',
            fri_open='0730',
            fri_close='1800',
            sat_open='0800',
            sat_close='1200',
        ),
        Business(
            owner_id=33,
            category_id=1,
            address='433 Chestnut St',
            city='Philadelphia',
            state='PA',
            zip_code='19106',
            name='Red Owl Tavern',
            description='Philadelphia\'s American tavern restaurant & bar Red Owl Tavern features American food, hand crafted cocktails & a rooftop bar overlooking Independence Hall.',
            website='https://redowltavern.com/',
            phone='2158232267',
            price='$',
            set_hours='yes',
            mon_open='1200',
            mon_close='0200',
            tue_open='1200',
            tue_close='0200',
            wed_open='1200',
            wed_close='0200',
            thu_open='1200',
            thu_close='0200',
            fri_open='1200',
            fri_close='0200',
            sat_open='1000',
            sat_close='0200',
            sun_open='1000',
            sun_close='0200',
        ),
        Business(
            owner_id=15,
            category_id=2,
            address='622 N 2nd St',
            city='Philadelphia',
            state='PA',
            zip_code='19123',
            name='Northern Liberties Veterinary Center',
            description='Offering comprehensive pet care and specialized services for your pets.',
            website='https://www.nolibsvet.com/',
            phone='2159231838',
            set_hours='yes',
            mon_open='0800',
            mon_close='2000',
            tue_open='0800',
            tue_close='2000',
            wed_open='0800',
            wed_close='2000',
            thu_open='0800',
            thu_close='2000',
            fri_open='0800',
            fri_close='2000',
            sat_open='0800',
            sat_close='1300',
        ),
        Business(
            owner_id=8,
            category_id=3,
            address='2440 Frankford Ave',
            city='Philadelphia',
            state='PA',
            zip_code='19125',
            name='BarkPark Philly',
            description='Providing dog walking, boarding, and grooming services in a friendly environment.',
            website='https://www.barkparkphilly.com/',
            phone='2677527530',
            price='$$',
            set_hours='yes',
            mon_open='0900',
            mon_close='1800',
            tue_open='0900',
            tue_close='1800',
            wed_open='0900',
            wed_close='1800',
            thu_open='0900',
            thu_close='1800',
            fri_open='0900',
            fri_close='1800',
        ),
        Business(
            owner_id=22,
            category_id=4,
            address='1946 S Christopher Columbus Blvd',
            city='Philadelphia',
            state='PA',
            zip_code='19148',
            name='Monster Pets',
            description='A comprehensive pet store offering a wide range of pet supplies and products.',
            website='http://monsterpets.com/',
            phone='2153369000',
            price='$',
            set_hours='yes',
            mon_open='0900',
            mon_close='2100',
            tue_open='0900',
            tue_close='2100',
            wed_open='0900',
            wed_close='2100',
            thu_open='0900',
            thu_close='2100',
            fri_open='0900',
            fri_close='2100',
            sat_open='0900',
            sat_close='2100',
            sun_open='1000',
            sun_close='1900',
        ),
        Business(
            owner_id=30,
            category_id=5,
            address='4301 Island Ave',
            city='Philadelphia',
            state='PA',
            zip_code='19153',
            name='Aloft Philadelphia Airport',
            description='A pet-friendly hotel where two dogs up to 40 lbs are welcome for no additional fee.',
            website='https://www.marriott.com/hotels/travel/phlal-aloft-philadelphia-airport/',
            phone='2672981700',
            price='$$$$',
            set_hours='no',
        ),
        Business(
            owner_id=12,
            category_id=6,
            address='300 S 25th St',
            city='Philadelphia',
            state='PA',
            zip_code='19103',
            name='Schuylkill River Park',
            description='A fenced, off-leash dog park located along the Schuylkill River with plenty of room for dogs to play.',
            set_hours='no',
        ),
        Business(
            owner_id=5,
            category_id=7,
            address='100 N 2nd St',
            city='Philadelphia',
            state='PA',
            zip_code='19106',
            name='Philadelphia Animal Welfare Society (PAWS)',
            description='A no-kill shelter dedicated to saving Philadelphia\'s homeless, abandoned, and unwanted animals.',
            website='https://phillypaws.org/',
            phone='2152389901',
            set_hours='yes',
            mon_open='1200',
            mon_close='1900',
            tue_open='1200',
            tue_close='1900',
            wed_open='1200',
            wed_close='1900',
            thu_open='1200',
            thu_close='1900',
            fri_open='1200',
            fri_close='1900',
            sat_open='1100',
            sat_close='1700',
            sun_open='1100',
            sun_close='1700',
        ),
        Business(
            owner_id=37,
            category_id=8,
            city='Philadelphia',
            state='PA',
            zip_code='19123',
            name='Pet Imagery by Lauren Kaplan',
            description='Specializing in professional pet photography to capture memorable moments with your furry friends.',
            website='https://www.petimagery.com/',
            email='mail@laurenphoto.com',
            set_hours='no',
        ),
        Business(
            owner_id=47,
            category_id=1,
            address='6700 Powers Ferry Rd NW',
            city='Sandy Springs',
            state='GA',
            zip_code='30339',
            name='Ray\'s on the River',
            description='Situated along the Chattahoochee River, Ray\'s offers fresh seafood, prime cut steaks, and serene views with outdoor seating for pets.',
            website='https://raysontheriver.com/',
            phone='7709551187',
            price='$$$$',
            set_hours="yes",
            mon_open='1100',
            mon_close='2200',
            tue_open='1100',
            tue_close='2200',
            wed_open='1100',
            wed_close='2200',
            thu_open='1100',
            thu_close='2200',
            fri_open='1100',
            fri_close='2300',
            sat_open='1100',
            sat_close='2300',
            sun_open='1100',
            sun_close='2200',
        ),
        Business(
            owner_id=12,
            category_id=3,
            city='Alpharetta',
            state='GA',
            zip_code='30004',
            name='Homeridge Mobile Vet',
            description='Mobile veterinary services providing professional health and grooming services for pets in Alpharetta and surrounding areas.',
            website='https://www.homeridgemobilevet.com',
            phone='7707789494',
            set_hours="yes",
            mon_open='1000',
            mon_close='1800',
            tue_open='1000',
            tue_close='1800',
            wed_open='1000',
            wed_close='1800',
            thu_open='1000',
            thu_close='1800',
            fri_open='1000',
            fri_close='1800',
            sat_open='1000',
            sat_close='1800',
        ),
        Business(
            owner_id=3,
            category_id=1,
            address='220 Sandy Springs Cir',
            city='Atlanta',
            state='GA',
            zip_code='30328',
            name='Brooklyn Cafe',
            description='Contemporary neighborhood cuisine with outdoor seating where pets are welcome.',
            website='https://www.brooklyncafe.com',
            phone='4048438377',
            price='$',
            set_hours="yes",
            mon_open='1100',
            mon_close='2100',
            tue_open='1100',
            tue_close='2100',
            wed_open='1100',
            wed_close='2100',
            thu_open='1100',
            thu_close='2100',
            fri_open='1100',
            fri_close='2200',
            sat_open='1100',
            sat_close='2200',
            sun_open='1100',
            sun_close='2100',
        ),
        Business(
            owner_id=45,
            category_id=6,
            address='1978 Island Ford Pkwy',
            city='Sandy Springs',
            state='GA',
            zip_code='30350',
            name='Chattahoochee River National Recreation Area',
            description='National park offering scenic trails, fishing, and picnicking areas, with many trails and areas where pets are welcome.',
            website='https://www.nps.gov/chat/index.htm',
            set_hours="yes",
            mon_open='0800',
            mon_close='2000',
            tue_open='0800',
            tue_close='2000',
            wed_open='0800',
            wed_close='2000',
            thu_open='0800',
            thu_close='2000',
            fri_open='0800',
            fri_close='2000',
            sat_open='0800',
            sat_close='2000',
            sun_open='0800',
            sun_close='2000',
        ),
        Business(
            owner_id=10,
            category_id=3,
            address='175 Roswell St,',
            city='Alpharetta',
            state='GA',
            zip_code='30009',
            name='Waggy World Paw Park',
            description='Off-leash dog park with separate areas for small and large dogs, water fountains, and seating for pet owners.',
            website='https://www.alpharetta.ga.us',
            set_hours="yes",
            mon_open='0700',
            mon_close='2100',
            tue_open='0700',
            tue_close='2100',
            wed_open='0700',
            wed_close='2100',
            thu_open='0700',
            thu_close='2100',
            fri_open='0700',
            fri_close='2100',
            sat_open='0700',
            sat_close='2100',
            sun_open='0700',
            sun_close='2100',
        ),
        Business(
            owner_id=18,
            category_id=4,
            address='625 W Crossville Rd Ste 134',
            city='Roswell',
            state='GA',
            zip_code='30075',
            name='PetSmart Roswell',
            description='Pet store offering a wide range of pet supplies, grooming services, and a pet adoption center.',
            website='https://www.petsmart.com',
            phone='6783528138',
            price='$$',
            set_hours="yes",
            mon_open='0900',
            mon_close='2100',
            tue_open='0900',
            tue_close='2100',
            wed_open='0900',
            wed_close='2100',
            thu_open='0900',
            thu_close='2100',
            fri_open='0900',
            fri_close='2100',
            sat_open='0900',
            sat_close='2100',
            sun_open='1000',
            sun_close='1900',
        ),
        Business(
            owner_id=5,
            category_id=7,
            address='PO Box 821',
            city='Roswell',
            state='GA',
            zip_code='30009',
            name='Angels Among Us Pet Rescue',
            description='Non-profit organization dedicated to rescuing dogs and cats from high-kill shelters and placing them in loving homes.',
            website='https://www.angelsrescue.org',
            phone='8774045874',
            set_hours="yes",
            mon_open='1000',
            mon_close='1700',
            tue_open='1000',
            tue_close='1700',
            wed_open='1000',
            wed_close='1700',
            thu_open='1000',
            thu_close='1700',
            fri_open='1000',
            fri_close='1700',
            sat_open='1000',
            sat_close='1700',
        ),
        Business(
            owner_id=23,
            category_id=2,
            address='562 N Main St',
            city='Alpharetta',
            state='GA',
            zip_code='30009',
            name='North Main Animal Hospital',
            description='Full-service veterinary hospital providing comprehensive healthcare services for pets including surgery, dentistry, and wellness exams.',
            website='https://www.alpharetta-vet.com/',
            phone='7705188911',
            set_hours="yes",
            mon_open='0800',
            mon_close='1800',
            tue_open='0800',
            tue_close='1800',
            wed_open='0800',
            wed_close='1800',
            thu_open='0800',
            thu_close='1800',
            fri_open='0800',
            fri_close='1800',
            sat_open='0900',
            sat_close='1300',
        ),
        Business(
            owner_id=5,
            category_id=1,
            address='5202 N Central Ave',
            city='Phoenix',
            state='AZ',
            zip_code='85012',
            name='Joyride Taco House',
            description='Joyride Taco House is a vibrant and laid-back restaurant that will satisfy your deepest taco cravings and thirst for delicious margaritas. Joyride\'s lively and casual atmosphere makes it the perfect place to gather with friends and family.',
            website='https://www.joyridetacohouse.com/',
            phone='6022748226',
            email='joyridecentral@upwardprojects.com',
            price='$',
            set_hours="yes",
            mon_open='1100',
            mon_close='2300',
            tue_open='1100',
            tue_close='2300',
            wed_open='1100',
            wed_close='2300',
            thu_open='1100',
            thu_close='2300',
            fri_open='1100',
            fri_close='2300',
            sat_open='1000',
            sat_close='2300',
            sun_open='1000',
            sun_close='2300',
        ),
        Business(
            owner_id=38,
            category_id=2,
            address='1025 E Camelback Rd',
            city='Phoenix',
            state='AZ',
            zip_code='85014',
            name='Camelback Animal Clinic',
            description='Camelback Animal Clinic in Phoenix, AZ offers a variety of veterinary services and prevenative care options to ensure the health of your pet!',
            website='https://www.camelbackanimalcenterphoenix.com/',
            phone='6025954020',
            set_hours="yes",
            mon_open='1000',
            mon_close='1800',
            tue_open='1000',
            tue_close='1800',
            wed_open='1000',
            wed_close='1800',
            thu_open='1000',
            thu_close='1800',
            fri_open='1000',
            fri_close='1800',
        ),
        Business(
            owner_id=15,
            category_id=3,
            address='12801 N Paradise Village Pkwy W',
            city='Phoenix',
            state='AZ',
            zip_code='85032',
            name='Doggie District Pet Resort & Training Center',
            description='Premier dog boarding, daycare, and training facility, offering top-notch care for pets in the Phoenix area.',
            website='https://www.doggiedistrict.com/',
            phone='8432776109',
            price='$$$',
            set_hours="yes",
            mon_open='0700',
            mon_close='1900',
            tue_open='0700',
            tue_close='1900',
            wed_open='0700',
            wed_close='1900',
            thu_open='0700',
            thu_close='1900',
            fri_open='0700',
            fri_close='1900',
            sat_open='0800',
            sat_close='1700',
            sun_open='0800',
            sun_close='1700',
        ),
        Business(
            owner_id=10,
            category_id=4,
            address='4380 N Miller Rd',
            city='Scottsdale',
            state='AZ',
            zip_code='85251',
            name='PetSmart',
            description='Leading pet supply store offering a wide range of products and services including grooming and training.',
            website='https://www.petsmart.com/',
            phone='4804294519',
            price='$$',
            set_hours="yes",
            mon_open='0900',
            mon_close='2100',
            tue_open='0900',
            tue_close='2100',
            wed_open='0900',
            wed_close='2100',
            thu_open='0900',
            thu_close='2100',
            fri_open='0900',
            fri_close='2100',
            sat_open='0900',
            sat_close='2100',
            sun_open='1000',
            sun_close='1900',
        ),
        Business(
            owner_id=22,
            category_id=5,
            address='1600 S Country Club Dr',
            city='Mesa',
            state='AZ',
            zip_code='85210',
            name='Holiday Inn Hotel & Suites Phoenix-Mesa/Chandler',
            description='Pet-friendly hotel providing comfortable accommodations and amenities for travelers with pets.',
            website='https://www.ihg.com/holidayinn/hotels/us/en/mesa/phxme/hoteldetail',
            phone='4809647000',
            price='$$',
            set_hours="no",
        ),
        Business(
            owner_id=44,
            category_id=6,
            address='625 N Galvin Pkwy',
            city='Phoenix',
            state='AZ',
            zip_code='85008',
            name='Papago Park',
            description='A large park offering hiking trails, fishing lagoons, and picnic areas, where pets are welcome on-leash.',
            website='https://www.phoenix.gov/parks/trails/locations/papago-park',
            set_hours="yes",
            mon_open='0500',
            mon_close='2300',
            tue_open='0500',
            tue_close='2300',
            wed_open='0500',
            wed_close='2300',
            thu_open='0500',
            thu_close='2300',
            fri_open='0500',
            fri_close='2300',
            sat_open='0500',
            sat_close='2300',
            sun_open='0500',
            sun_close='2300',
        ),
        Business(
            owner_id=37,
            category_id=7,
            address='25 N 40th St',
            city='Pheonix',
            state='AZ',
            zip_code='85034',
            name='Arizona Animal Welfare League & SPCA',
            description='Arizona\'s oldest and largest no-kill shelter, dedicated to rescuing and rehoming pets in need.',
            website='https://aawl.org/',
            phone='6022736852',
            set_hours="yes",
            mon_open='1100',
            mon_close='1800',
            tue_open='1100',
            tue_close='1800',
            wed_open='1100',
            wed_close='1800',
            thu_open='1100',
            thu_close='1800',
            fri_open='1100',
            fri_close='1800',
            sat_open='1100',
            sat_close='1800',
        ),
        Business(
            owner_id=28,
            category_id=8,
            city='Scottsdale',
            state='AZ',
            zip_code='85255',
            name='Flash and Hound Pet Photography',
            description='We\'re passionate about capturing the essence of your story as a pet owner - be it an adoption story, rescue or foster or how you went about bringing home a puppy from a responsible breeder.',
            website='https://www.flashandhound.com/',
            phone='6029038903',
            price='$$',
            set_hours="yes",
            mon_open='0900',
            mon_close='2000',
            tue_open='0900',
            tue_close='2000',
            wed_open='0900',
            wed_close='2000',
            thu_open='0900',
            thu_close='2000',
            fri_open='0900',
            fri_close='2000',
            sat_open='0900',
            sat_close='2000',
            sun_open='1000',
            sun_close='1800',
        )
    ]

    
    db.session.add_all(businesses_3)
    db.session.commit()



# Uses a raw SQL query to TRUNCATE or DELETE the users table. SQLAlchemy doesn't
# have a built in function to do this. With postgres in production TRUNCATE
# removes all the data from the table, and RESET IDENTITY resets the auto
# incrementing primary key, CASCADE deletes any dependent entities.  With
# sqlite3 in development you need to instead use DELETE to remove all data and
# it will reset the primary keys for you as well.
def undo_businesses_2B():
    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.businesses RESTART IDENTITY CASCADE;")
    else:
        db.session.execute(text("DELETE FROM businesses"))

    db.session.commit()
