from app.models import db, Business, environment, SCHEMA
from sqlalchemy.sql import text

def seed_businesses_2A():
    businesses_2A = [
      Business(
         #93
        owner_id=50,
        category_id=1,
        address='6080 Falls Rd',
        city='Baltimore',
        state='MD',
        zip_code='21212',
        name='The Corner Pantry',
        description='The Corner Pantry is a casual eatery offering British-American cuisine. The outdoor seating area is dog-friendly, so you can enjoy a meal with your furry friend.',
        website='https://www.corner-pantry.com/',
        email='info@corner-pantry.com',
        phone='6673082331',
        price='$',
        set_hours='yes',
        mon_open='0700',
        mon_close='1500',
        tue_open='0700',
        tue_close='1500',
        wed_open='0700',
        wed_close='1500',
        thu_open='0700',
        thu_close='1500',
        fri_open='0700',
        fri_close='1500',
        sat_open='0800',
        sat_close='1500',
      ),
      Business(
         #94
        owner_id=49,
        category_id=2,
        address='716 York Rd',
        city='Towson',
        state='MD',
        zip_code='21204',
        name='Towson Veterinary Hospital',
        description='Towson Veterinary Hospital offers comprehensive veterinary care including exams, surgery, dental treatment, and ultrasound diagnostics. They also provide boarding services for pets.',
        website='https://www.towsonveterinary.com',
        email='reception@towson.vet',
        phone='4108258880',
        price='$$',
        set_hours='yes',
        mon_open='0900',
        mon_close='1800',
        tue_open='0900',
        tue_close='1800',
        wed_open='0900',
        wed_close='1800',
        thu_open='0900',
        thu_close='1800',
        fri_open='0900',
        fri_close='1800',
        sat_open='0900',
        sat_close='1800',
      ),
      Business(
         #95
        owner_id=50,
        category_id=3,
        address='240 Town Square Dr',
        city='Lusby',
        state='MD',
        zip_code='20657',
        name='Bark & Bath Pet Salon',
        description='Bark & Bath Pet Salon is a friendly, high end pet grooming facility located in Lusby, Maryland. Our salon accommodates cats and dogs of all breeds! We take pride in maintaining a clean and stress free salon environment.',
        website='http://www.barkandbathpetsalon.com/',
        email='barkandbathpetsalon@yahoo.com',
        phone='4102312527',
        set_hours='yes',
        mon_open='0800',
        mon_close='1600',
        tue_open='0800',
        tue_close='1600',
        wed_open='0800',
        wed_close='1600',
        thu_open='0800',
        thu_close='1600',
        fri_open='0800',
        fri_close='1600',
        sat_open='0800',
        sat_close='1200',
      ),
      Business(
         #96
        owner_id=5,
        category_id=49,
        address='3531 Chestnut Avenue',
        city='Baltimore',
        state='MD',
        zip_code='21211',
        name='Howl',
        description='Howl offers a variety of pet products including food, toys, and accessories. They also offer pet grooming services.',
        website='https://www.howlinhampden.com/',
        email='howlinhampden@gmail.com',
        phone='4102352469',
        price='$$',
        set_hours='yes',
        mon_open='1100',
        mon_close='1900',
        tue_open='1100',
        tue_close='1900',
        wed_open='1100',
        wed_close='1900',
        thu_open='1100',
        thu_close='1900',
        fri_open='1100',
        fri_close='1900',
        sat_open='1100',
        sat_close='1700',
        sun_open='1100',
        sun_close='1700',
      ),
      Business(
         #97
        owner_id=48,
        category_id=5,
        address='1734 W Nursery Rd',
        city='Linthicum Heights',
        state='MD',
        zip_code='21090',
        name='La Quinta Inn & Suites by Wyndham Baltimore BWI Airport',
        description='This pet-friendly hotel near BWI Airport offers comfortable accommodations for travelers and their pets, with easy access to Baltimore attractions.',
        website='https://www.wyndhamhotels.com/laquinta/linthicum-maryland/la-quinta-baltimore-bwi-airport/overview?CID=LC:6ysy27krtpcrqev:52918&iata=00093796',
        phone='4108592333',
        price='$$$',
        set_hours='no',
      ),
      Business(
         #98
        owner_id=47,
        category_id=6,
        address='1000 Lakeside Dr',
        city='Baltimore',
        state='MD',
        zip_code='21210',
        name='Lake Roland Park',
        description='Lake Roland Park offers scenic trails and open spaces that are perfect for outdoor activities with your dog. The park includes a designated dog park and swim area known as Paw Point Dog Park.',
        website='https://www.lakeroland.org',
        email='lakerol-rp@baltimorecountymd.gov',
        phone='4108874156',
        set_hours='no',
        mon_open='0600',
        mon_close='2200',
        tue_open='0600',
        tue_close='2200',
        wed_open='0600',
        wed_close='2200',
        thu_open='0600',
        thu_close='2200',
        fri_open='0600',
        fri_close='2200',
        sat_open='0600',
        sat_close='2200',
        sun_open='0600',
        sun_close='2200',
      ),
      Business(
         #99
        owner_id=48,
        category_id=7,
        address='3300 Falls Rd',
        city='Baltimore',
        state='MD',
        zip_code='21211',
        name='Maryland SPCA',
        description='Maryland SPCA is dedicated to improving the lives of pets and people by providing adoption services, veterinary care, and community programs.',
        website='https://www.mdspca.org',
        phone='4102358826',
        price='$',
        set_hours='yes',
        mon_open='1300',
        mon_close='1900',
        tue_open='1300',
        tue_close='1900',
        wed_open='1300',
        wed_close='1900',
        thu_open='1300',
        thu_close='1900',
        fri_open='1300',
        fri_close='1900',
        sat_open='1200',
        sat_close='1700',
      ),
      Business(
         #100
        owner_id=47,
        category_id=8,
        address='3500 Parkdale Ave Fl 2 Ste R',
        city='Baltimore',
        state='MD',
        zip_code='21211',
        name='Puptrait',
        description='Puptrait is an award winning dog-friendly photography studio located in the heart of Baltimore City, Maryland. We are world renowned for our anthropomorphic pet portraits and original handmade costume designs.',
        website='https://puptrait.com/',
        email='help@puptrait.com',
        phone='4436040711',
        price='$$$',
        set_hours='no',
        mon_open='1200',
        mon_close='2200',
        tue_open='1200',
        tue_close='2200',
        wed_open='1200',
        wed_close='2200',
        thu_open='1200',
        thu_close='2200',
        fri_open='1200',
        fri_close='2200',
        sat_open='1200',
        sat_close='2200',
        sun_open='1200',
        sun_close='2200',
      ),
      Business(
         #101
        owner_id=46,
        category_id=1,
        address='3307 N Davidson St',
        city='Charlotte',
        state='NC',
        zip_code='28205',
        name='Dog Bar',
        description='Dogs are allowed off-leash at this hangout with beer, wine & cocktails, plus a patio area & TVs.',
        phone='7043703595',
        price='$',
        set_hours="yes",
        tue_open='1700',
        tue_close='2200',
        wed_open='1700',
        wed_close='2200',
        thu_open='1700',
        thu_close='2200',
        fri_open='1700',
        fri_close='2200',
        sat_open='1200',
        sat_close='2200',
        sun_open='1200',
        sun_close='2200',
      ),
      Business(
         #102
        owner_id=45,
        category_id=2,
        address='9729 S Tryon St',
        city='Charlotte',
        state='NC',
        zip_code='28273',
        name='Steele Creek Animal Hospital',
        description='At Steele Creek Animal Hospital in Charlotte, NC, we offer a wide-range of services to help your animal in any way we can. Call us today!',
        website='https://www.keepingpetshealthy.com/',
        phone='7045884400',
        set_hours="yes",
        mon_open='0700',
        mon_close='1800',
        tue_open='0700',
        tue_close='1800',
        wed_open='0700',
        wed_close='1800',
        thu_open='0700',
        thu_close='1800',
        fri_open='0700',
        fri_close='1800',
        sat_open='0700',
        sat_close='1200',
      ),
      Business(
         #103
        owner_id=45,
        category_id=3,
        address='5011 Weddington Rd NW Suite 60',
        city='Concord',
        state='NC',
        zip_code='28027',
        name='Woof Gang Bakery & Grooming',
        description='Woof Gang Bakery & Grooming is the leader in professional pet grooming, and the leading specialty retailer of pet food and supplies in the country. Our pet grooming services, butt scratches, and nose boops are the best in the industry!',
        website='https://woofgangbakery.com/',
        phone='9802558116',
        email='concordnc@woofgangbakery.com',
        set_hours="yes",
        mon_open='1000',
        mon_close='1800',
        tue_open='1000',
        tue_close='1800',
        wed_open='1000',
        wed_close='1800',
        thu_open='1000',
        thu_close='1800',
        fri_open='1000',
        fri_close='1800',
        sat_open='1000',
        sat_close='1800',
        sun_open='1200',
        sun_close='1800',
      ),
      Business(
         #104
        owner_id=46,
        category_id=4,
        address='4110 Charlotte Hwy',
        city='Lake Wylie',
        state='SC',
        zip_code='28209',
        name='Pet Wants Lake Wylie',
        description='Lake Wylie, SC\'s Pet Wants is a specialty shop that focuses on pet nutrition and educating pet parents on the importance of healthy food for your dog. Fresh, simple ingredients make up their food that\'s made fresh every 45 days.',
        website='https://www.petwantslakewylie.com/',
        phone='8036101228',
        email='kbyrd@petwants.com',
        set_hours="yes",
        tue_open='1000',
        tue_close='1800',
        wed_open='1000',
        wed_close='1800',
        thu_open='1000',
        thu_close='1800',
        fri_open='1000',
        fri_close='1800',
        sat_open='1000',
        sat_close='1800',
        sun_open='1200',
        sun_close='1700',
        ),
      Business(
         #105
        owner_id=44,
        category_id=5,
        address='222 East 3rd St',
        city='Charlotte',
        state='NC',
        zip_code='28202',
        name='Aloft Charlotte City Center',
        description='Aloft Charlotte City Center welcomes both dogs and cats, and well-behaved pets may be left in the room unattended. Treats, beds, and food and water bowls are available at the front desk. ',
        website='https://www.marriott.com/en-us/hotels/cltul-aloft-charlotte-city-center/overview/?scid=f2ae0541-1279-4f24-b197-a979c79310b0',
        phone='7043331999',
        price='$$$',
        set_hours="no",
      ),
      Business(
         #106
        owner_id=43,
        category_id=6,
        address='15222 York Rd',
        city='Charlotte',
        state='NC',
        zip_code='28278',
        name='McDowell Nature Preserve',
        description='McDowell Nature Preserve offers scenic trails, fishing, and camping. Dogs are welcome on the trails and in the camping areas.',
        website='https://parkandrec.mecknc.gov/Places-to-Visit/Nature/mcdowell-nature-center-and-preserve',
        email='mdnp@MeckNC.gov',
        phone='9803141128',
        set_hours="yes",
        mon_open='0900',
        mon_close='1700',
        tue_open='0900',
        tue_close='1700',
        wed_open='0900',
        wed_close='1700',
        thu_open='0900',
        thu_close='1700',
        fri_open='0900',
        fri_close='1700',
        sat_open='0900',
        sat_close='1700',
        sun_open='1300',
        sun_close='1700',
      ),
      Business(
         #107
        owner_id=43,
        category_id=7,
        address='1348 Parker Dr',
        city='Charlotte',
        state='NC',
        zip_code='28208',
        name='The Humane Society of Charlotte',
        description='The Humane Society of Charlotte offers pet adoption services and community education programs. They aim to improve the lives of pets and people through compassion and care.',
        website='https://www.humanesocietyofcharlotte.org',
        phone='7043770534',
        set_hours="yes",
        mon_open='1100',
        mon_close='1700',
        tue_open='1100',
        tue_close='1700',
        wed_open='1100',
        wed_close='1700',
        thu_open='1100',
        thu_close='1700',
        fri_open='1100',
        fri_close='1900',
        sat_open='1100',
        sat_close='1800',
        sun_open='1100',
        sun_close='1700',
      ),
      Business(
         #108
        owner_id=44,
        category_id=8,
        address='8431 Old Statesville Rd',
        city='Charlotte',
        state='NC',
        zip_code='28203',
        name='DoodyCalls',
        description='DoodyCalls provides dog pooper scooper service for your yard, patio/deck deodorizing, as well as pet dog waste station set up and maintenance for communities.',
        website='https://www.doodycalls.com/charlotte/',
        phone='7046100545',
        email='charlottedoodycalls@live.com',
        set_hours="yes",
        mon_open='0830',
        mon_close='2100',
        tue_open='0830',
        tue_close='2100',
        wed_open='0830',
        wed_close='2100',
        thu_open='0830',
        thu_close='2100',
        fri_open='0830',
        fri_close='2100',
        sat_open='0900',
        sat_close='1700',
        sun_open='1230',
        sun_close='1530',
      ),
      Business(
         #109
        owner_id=42,
        category_id=1,
        address=' 6400 Time Square Ave',
        city='Orlando',
        state='FL',
        zip_code='32835',
        name='Teak Neighborhood Grill',
        description='Casual eatery with a pet-friendly patio serving microbrews & handcrafted burgers, this pub with a patio hosts trivia nights & live music.',
        website='https://teakorlando.com/',
        email='teakorlando@live.com',
        phone='4073135111',
        price='$$',
        set_hours="yes",
        mon_open='1130',
        mon_close='2300',
        tue_open='1130',
        tue_close='2300',
        wed_open='1130',
        wed_close='2300',
        thu_open='1130',
        thu_close='2300',
        fri_open='1100',
        fri_close='2400',
        sat_open='1100',
        sat_close='2400',
        sun_open='1100',
        sun_close='2300',
      ),
      Business(
         #110
        owner_id=41,
        category_id=2,
        address='1201 W Michigan St',
        city='Orlando',
        state='FL',
        zip_code='32805',
        name='Michigan Street Animal Hospital',
        description='Full-service veterinary hospital offering comprehensive medical, surgical, and dental care.',
        website='https://www.michiganstreetvet.com/',
        email= 'westmichiganstvet@gmail.com',
        phone='3177575077',
        set_hours="yes",
        mon_open='0800',
        mon_close='1700',
        tue_open='0800',
        tue_close='1700',
        wed_open='0800',
        wed_close='1700',
        thu_open='0800',
        thu_close='1700',
        fri_open='0800',
        fri_close='1700',
        sat_open='0800',
        sat_close='1200',
      ),
      Business(
         #111
        owner_id=41,
        category_id=3,
        address='3815 Lake Center Dr',
        city='MT Dora',
        state='FL',
        zip_code='32757',
        name='The Green K9',
        description='Professional dog grooming and boarding services with a focus on natural pet care.',
        website='https://thegreenk9.com/',
        email='info@thegreenk9.com',
        phone='3527296172',
        set_hours="yes",
        mon_open='0730',
        mon_close='1800',
        tue_open='0730',
        tue_close='1800',
        wed_open='0730',
        wed_close='1800',
        thu_open='0730',
        thu_close='1800',
        fri_open='0730',
        fri_close='1800',
        sat_open='1000',
        sat_close='1600',
        sun_open='1000',
        sun_close='1600',
      ),
      Business(
         #112
        owner_id=42,
        category_id=4,
        address='460 N Ronald Reagan Blvd',
        city='Longwood',
        state='FL',
        zip_code='32750',
        name='Doggo Lovers',
        description='Doggo Lovers in Longwood, FL, is a pet supply store and dog boutique. They carry dog food, treats, pet care items, bowls, leashes, jewelry and accessories',
        website='https://doggolovers.com/',
        email='doggoloversfl@gmail.com',
        phone='6892479993',
        set_hours="yes",
        mon_open='1000',
        mon_close='1900',
        tue_open='1000',
        tue_close='1900',
        wed_open='1000',
        wed_close='1900',
        thu_open='1000',
        thu_close='1900',
        fri_open='1000',
        fri_close='1900',
        sat_open='1000',
        sat_close='1700',
      ),
      Business(
         #113
        owner_id=40,
        category_id=5,
        address='8480 International Dr',
        city='Orlando',
        state='FL',
        zip_code='32819',
        name='Sonesta ES Suites Orlando - International Drive',
        description='Sonesta ES Suites Orlando - International Drive welcomes two dogs of any size for an additional fee of $75 (for stays of 1 to 7 nights), and $25 per week thereafter. Cats are not allowed.',
        website='https://www.sonesta.com/sonesta-es-suites/fl/orlando/sonesta-es-suites-orlando-international-drive',
        phone='4073522400',
        price='$$',
        set_hours="no",
      ),
      Business(
         #114
        owner_id=39,
        category_id=6,
        address='512 East Washington St',
        city='Orlando',
        state='FL',
        zip_code='32801',
        name='Lake Eola Park',
        description='Beautiful park in downtown Orlando, offering walking trails, swan boat rentals, and a large lake. Dogs are welcome on leashes.',
        website='https://www.cityoforlando.net/parks/lake-eola-park/',
        phone='4072464484',
        set_hours="yes",
        mon_open='0600',
        mon_close='2359',
        tue_open='0600',
        tue_close='2359',
        wed_open='0600',
        wed_close='2359',
        thu_open='0600',
        thu_close='2359',
        fri_open='0600',
        fri_close='2359',
        sat_open='0600',
        sat_close='2359',
        sun_open='0600',
        sun_close='2359',
      ),
      Business(
         #115
        owner_id=39,
        category_id=7,
        address='2769 Conroy Rd',
        city='Orlando',
        state='FL',
        zip_code='32839',
        name='Orange County Animal Services',
        description='Animal shelter providing pet adoption services, community education, and veterinary care.',
        website='https://www.ocnetpets.com/',
        phone='4078363111',
        set_hours="yes",
        mon_open='1000',
        mon_close='1800',
        tue_open='1000',
        tue_close='1800',
        wed_open='1400',
        wed_close='1800',
        thu_open='1000',
        thu_close='1800',
        fri_open='1000',
        fri_close='1800',
        sat_open='1000',
        sat_close='1800',
        sun_open='1000',
        sun_close='1800',
      ),
      Business(
         #116
        owner_id=40,
        category_id=8,
        address='7284 Narcoossee Rd',
        city='Orlando',
        state='FL',
        zip_code='32822',
        name='Orlando Pet Crematory',
        description='Specializing in helping families create unforgettable memorials of beautiful moments shared with pets.',
        website='https://orlandopetcrematory.com/',
        phone='4073817474',
        set_hours="yes",
        mon_open='0900',
        mon_close='1530',
        tue_open='0900',
        tue_close='1530',
        wed_open='0900',
        wed_close='1530',
        thu_open='0900',
        thu_close='1530',
        fri_open='0900',
        fri_close='1530',
      ),
      Business(
         #117
        owner_id=38,
        category_id=1,
        address='245 E Commerce St Ste 100',
        city='San Antonio',
        state='TX',
        zip_code='78205',
        name='Rita\'s on the River',
        description='Mexican restaurant on the Riverwalk where you can dine with your pup. While you sip on a margarita, your dog can have something from the dog menu that includes dog-friendly ice cream, white rice with zucchini and carrots, and a free dog water slushy.',
        website='https://ritasontheriver.com/',
        phone='2102277482',
        price='$$',
        set_hours="yes",
        mon_open='1100',
        mon_close='2200',
        tue_open='1100',
        tue_close='2200',
        wed_open='1100',
        wed_close='2200',
        thu_open='1100',
        thu_close='2200',
        fri_open='1100',
        fri_close='2300',
        sat_open='1100',
        sat_close='2300',
      ),
      Business(
         #118
        owner_id=37,
        category_id=2,
        address='6820 Alamo Pkwy STE 118',
        city='San Antonio',
        state='TX',
        zip_code='78253',
        name='Alamo Ranch Animal Hospital',
        description='Full-service veterinary hospital offering comprehensive pet care.',
        website='https://alamoranchvets.com/',
        phone='2105387484',
        set_hours="yes",
        mon_open='0730',
        mon_close='1730',
        tue_open='0730',
        tue_close='1730',
        wed_open='0730',
        wed_close='1730',
        thu_open='0730',
        thu_close='1730',
        fri_open='0730',
        fri_close='1730',
      ),
      Business(
         #119
        owner_id=37,
        category_id=3,
        address='5010 N Loop 1604 W',
        city='San Antonio',
        state='TX',
        zip_code='78249',
        name='Lucy\'s Doggy Daycare and Spa',
        description='Offering dog daycare, boarding, grooming, and spa services.',
        website='https://www.lucysdoggydaycare.com/',
        email='info@lucysdoggydaycare.com',
        phone='2104953647',
        set_hours="yes",
        mon_open='0700',
        mon_close='2000',
        tue_open='0700',
        tue_close='2000',
        wed_open='0700',
        wed_close='2000',
        thu_open='0700',
        thu_close='2000',
        fri_open='0700',
        fri_close='2000',
        sat_open='0800',
        sat_close='1800',
        sun_open='0800',
        sun_close='1600',
      ),
      Business(
         #120
        owner_id=38,
        category_id=4,
        address='5120 Broadway St',
        city='San Antonio',
        state='TX',
        zip_code='78209',
        name='Fifi & Fidos Pet Boutique',
        description='Upscale boutique carrying food & treats for dogs & cats, also offers pet nutrition advice.',
        website='https://fifiandfidos.com/',
        phone='2108222525',
        set_hours="yes",
        mon_open='1000',
        mon_close='1800',
        tue_open='1000',
        tue_close='1800',
        wed_open='1000',
        wed_close='1800',
        thu_open='1000',
        thu_close='1800',
        fri_open='1000',
        fri_close='1800',
        sat_open='1000',
        sat_close='1800',
      ),
      Business(
         #121
        owner_id=36,
        category_id=5,
        address='420 W Market St',
        city='San Antonio',
        state='TX',
        zip_code='78205',
        name='The Westin Riverwalk, San Antonio',
        description='Pet-friendly hotel offering upscale accommodations along the Riverwalk.',
        website='https://www.marriott.com/en-us/hotels/satvw-the-westin-riverwalk-san-antonio/overview/',
        phone='2102246500',
        price='$$$',
        set_hours="no",
      ),
      Business(
         #122
        owner_id=35,
        category_id=6,
        address='13203 Blanco Rd',
        city='San Antonio',
        state='TX',
        zip_code='78216',
        name='Phil Hardberger Park',
        description='A large park with trails, dog parks, and picnic areas.',
        website='https://www.philhardbergerpark.org/',
        phone='2104927472',
        set_hours='no'
      ),
      Business(
         #123
        owner_id=35,
        category_id=7,
        address='4804 Fredericksburg Rd',
        city='San Antonio',
        state='TX',
        zip_code='78229',
        name='San Antonio Humane Society',
        description='Animal shelter offering pet adoption services.',
        website='https://sahumane.org/',
        email='communication@sahumane.org',
        phone='2102267461',
        set_hours="yes",
        mon_open='1200',
        mon_close='1900',
        tue_open='1200',
        tue_close='1900',
        wed_open='1200',
        wed_close='1900',
        thu_open='1200',
        thu_close='1900',
        fri_open='1200',
        fri_close='1900',
        sat_open='1200',
        sat_close='1900',
        sun_open='1200',
        sun_close='1900',
      ),
      Business(
         #124
        owner_id=37,
        category_id=8,
        address='5611 E. Houston St.',
        city='San Antonio',
        state='TX',
        zip_code='78220',
        name='All Paws Great & Small Pet Funeral Home & Crematory',
        description='Providing pet burial and cremation services in a respectful manner.',
        website='https://www.faithfulfriendscrematory.com/',
        phone='2106617297',
        set_hours="yes",
        mon_open='0800',
        mon_close='1700',
        tue_open='0800',
        tue_close='1700',
        wed_open='0800',
        wed_close='1700',
        thu_open='0800',
        thu_close='1700',
        fri_open='0800',
        fri_close='1700',
        sat_open='0800',
        sat_close='1400',
      ),
      Business(
         #125
        owner_id=36,
        category_id=3,
        address=' 7182 Oak Dr.',
        city='San Antonio',
        state='TX',
        zip_code='78256',
        name='Barkaritaville Pet Resort',
        description='Barkaritaville Pet Resort is a full-service, state of the art pet resort in San Antonio, TX, with luxury lodging, doggie daycare, grooming salon and spa, dog training, DIY dog wash, and more!',
        website='https://www.faithfulfriendscrematory.com/',
        email='infosa@barkpr.us',
        phone='2104052275',
        set_hours="yes",
        mon_open='0700',
        mon_close='1800',
        tue_open='0700',
        tue_close='1800',
        wed_open='0700',
        wed_close='1800',
        thu_open='0700',
        thu_close='1800',
        fri_open='0700',
        fri_close='1800',
        sat_open='0800',
        sat_close='1700',
      ),
      Business(
         #126
        owner_id=35,
        category_id=1,
        address='915 SE Hawthorne Blvd',
        city='Portland',
        state='OR',
        zip_code='97214',
        name='Lucky Labrador Brew Pub',
        description='Enjoy pizza, sandwiches, and a variety of local brews at this dog-friendly brewery. The patio is perfect for you and your pup, with plenty of water bowls and a relaxing atmosphere.',
        website='https://www.luckylab.com',
        phone='5032363555',
        price='$$',
        set_hours="yes",
        mon_open='1630',
        mon_close='2230',
        tue_open='1630',
        tue_close='2200',
        wed_open='1630',
        wed_close='2230',
        thu_open='1630',
        thu_close='2230',
        fri_open='1400',
        fri_close='2300',
        sat_open='1200',
        sat_close='2300',
        sun_open='1200',
        sun_close='2100',
      ),
      Business(
         #127
        owner_id=35,
        category_id=1,
        address='1438 NE Alberta St',
        city='Portland',
        state='OR',
        zip_code='97211',
        name='Tin Shed Garden Cafe',
        description='A top dog-friendly spot in Portland, offering breakfast, lunch, and dinner. The outdoor patio welcomes dogs and provides a special dog menu with proceeds benefiting local rescues.',
        website='https://www.tinshedgardencafe.com',
        phone='5032886966',
        price='$$',
        set_hours="yes",
        mon_open='0800',
        mon_close='1400',
        wed_open='0800',
        wed_close='1400',
        thu_open='0800',
        thu_close='1400',
        fri_open='0800',
        fri_close='1400',
        sat_open='0700',
        sat_close='1500',
        sun_open='0700',
        sun_close='1500',
      ),
      Business(
         #128
        owner_id=34,
        category_id=2,
        address='315 NE Killingsworth St',
        city='Portland',
        state='OR',
        zip_code='97211',
        name='Heart and Soul Animal Urgent Care',
        description='Heart and Soul is a local, independent veterinary clinic in NE Portland, OR. We provide experienced veterinary urgent care and wellness services for pets.',
        website='https://pdxheartandsoul.com/',
        phone='5037499400',
        set_hours="yes",
        mon_open='0730',
        mon_close='2000',
        wed_open='0730',
        wed_close='2000',
        thu_open='0730',
        thu_close='2000',
        fri_open='0730',
        fri_close='2000',
        sat_open='0730',
        sat_close='2000',
        sun_open='0730',
        sun_close='2000',
      ),
      Business(
         #129
        owner_id=34,
        category_id=3,
        city='Vancouver',
        state='WA',
        zip_code='98687',
        name='Vancouver Dogs Gone Walking',
        description='Offering professional dog walking, pet sitting, and overnight care in the Vancouver area. They provide personalized services to meet the needs of every pet.',
        website='https://vancouverdgw.wixsite.com/vancouverdgw',
        email='cmoreno@hmccoregon.com',
        phone='3606011127',
      ),
      Business(
         #130
        owner_id=33,
        category_id=4,
        address='3131 N Lombard Street',
        city='Portland',
        state='OR',
        zip_code='97217',
        name='Fang! Pet & Garden Supply',
        description='Fang! offers healthy, affordable pet products for cats, dogs, small animals, and chickens. It also features indoor tropical houseplants, a seasonal outdoor garden center with veggie starts, native and landscaping plants, soil, and gardening tools.',
        website='https://www.fangpetgardensupply.com',
        email='gardencenter@fangpetgardensupply.com',
        phone='5039725822',
        set_hours="yes",
        mon_open='0900',
        mon_close='1900',
        tue_open='0900',
        tue_close='1900',
        wed_open='0900',
        wed_close='1900',
        thu_open='0900',
        thu_close='1900',
        fri_open='0900',
        fri_close='1900',
        sat_open='0900',
        sat_close='1900',
        sun_open='0900',
        sun_close='1900',
      ),
      Business(
         #131
        owner_id=32,
        category_id=5,
        address='813 SW Alder St',
        city='Portland',
        state='OR',
        zip_code='97205',
        name='Woodlark Hotel',
        description='Woodlark is pet friendly! Pets of any size are welcome for no additional fee. Doggy beds, treats, toys, and bowls are provided to furry guests.',
        website='https://woodlarkhotel.com/',
        phone='5035482559',
        set_hours="no",
      ),
      Business(
         #132
        owner_id=33,
        category_id=6,
        address='1099 NW Overton Street',
        city='Portland',
        state='OR',
        zip_code='97209',
        name='The Fields Park',
        description='A popular downtown park with a designated off-leash dog area, offering open spaces for dogs to run and play.',
        website='https://www.portland.gov/parks/fields-park',
        phone='5038231637',
        set_hours="yes",
        mon_open='0500',
        mon_close='2400',
        tue_open='0500',
        tue_close='2400',
        wed_open='0500',
        wed_close='2400',
        thu_open='0500',
        thu_close='2400',
        fri_open='0500',
        fri_close='2400',
        sat_open='0500',
        sat_close='2400',
        sun_open='0500',
        sun_close='2400',
      ),
      Business(
         #133
        owner_id=33,
        category_id=7,
        address='1067 NE Columbia Blvd',
        city='Portland',
        state='OR',
        zip_code='97211',
        name='Oregon Humane Society',
        description='Dedicated to finding homes for pets in need, the Oregon Humane Society offers adoption services and volunteer opportunities.',
        website='https://www.oregonhumane.org',
        phone='5032857722',
      ),
      Business(
         #134
        owner_id=32,
        category_id=8,
        city='Portland',
        state='OR',
        zip_code='97221',
        name='Susi B Davis Watercolors',
        description='Watercolor pet portraits They are rendered from your or my photos plus a detailed description of his or her personality. If possible I prefer meeting the pet and getting to know their personality and taking photos.',
        website='http://www.susibdaviswatercolors.com/index.html#other',
        email='Susiwatercolors@gmail.com',
        phone='5033202937',
        set_hours="no",
      ),
      Business(
         #135
        owner_id=31,
        category_id=4,
        address='2531 Fair Oaks Blvd.',
        city='Sacramento',
        state='CA',
        zip_code='95825',
        name='Pet Food Express',
        description='Pet Food Express offers a wide selection of high-quality pet foods and products. Pets are welcome in the store.',
        website='https://www.petfood.express/',
        phone='9164879999',
        price='$$',
        set_hours="yes",
        mon_open='0900',
        mon_close='2030',
        tue_open='0900',
        tue_close='2030',
        wed_open='0900',
        wed_close='2030',
        thu_open='0900',
        thu_close='2030',
        fri_open='0900',
        fri_close='2030',
        sat_open='0900',
        sat_close='2030',
        sun_open='0900',
        sun_close='1900',
      ),
      Business(
         #136
        owner_id=31,
        category_id=1,
        address='1800 15th St Ste B',
        city='Sacramento',
        state='CA',
        zip_code='95811',
        name='Iron Horse Tavern',
        description='A casual eatery offering a variety of American dishes with an extensive beer list. Dogs are welcome on the patio.',
        website='https://www.ironhorsetavern.net/',
        phone='9164484488',
        price='$$',
        set_hours="yes",
        mon_open='1100',
        mon_close='2100',
        tue_open='1100',
        tue_close='2100',
        wed_open='1100',
        wed_close='2100',
        thu_open='1100',
        thu_close='2100',
        fri_open='1100',
        fri_close='2200',
        sat_open='0900',
        sat_close='2200',
        sun_open='0900',
        sun_close='2030',
      ),
      Business(
         #137
        owner_id=30,
        category_id=3,
        address='4060 Power Inn Rd',
        city='Sacramento',
        state='CA',
        zip_code='95826',
        name='The Animal Den Pet Resort',
        description='The Animal Den Pet Resort is a daycare center and boarding facility in Sacramento, CA. The resort has state-of-the-art climate/humidity controlled facilities which ensure a comfortable stay for Fido.',
        website='https://www.animaldenpetresort.com/',
        phone='9164564720',
        price='$$',
        set_hours="yes",
        mon_open='0700',
        mon_close='1830',
        tue_open='0700',
        tue_close='1830',
        wed_open='0700',
        wed_close='1830',
        thu_open='0700',
        thu_close='1830',
        fri_open='0700',
        fri_close='1830',
        sat_open='0730',
        sat_close='1700',
        sun_open='0730',
        sun_close='1700',
      ),
      Business(
         #138
        owner_id=30,
        category_id=5,
        address='2618 Gateway Oaks Dr',
        city='Sacramento',
        state='CA',
        zip_code='95833',
        name='Residence Inn by Marriott Sacramento Airport Natomas',
        description='This pet-friendly hotel offers a comfortable stay with amenities including a fitness center and pool.',
        website='https://www.marriott.com/en-us/hotels/sacsn-residence-inn-sacramento-airport-natomas/overview/?scid=f2ae0541-1279-4f24-b197-a979c79310b0',
        phone='9166491300',
        price='$$',
        set_hours="no",
      ),
      Business(
        #139
        owner_id=31,
        category_id=2,
        address='2513 Walnut Ave',
        city='Carmichael',
        state='CA',
        zip_code='95608',
        name='Reagor Pet Hospital',
        description='A full-service veterinary hospital providing comprehensive healthcare services to pets in the area.',
        website='https://reagorpethospital.com/',
        email='reagorpethospital@gmail.com',
        phone='9169711551',
        set_hours="yes",
        mon_open='0800',
        mon_close='1800',
        wed_open='0800',
        wed_close='1800',
        thu_open='0800',
        thu_close='1800',
        fri_open='0800',
        fri_close='1800',
      ),
      Business(
         #140
        owner_id=29,
        category_id=7,
        address='6001 Folsom Blvd',
        city='Sacramento',
        state='CA',
        zip_code='95819',
        name='Happy Tails Pet Sanctuary',
        description='Our Sacramento pet sanctuary and adoption program provides loving, compassionate care for homeless animals, giving abandoned and mistreated animals the second chance they deserve.',
        website='https://www.happytails.org/',
        email='purrball@happytails.org',
        phone='9165561155',
        set_hours="yes",
        thu_open='1200',
        thu_close='1800',
        fri_open='1200',
        fri_close='1800',
        sat_open='1200',
        sat_close='1500',
        sun_open='1200',
        sun_close='1500',
      ),
      Business(
         #141
        owner_id=29,
        category_id=6,
        address='1818 Q St',
        city='Sacramento',
        state='CA',
        zip_code='95834',
        name='Truitt Bark Park',
        description='A well-maintained dog park offering open spaces for dogs to play and socialize.',
        website='https://www.cityofsacramento.gov/ypce/parks',
        set_hours="yes",
        mon_open='0700',
        mon_close='2200',
        tue_open='0700',
        tue_close='2200',
        wed_open='0700',
        wed_close='2200',
        thu_open='0700',
        thu_close='2200',
        fri_open='0700',
        fri_close='2200',
        sat_open='0700',
        sat_close='2200',
        sun_open='0700',
        sun_close='2200',
      ),
      Business(
         #142
        owner_id=31,
        category_id=1,
        address='2332 K St',
        city='Sacramento',
        state='CA',
        zip_code='95816',
        name='Der Biergarten',
        description='Midtown Der Biergarten, is a casual German bar and eatery that serves up a variety of delicious brews and tasty fare. Fido is welcome to join you at one of their pet-friendly, traditional Biergarten tables.',
        website='https://beergardensacramento.com/',
        phone='9163464572',
        set_hours="yes",
        mon_open='1100',
        mon_close='2145',
        tue_open='1100',
        tue_close='2145',
        wed_open='1100',
        wed_close='2145',
        thu_open='1100',
        thu_close='2145',
        fri_open='1100',
        fri_close='2345',
        sat_open='1100',
        sat_close='2345',
        sun_open='1100',
        sun_close='2145',
      ),
      Business(
         #143
        owner_id=28,
        category_id=1,
        address='4501 Butler St',
        city='Pittsburgh',
        state='PA',
        zip_code='15201',
        name='Walter\'s BBQ Southern Kitchen',
        description='Enjoy BBQ and southern cuisine in Lawrenceville with your pup in their extensive outdoor space.',
        website='https://www.walterspgh.com/',
        phone='4126837474',
        price='$$',
        set_hours="yes",
        mon_open='1100',
        mon_close='2100',
        wed_open='1100',
        wed_close='2200',
        thu_open='1100',
        thu_close='2200',
        fri_open='1100',
        fri_close='2400',
        sat_open='1100',
        sat_close='2400',
        sun_open='1100',
        sun_close='0900',
      ),
      Business(
         #144
        owner_id=27,
        category_id=6,
        address='Riverview Ave',
        city='Pittsburgh',
        state='PA',
        zip_code='15214',
        name='Riverview Dog Park',
        description='A spacious dog park in Riverview Park with separate areas for small and large dogs.',
      ),
      Business(
         #145
        owner_id=28,
        category_id=3,
        address='6201 Spirit St',
        city='Pittsburgh',
        state='PA',
        zip_code='15206',
        name='Woof Gang Bakery & Grooming East Liberty',
        description='A pet store offering natural treats and grooming services in East Liberty.',
        website='https://woofgangbakery.com/pages/locations/east-liberty',
        phone='4123619220',
        price='$$',
        set_hours="yes",
        mon_open='0900',
        mon_close='1800',
        tue_open='0900',
        tue_close='1800',
        wed_open='0900',
        wed_close='1800',
        thu_open='0900',
        thu_close='1800',
        fri_open='0900',
        fri_close='1800',
        sat_open='0900',
        sat_close='1700',
      ),
      Business(
         #146
        owner_id=27,
        category_id=2,
        address='6742 Reynolds St',
        city='Pittsburgh',
        state='PA',
        zip_code='15206',
        name='Point Breeze Veterinary Clinic',
        description='A full-service veterinary clinic providing comprehensive pet care.',
        website='https://pointbreezevet.com/',
        email='pointbreezevet@gmail.com',
        phone='4126651810',
        set_hours="yes",
        mon_open='0800',
        mon_close='1900',
        tue_open='0800',
        tue_close='1830',
        wed_open='0800',
        wed_close='1830',
        thu_open='0800',
        thu_close='1830',
        fri_open='0800',
        fri_close='1800',
        sat_open='0900',
        sat_close='1200',
      ),
      Business(
         #147
        owner_id=26,
        category_id=3,
        address='5111 Doyle Road',
        city='Pittsburgh',
        state='PA',
        zip_code='15227',
        name='Chubby Puppy Daycare & Training',
        description='Chubby Puppy Daycare & Training offers daycare, obedience training classes, private instruction, toys and treats.',
        website='https://www.chubbypuppydaycare.com/',
        email='chubbypuppypittsburgh@gmail.com',
        phone='4126682286',
        set_hours="yes",
        mon_open='0700',
        mon_close='1800',
        tue_open='0700',
        tue_close='1800',
        wed_open='0700',
        wed_close='1800',
        thu_open='0700',
        thu_close='1800',
        fri_open='0700',
        fri_close='1800',
      ),
      Business(
         #148
        owner_id=27,
        category_id=5,
        address='620 William Penn Pl',
        city='Pittsburgh',
        state='PA',
        zip_code='15219',
        name='Kimpton Hotel Monaco Pittsburgh',
        description='A luxurious, pet-friendly hotel in downtown Pittsburgh with no extra fees for pets.',
        website='https://www.monaco-pittsburgh.com/',
        phone='4124711170',
        price='$$$',
      ),
      Business(
         #149
        owner_id=26,
        category_id=8,
        city='Pittsburgh',
        state='PA',
        zip_code='15206',
        name='Lap of Love',
        description='Lap of Love provides families and their pets with veterinary end-of-life care in the greater Pittsburgh area.',
        website='https://www.lapoflove.com/find-a-vet/Pennsylvania/Pittsburgh/about',
        email='Pittsburgh@LapofLove.com',
        phone='4126684468',
        set_hours="yes",
        mon_open='0700',
        mon_close='2300',
        tue_open='0700',
        tue_close='2300',
        wed_open='0700',
        wed_close='2300',
        thu_open='0700',
        thu_close='2300',
        fri_open='0700',
        fri_close='2300',
        sat_open='0700',
        sat_close='2300',
        sun_open='0700',
        sun_close='2300',
      ),
      Business(
         #150
        owner_id=25,
        category_id=7,
        address='413 E 6th Ave',
        city='Tarentum',
        state='PA',
        zip_code='15084',
        name='Paws Across Pittsburgh Animal Rescue',
        description='A non-profit foster-based animal rescue that works to rescue, rehabilitate, and re-home homeless, abused and unwanted dogs and cats.',
        website='https://www.pawsacrosspittsburgh.com/',
        email='info@pawsacrosspittsburgh.com',
        phone='4124952799',
        set_hours="yes",
        mon_open='0900',
        mon_close='1700',
        tue_open='0900',
        tue_close='1700',
        wed_open='0900',
        wed_close='1700',
        thu_open='0900',
        thu_close='1700',
        fri_open='0900',
        fri_close='1700',
        sat_open='0900',
        sat_close='1700',
        sun_open='0900',
        sun_close='1700',
      ),
      Business(
         #151
        owner_id=24,
        category_id=1,
        address='518 E Fremont St',
        city='Las Vegas',
        state='NV',
        zip_code='89101',
        name='Therapy',
        description='Therapy is a trendy eatery in the Fremont East District offering American comfort food and craft cocktails. Dogs are welcome at the outdoor seating area.',
        website='http://www.therapylv.com',
        phone='7029121622',
        price='$$',
        set_hours="yes",
        tue_open='1100',
        tue_close='2400',
        wed_open='1100',
        wed_close='2400',
        thu_open='1100',
        thu_close='2400',
        fri_open='1100',
        fri_close='2400',
        sat_open='1100',
        sat_close='2400',
        sun_open='1100',
        sun_close='2400',
      ),
      Business(
         #152
        owner_id=25,
        category_id=2,
        address='1117 N. Decatur Blvd.',
        city='Las Vegas',
        state='NV',
        zip_code='89108',
        name='VCA Decatur Animal Hospital',
        description='Animal hospital that offers comprehensive veterinary care including wellness exams, preventative care, surgery, and dental care.',
        website='https://vcahospitals.com/decatur',
        phone='7026463777',
        set_hours="yes",
        mon_open='0800',
        mon_close='1800',
        tue_open='0800',
        tue_close='1800',
        wed_open='0800',
        wed_close='1800',
        thu_open='0800',
        thu_close='1800',
        fri_open='0800',
        fri_close='1800',
        sat_open='0800',
        sat_close='1400',
      ),
      Business(
         #153
        owner_id=33,
        category_id=3,
        address='6050 West Lone Mountain Road',
        city='Las Vegas',
        state='NV',
        zip_code='89130',
        name='Tails Pet Resort',
        description='Tails Pet Resort offers boarding, daycare, and grooming services for dogs. Their facilities include spacious play areas and comfortable boarding suites.',
        website='https://www.tailsresorts.com/',
        email='reservations@tailsresorts.com',
        phone='7025099909',
        set_hours="yes",
        mon_open='0630',
        mon_close='1900',
        tue_open='0630',
        tue_close='1900',
        wed_open='0630',
        wed_close='1900',
        thu_open='0630',
        thu_close='1900',
        fri_open='0630',
        fri_close='1900',
        sat_open='0800',
        sat_close='1800',
        sun_open='0900',
        sun_close='1700',
      ),
      Business(
         #154
        owner_id=34,
        category_id=4,
        address='9890 S. Maryland Parkway',
        city='Las Vegas',
        state='NV',
        zip_code='89183',
        name='BanksyDog',
        description='A boutique pet store in Las Vegas, NV, that offers pet food, treats, toys and many other supplies. They also have self-serve dog wash stations for you to bathe your pup, or you can schedule a professional grooming appointment. ',
        website='https://www.banksydog.com/',
        email='angelo@banksydog.com',
        phone='7026138259',
        set_hours="yes",
        mon_open='1000',
        mon_close='1900',
        tue_open='1000',
        tue_close='1900',
        wed_open='1000',
        wed_close='1900',
        thu_open='1000',
        thu_close='1900',
        fri_open='1000',
        fri_close='1900',
        sat_open='1000',
        sat_close='1900',
        sun_open='1000',
        sun_close='1900',
      ),
      Business(
         #155
        owner_id=37,
        category_id=5,
        address='145 E Harmon Ave',
        city='Las Vegas',
        state='NV',
        zip_code='89109',
        name='The Signature at MGM Grand',
        description='The Signature at MGM Grand is a pet-friendly hotel offering luxurious accommodations and services. Pets are welcome for an additional fee.',
        website='https://www.signaturemgmgrand.com',
        phone='8777270007',
        price='$$$$',
        set_hours="no",
      ),
      Business(
         #156
        owner_id=36,
        category_id=6,
        address='1600 Wigwam Pkwy',
        city='Henderson',
        state='NV',
        zip_code='89074',
        name='Cornerstone Park',
        description='Cornerstone Park offers a large lake, walking trails, and picnic areas. Dogs are welcome on-leash and there is a designated off-leash dog area.',
        website='https://www.cityofhenderson.com/Home/Components/FacilityDirectory/FacilityDirectory/218/752',
        set_hours="yes",
        mon_open='0600',
        mon_close='2400',
        tue_open='0600',
        tue_close='2400',
        wed_open='0600',
        wed_close='2400',
        thu_open='0600',
        thu_close='2400',
        fri_open='0600',
        fri_close='2400',
        sat_open='0600',
        sat_close='2400',
        sun_open='0600',
        sun_close='2400',
      ),
      Business(
         #157
        owner_id=42,
        category_id=7,
        address='1750 S Rainbow Blvd',
        city='Las Vegas',
        state='NV',
        zip_code='89146',
        name='Hearts Alive Village',
        description='Hearts Alive Village is a non-profit animal rescue organization dedicated to providing safe and loving homes for homeless animals.',
        website='https://heartsalivevillage.org',
        email='info@heartsalivevillage.org',
        phone='7028700065',
        set_hours="yes",
        mon_open='1000',
        mon_close='1800',
        tue_open='1000',
        tue_close='1800',
        wed_open='1000',
        wed_close='1800',
        thu_open='1000',
        thu_close='1800',
        fri_open='1000',
        fri_close='1800',
        sat_open='1000',
        sat_close='1800',
        sun_open='1000',
        sun_close='1600',
      ),
      Business(
         #158
        owner_id=28,
        category_id=8,
        city='Las Vegas',
        state='NV',
        zip_code='89032',
        name='Pawtraits by Nicole',
        description='Professional dog photographer with a passion for capturing the unfiltered charm of our furry companions.',
        website='https://www.pawtraitsbynicole.com/',
        phone='7023583298',
        set_hours="no",
      ),
      Business(
         #159
        owner_id=35,
        category_id=1,
        address='3825 Edwards Road',
        city='Cincinnati',
        state='OH',
        zip_code='45209',
        name='Taste of Belgium',
        description='You can eat and drink like a true Belgian at Taste of Belgium. This location on Race Street in Cincinnati offer dog-friendly seating with a lot of outdoor tables.',
        website='https://authenticwaffle.com/',
        set_hours="yes",
        mon_open='0800',
        mon_close='1500',
        tue_open='0800',
        tue_close='2200',
        wed_open='0800',
        wed_close='2200',
        thu_open='0800',
        thu_close='2200',
        fri_open='0800',
        fri_close='2200',
        sat_open='0800',
        sat_close='2200',
        sun_open='0800',
        sun_close='2100',
      ),
      Business(
         #160
        owner_id=44,
        category_id=1,
        address='7022 Miami Ave',
        city='Cincinnati',
        state='OH',
        zip_code='45243',
        name='A Tavola Bar + Trattoria',
        description='The eclectic menu includes sliders, meatballs, bruschette, and signature pizza. Dogs are welcome at outdoor patios.',
        website='https://www.atavolapizza.com/',
        phone='5132720192',
        set_hours="yes",
        mon_open='1100',
        mon_close='2100',
        tue_open='1100',
        tue_close='2100',
        wed_open='1100',
        wed_close='2100',
        thu_open='1100',
        thu_close='2100',
        fri_open='1100',
        fri_close='2200',
        sat_open='1100',
        sat_close='2200',
        sun_open='1100',
        sun_close='2100',
      ),
      Business(
         #161
        owner_id=33,
        category_id=2,
        address='7670 Montgomery Rd',
        city='Cincinnati',
        state='OH',
        zip_code='45236',
        name='Montgomery Animal Hospital',
        description='Montgomery Animal Hospital offers comprehensive veterinary care for your pets including wellness exams, surgery, and dental care.',
        website='https://www.montgomeryanimalhospital.com',
        set_hours="yes",
        mon_open='0730',
        mon_close='1800',
        tue_open='0730',
        tue_close='1800',
        wed_open='0730',
        wed_close='1800',
        thu_open='0730',
        thu_close='1800',
        fri_open='0730',
        fri_close='1800',
        sat_open='0800',
        sat_close='1400',
      ),
      Business(
         #162
        owner_id=42,
        category_id=3,
        address='3797 Shady Ln',
        city='North Bend',
        state='OH',
        zip_code='45052',
        name='Pet Wants',
        description='Pet Wants offers fresh, all-natural pet food that is made monthly to ensure the freshest quality. They also provide free delivery to the Cincinnati area.',
        website='https://www.petwantscincywest.com',
        email='InfoCincyWest@petwants.com',
        phone='5138721188',
        set_hours="yes",
        mon_open='1000',
        mon_close='1900',
        tue_open='1000',
        tue_close='1900',
        wed_open='1000',
        wed_close='1900',
        thu_open='1000',
        thu_close='1900',
        fri_open='1000',
        fri_close='1900',
        sat_open='1000',
        sat_close='1600',
        sun_open='1200',
        sun_close='1500',
      ),
      Business(
         #163
        owner_id=32,
        category_id=3,
        address='5081 Madison Rd',
        city='Cincinnati',
        state='OH',
        zip_code='45227',
        name='Red Dog Pet Resort & Spa',
        description='Red Dog Pet Resort & Spa provides boarding, daycare, grooming, and training services. They offer a luxurious experience for your pet with plenty of playtime and attention.',
        website='https://www.reddogpetresort.com',
        email='cincinnati@reddogpetresort.com',
        phone='5137333647',
        set_hours="yes",
        mon_open='0700',
        mon_close='1900',
        tue_open='0700',
        tue_close='1900',
        wed_open='0700',
        wed_close='1900',
        thu_open='0700',
        thu_close='1900',
        fri_open='0700',
        fri_close='1900',
        sat_open='0800',
        sat_close='1600',
        sun_open='1000',
        sun_close='1600',
      ),
      Business(
         #164
        owner_id=45,
        category_id=5,
        address='151 Goodman Dr',
        city='Cincinnati',
        state='OH',
        zip_code='45219',
        name='Graduate Cincinnati',
        description='Four star hotel that welcomes two pets of any size for an additional fee of $75 per pet, per stay.',
        website='https://graduatehotels.com/cincinnati/',
        set_hours="no",
      ),
      Business(
         #165
        owner_id=35,
        category_id=1,
        address='7605 Wooster Pike',
        city='Cincinnati',
        state='OH',
        zip_code='45227',
        name='Fifty West Brewing Company',
        description='Our burger Bar was created with families in mind (And yes, dogs are family) We have draft beer, cider, wine, thc beverages, and non-alcoholic options in addition to a fantastic selection of food offerings including a kid friendly menu.',
        website='https://www.fiftywestbrew.com',
        phone='5138348789',
        set_hours="yes",
        mon_open='1100',
        mon_close='2300',
        tue_open='1100',
        tue_close='2300',
        wed_open='1100',
        wed_close='2300',
        thu_open='1100',
        thu_close='2300',
        fri_open='1100',
        fri_close='2300',
        sat_open='1100',
        sat_close='2300',
        sun_open='1100',
        sun_close='2100',
      ),
      Business(
         #166
        owner_id=49,
        category_id=6,
        address='100 W Mehring Way',
        city='Cincinnati',
        state='OH',
        zip_code='45202',
        name='Smale Riverfront Park',
        description='Leashed dogs are welcome to join their humans at Smale Riverfront Park in Cincinnati, OH. This dog-friendly recreation area includes trails, a labyrinth, gardens, fountains, a carousel, an esplanade, benches, swings and more.',
        website='https://www.cincinnati-oh.gov/cincyparks/visit-a-park/find-a-parkfacility/smale-riverfront-park/',
        phone='5133526180',
        set_hours="yes",
        mon_open='0600',
        mon_close='2200',
        tue_open='0600',
        tue_close='2200',
        wed_open='0600',
        wed_close='2200',
        thu_open='0600',
        thu_close='2200',
        fri_open='0600',
        fri_close='2200',
        sat_open='0600',
        sat_close='2200',
        sun_open='0600',
        sun_close='2200',
      ),
      Business(
         #167
        owner_id=38,
        category_id=7,
        address='11900 Conrey Road',
        city='Cincinnati',
        state='OH',
        zip_code='45249',
        name='SPCA Cincinnati',
        description='SPCA Cincinnati offers pet adoption services and strives to connect loving families with their new furry friends.',
        website='https://www.spcacincinnati.org',
        phone='5135416100',
        set_hours="yes",
        mon_open='1200',
        mon_close='1800',
        tue_open='1200',
        tue_close='1800',
        wed_open='1200',
        wed_close='1800',
        thu_open='1200',
        thu_close='1800',
        fri_open='1200',
        fri_close='1800',
        sat_open='1200',
        sat_close='1800',
        sun_open='1200',
        sun_close='1800',
      ),
      Business(
         #168
        owner_id=48,
        category_id=8,
        address='2722 Erie Ave',
        city='Cincinnati',
        state='OH',
        zip_code='45208',
        name='COhatch',
        description='COhatch in Cincinnati, OH, allows enterprising pups to join you in a private office with prior approval. ',
        website='https://www.cohatch.com/locations/cincinnati/hyde-park/',
        set_hours="no",
      ),
      Business(
         #169
        owner_id=46,
        category_id=1,
        address='440A W 2nd St',
        city='Austin',
        state='TX',
        zip_code='78701',
        name='La Condesa',
        description='A contemporary Mexican restaurant that welcomes pets in their outdoor seating area.',
        website='https://lacondesa.com/',
        email='info@lacondesa.com',
        phone='5124990300',
        price='$$$',
        set_hours="yes",
        mon_open='1700',
        mon_close='2200',
        tue_open='1700',
        tue_close='2200',
        wed_open='1700',
        wed_close='2200',
        thu_open='1700',
        thu_close='2200',
        fri_open='1700',
        fri_close='2300',
        sat_open='1100',
        sat_close='2300',
        sun_open='1100',
        sun_close='2200',
      ),
      Business(
         #170
        owner_id=26,
        category_id=1,
        address='2027 S Lamar Blvd',
        city='Austin',
        state='TX',
        zip_code='78704',
        name='Bouldin Acres',
        description='Bouldin Acres, located in Austin, TX, is a trendy beer garden and eatery that serves up a myriad of delicious drinks, tasty fare, fun lawn games, and more. Fido is welcome to join you at this pet-friendly joint while you enjoy your day.',
        website='https://bouldinacres.com/south-lamar/',
        email='info@bouldinacres.com',
        phone='7372843409',
        price='$$',
        set_hours="yes",
        mon_open='1100',
        mon_close='2400',
        tue_open='1100',
        tue_close='2400',
        wed_open='1100',
        wed_close='2400',
        thu_open='1100',
        thu_close='2400',
        fri_open='1100',
        fri_close='2400',
        sat_open='1100',
        sat_close='2400',
        sun_open='1100',
        sun_close='2400',
      ),
      Business(
         #171
        owner_id=44,
        category_id=2,
        address='3407 Northland Dr',
        city='Austin',
        state='TX',
        zip_code='78731',
        name='Griffith Small Animal Hospital',
        description='A full-service veterinary clinic offering medical, surgical, and dental care for pets.',
        website='http://www.griffithanimalhospital.com/',
        email='gsahstaff@griffithvet.net',
        phone='7379109993',
        set_hours="yes",
        mon_open='0700',
        mon_close='1800',
        tue_open='0700',
        tue_close='1800',
        wed_open='0700',
        wed_close='1800',
        thu_open='0700',
        thu_close='1800',
        fri_open='0700',
        fri_close='1800',
      ),
      Business(
         #172
        owner_id=33,
        category_id=3,
        address='509 Cypress Creek Rd',
        city='Cedar Park',
        state='TX',
        zip_code='78613',
        name='Happy Tails Pet Resort',
        description='Offering grooming, boarding, and daycare services for pets in a luxurious setting.',
        website='https://www.happytailspetresorttx.com/',
        email='info@happytailsaustin.com',
        phone='5126416491',
        price='$$',
        set_hours="yes",
        mon_open='0700',
        mon_close='1900',
        tue_open='0700',
        tue_close='1900',
        wed_open='0700',
        wed_close='1900',
        thu_open='0700',
        thu_close='1900',
        fri_open='0700',
        fri_close='1900',
        sat_open='0800',
        sat_close='1700',
        sun_open='0800',
        sun_close='1700',
      ),
      Business(
         #173
        owner_id=31,
        category_id=4,
        address='916B 12th St',
        city='Austin',
        state='TX',
        zip_code='78703',
        name='Tomlinson\'s Feed',
        description='A pet store offering premium natural pet foods and supplies with several locations in Austin.',
        website='https://www.tomlinsons.com/',
        phone='5125141881',
        price='$$',
        set_hours="yes",
        mon_open='0900',
        mon_close='2000',
        tue_open='0900',
        tue_close='2000',
        wed_open='0900',
        wed_close='2000',
        thu_open='0900',
        thu_close='2000',
        fri_open='0900',
        fri_close='2000',
        sat_open='0900',
        sat_close='2000',
        sun_open='1000',
        sun_close='1800',
      ),
      Business(
         #174
        owner_id=46,
        category_id=5,
        address='600 Davis St',
        city='Austin',
        state='TX',
        zip_code='78701',
        name='Hotel Van Zandt',
        description='A pet-friendly hotel that offers amenities for pets, including beds, bowls, and treats.',
        website='https://www.hotelvanzandt.com/',
        phone='5125425300',
        price='$$$',
        set_hours="no",
      ),
      Business(
         #175
        owner_id=42,
        category_id=6,
        address='2100 Barton Springs Rd',
        city='Austin',
        state='TX',
        zip_code='78704',
        name='Zilker Metropolitan Park',
        description='A large urban park offering a variety of activities including hiking, kayaking, and an off-leash dog area.',
        website='http://www.austintexas.gov/department/zilker-metropolitan-park',
        set_hours="yes",
        mon_open='0500',
        mon_close='2200',
        tue_open='0500',
        tue_close='2200',
        wed_open='0500',
        wed_close='2200',
        thu_open='0500',
        thu_close='2200',
        fri_open='0500',
        fri_close='2200',
        sat_open='0500',
        sat_close='2200',
        sun_open='0500',
        sun_close='2200',
      ),
      Business(
         #176
        owner_id=32,
        category_id=6,
        address='Abbate Cir',
        city='Austin',
        state='TX',
        zip_code='78721',
        name='Austin Doga',
        description='Yoga and mindfulness with your dog for relaxation, bonding, & joy.',
        website='https://www.austindoga.com/',
        email='austindoga@gmail.com',
        phone='5124133648',
        set_hours="no",
      ),
      Business(
         #177
        owner_id=20,
        category_id=7,
        address='7201 Levander Loop Bldg A',
        city='Austin',
        state='TX',
        zip_code='78702',
        name='Austin Animal Center',
        description='The largest no-kill animal shelter in the United States, providing adoption services.',
        website='http://www.austintexas.gov/department/aac',
        phone='5129780500',
        set_hours="yes",
        mon_open='1100',
        mon_close='1900',
        wed_open='1100',
        wed_close='1900',
        thu_open='1100',
        thu_close='1900',
        fri_open='1100',
        fri_close='1900',
        sat_open='1100',
        sat_close='1900',
        sun_open='1100',
        sun_close='1900',
      ),
      Business(
         #178
        owner_id=29,
        category_id=3,
        address='7739 Northcross Dr STE H',
        city='Austin',
        state='TX',
        zip_code='78757',
        name='Zoom Room Dog Training',
        description='An indoor dog training gym that offers classes, private training, and agility courses.',
        website='https://www.zoomroom.com/location/austin/',
        phone='5123711223',
        price='$$',
        set_hours="yes",
        tue_open='1300',
        tue_close='2100',
        wed_open='0900',
        wed_close='2100',
        thu_open='1300',
        thu_close='2100',
        fri_open='1200',
        fri_close='1900',
        sat_open='0900',
        sat_close='2000',
        sun_open='0900',
        sun_close='2000',
      ), #########
      Business(
         #179
        owner_id=15,
        category_id=1,
        address=' 3179 Los Feliz Blvd',
        city='Los Angeles',
        state='CA',
        zip_code='90039',
        name='The Morrison',
        description='Scottish pub serving upscale burgers & pub eats in addition to a huge selection of beer & whiskey. Has an outdoor dining area where pets are welcome.',
        phone='3236671839',
        price='$$',
        set_hours="yes",
        mon_open='1200',
        mon_close='2100',
        tue_open='1200',
        tue_close='2100',
        wed_open='1200',
        wed_close='2100',
        thu_open='1200',
        thu_close='2200',
        fri_open='1200',
        fri_close='2300',
        sat_open='1200',
        sat_close='2300',
        sun_open='1200',
        sun_close='2100',
      ),
      Business(
        #180
        owner_id=27,
        category_id=2,
        address='2162 Sunset Blvd',
        city='Los Angeles',
        state='CA',
        zip_code='90026',
        name='Mohawk Alley Animal Hospital',
        description='Comprehensive veterinary services for your pets, from routine check-ups to surgeries.',
        website='https://www.mohawkalleyanimalhospital.com/site/home',
        phone='2132017900',
        set_hours="yes",
        mon_open='0800',
        mon_close='1800',
        tue_open='0800',
        tue_close='1800',
        wed_open='0800',
        wed_close='1800',
        thu_open='0800',
        thu_close='1800',
        fri_open='0800',
        fri_close='1800',
        sat_open='0800',
        sat_close='1800',
        sun_open='0800',
        sun_close='1800',
      ),
      Business(
        #181
        owner_id=30,
        category_id=3,
        address='11860 Mississippi Avenue',
        city='Los Angeles',
        state='CA',
        zip_code='90025',
        name='The Wags Club',
        description='Premier dog daycare and boarding facility with spacious indoor and outdoor play areas.',
        website='https://thewagsclub.com/',
        phone='3104733333',
        price='$$$',
        set_hours="yes",
        mon_open='0700',
        mon_close='2100',
        tue_open='0700',
        tue_close='2100',
        wed_open='0700',
        wed_close='2100',
        thu_open='0700',
        thu_close='2100',
        fri_open='0700',
        fri_close='2100',
        sat_open='0900',
        sat_close='1700',
        sun_open='0900',
        sun_close='1700',
      ),
      Business(
        #182
        owner_id=9,
        category_id=4,
        address='1000 S Grand Ave A',
        city='Los Angeles',
        state='CA',
        zip_code='90015',
        name='Healthy Spot',
        description='Pet store offering high-quality pet products and grooming services.',
        website='https://healthyspot.com/',
        phone='2139217700',
        price='$$',
        set_hours="yes",
        mon_open='0800',
        mon_close='1900',
        tue_open='0800',
        tue_close='1900',
        wed_open='0800',
        wed_close='1900',
        thu_open='0800',
        thu_close='1900',
        fri_open='0800',
        fri_close='1900',
        sat_open='0900',
        sat_close='1900',
        sun_open='0900',
        sun_close='1900',
      ),
      Business(
         #183
        owner_id=21,
        category_id=5,
        address='328 E 1st St',
        city='Los Angeles',
        state='CA',
        zip_code='90012',
        name='Miyako Hotel Los Angeles',
        description='A pet-friendly hotel in the heart of Little Tokyo offering modern amenities.',
        website='https://www.miyakola.com/',
        phone='2136172000',
        price='$$$',
        set_hours="no",
      ),
      Business(
         #184
        owner_id=4,
        category_id=6,
        address='647 N San Vicente Blvd',
        city='West Hollywood',
        state='CA',
        zip_code='90069',
        name='West Hollywood Park',
        description='A beautiful park with a designated dog area for your pets to enjoy.',
        website='https://www.weho.org/Home/Components/FacilityDirectory/FacilityDirectory/2/773',
        phone='3238486534',
        set_hours="yes",
        mon_open='0600',
        mon_close='2400',
        tue_open='0600',
        tue_close='2400',
        wed_open='0600',
        wed_close='2400',
        thu_open='0600',
        thu_close='2400',
        fri_open='0600',
        fri_close='2400',
        sat_open='0600',
        sat_close='2400',
        sun_open='0600',
        sun_close='2400',
      ),
      Business(
         #185
        owner_id=17,
        category_id=7,
        address='7700 E Spring St',
        city='Long Beach',
        state='CA',
        zip_code='90815',
        name='Long Beach Animal Care Services',
        description='Non-profit animal rescue organization dedicated to finding homes for pets in need.',
        website='https://www.longbeach.gov/acs',
        phone='5625707387',
        set_hours="yes",
        wed_open='1000',
        wed_close='1730',
        thu_open='1000',
        thu_close='1730',
        fri_open='1000',
        fri_close='1730',
        sat_open='1000',
        sat_close='1600',
        sun_open='1000',
        sun_close='1600',
      ),
      Business(
         #186
        owner_id=42,
        category_id=8,
        city='Los Angeles',
        state='CA',
        zip_code='90001',
        name='Diana Lundin Fine Art Pet Photographer ',
        description='Diana Lundin is a PPA certified, international award-winning Los Angeles pet photographer. Her pet photography is creative, dramatic, humorous.',
        website='https://www.dianalundin.com/',
        phone='8184815214',
        set_hours="no",
      ),
      Business(
       #187
        owner_id=5,
        category_id=1,
        address='2959 N California Ave',
        city='Chicago',
        state='IL',
        zip_code='60618',
        name='Ludlow Liquors',
        description='This Avondale bar offers a backyard garden patio with plenty of room for people and pooches to soak up the sun. ',
        website='https://www.ludlow-liquors.com/',
        phone='7737547492',
        price='$$',
        set_hours="yes",
        mon_open='1700',
        mon_close='2400',
        wed_open='1700',
        wed_close='2400',
        thu_open='1700',
        thu_close='2400',
        fri_open='1700',
        fri_close='2400',
        sat_open='1500',
        sat_close='2400',
        sun_open='1500',
        sun_close='2400',
      ),
      Business(
         #188
        owner_id=12,
        category_id=2,
        address='620 W Webster Ave',
        city='Chicago',
        state='IL',
        zip_code='60614',
        name='Oz Animal Hospital',
        description='A full-service animal hospital offering comprehensive medical, surgical, and dental care.',
        website='https://ozanimalhospital.com/contact-lincoln-park/',
        email='lincolnpark@ozanimalhospital.com',
        phone='7733489867',
        set_hours="yes",
        mon_open='0800',
        mon_close='1800',
        tue_open='0800',
        tue_close='1800',
        wed_open='0800',
        wed_close='1800',
        thu_open='0800',
        thu_close='1800',
        fri_open='0800',
        fri_close='1800',
        sat_open='0800',
        sat_close='1400',
      ),
      Business(
         #189
        owner_id=24,
        category_id=3,
        address='350 N Laflin St',
        city='Chicago',
        state='IL',
        zip_code='60607',
        name='Pet Care Plus',
        description='Provides dog walking, grooming, and boarding services in a state-of-the-art facility.',
        website='https://www.petcp.com/',
        phone='3123979077',
        price='$$',
        set_hours="yes",
        mon_open='0645',
        mon_close='1900',
        tue_open='0645',
        tue_close='1900',
        wed_open='0645',
        wed_close='1900',
        thu_open='0645',
        thu_close='1900',
        fri_open='0645',
        fri_close='1900',
        sat_open='0900',
        sat_close='1600',
        sun_open='1000',
        sun_close='1500',
      ),
      Business(
         #190
        owner_id=9,
        category_id=4,
        address=' 3337 N. Broadway St',
        city='Chicago',
        state='IL',
        zip_code='60657',
        name='Wigglyville, Inc.',
        description='A pet boutique offering a wide range of pet supplies, food, and accessories for dogs and cats.',
        website='https://wigglyville.com/',
        email='wigglyville@gmail.com',
        phone='7735283337',
        price='$$$',
        set_hours="yes",
        mon_open='1000',
        mon_close='1900',
        tue_open='1000',
        tue_close='1900',
        wed_open='1000',
        wed_close='1900',
        thu_open='1000',
        thu_close='1900',
        fri_open='1000',
        fri_close='1900',
        sat_open='1000',
        sat_close='1800',
        sun_open='1000',
        sun_close='1800',
      ),
      Business(
         #191
        owner_id=16,
        category_id=5,
        address='2121 S Prairie Ave',
        city='Chicago',
        state='IL',
        zip_code='60616',
        name='Marriott Marquis Chicago',
        description='A pet-friendly hotel located in the heart of the city, offering luxurious accommodations and amenities.',
        website='https://www.marriott.com/en-us/hotels/chimq-marriott-marquis-chicago/overview/?scid=f2ae0541-1279-4f24-b197-a979c79310b0',
        phone='3128240500',
        price='$$$',
        set_hours="no",
      ),
      Business(
         #192
        owner_id=22,
        category_id=6,
        address='500-5700 N Lake Shore Dr',
        city='Chicago',
        state='IL',
        zip_code='60614',
        name='Lincoln (Abraham) Park',
        description='A large public park offering open spaces, walking trails, and designated dog-friendly areas.',
        website='https://www.chicagoparkdistrict.com/parks-facilities/lincoln-abraham-park',
        phone='3127427726',
        set_hours="yes",
        mon_open='0600',
        mon_close='2300',
        tue_open='0600',
        tue_close='2300',
        wed_open='0600',
        wed_close='2300',
        thu_open='0600',
        thu_close='2300',
        fri_open='0600',
        fri_close='2300',
        sat_open='0600',
        sat_close='2300',
        sun_open='0600',
        sun_close='2300',
      ),
      Business(
         #193
        owner_id=33,
        category_id=7,
        address='1997 N Clybourn Ave',
        city='Chicago',
        state='IL',
        zip_code='60614',
        name='PAWS Chicago Adoption Center',
        description='A no-kill animal shelter dedicated to finding homes for homeless pets through adoption and fostering.',
        website='https://www.pawschicago.org/',
        phone='7739357297',
        set_hours="yes",
        mon_open='1200',
        mon_close='1900',
        wed_open='1200',
        wed_close='1900',
        thu_open='1200',
        thu_close='1900',
        fri_open='1200',
        fri_close='1900',
        sat_open='1100',
        sat_close='1700',
        sun_open='1100',
        sun_close='1700',
      ),
      Business(
         #194
        owner_id=27,
        category_id=8,
        address='1112 N Ashland Ave #1F',
        city='Chicago',
        state='IL',
        zip_code='60622',
        name='Van & Bella\'s, Pet Photography Studio',
        description='Specializes in capturing memorable moments of pets with professional photography services.',
        website='https://vanandbellas.com/',
        phone='3126008540',
        set_hours="no",
      ),
      Business(
         #195
        owner_id=8,
        category_id=1,
        address='1950 Market Center Blvd',
        city='Dallas',
        state='TX',
        zip_code='75207',
        name='Ferris Wheelers Backyard and BBQ',
        description='Sitting in the shadow of a ferris wheel on the west side, this spot has brisket queso, sausage corn dogs, and pulled pork sandwiches — without the hassle of going to the fair grounds. It’s kid and dog friendly.',
        website='https://hatcreekburgers.com',
        phone='2147414141',
        price='$$',
        set_hours="yes",
        mon_open='1100',
        mon_close='2200',
        tue_open='1100',
        tue_close='2200',
        wed_open='1100',
        wed_close='2200',
        thu_open='1100',
        thu_close='2200',
        fri_open='1100',
        fri_close='2200',
        sat_open='1100',
        sat_close='2200',
        sun_open='1100',
        sun_close='2200',
      ),
      Business(
         #196
        owner_id=12,
        category_id=1,
        address='2889 Cityplace W Blvd',
        city='Dallas',
        state='TX',
        zip_code='75204',
        name='MUTTS Canine Cantina',
        description="Grab a bite and relax while your dog runs and plays at this popular off-leash dog park and beer garden. The simple menu of cocktails, burgers, chicken, and treats for the fur babies is sure to satisfy.",
        website='https://muttscantina.com/tx-dallas/',
        phone='2143778723',
        price='$',
        set_hours="yes",
        mon_open='1500',
        mon_close='2200',
        tue_open='1500',
        tue_close='2200',
        wed_open='1500',
        wed_close='2200',
        thu_open='1500',
        thu_close='2200',
        fri_open='1500',
        fri_close='2200',
        sat_open='1100',
        sat_close='2200',
        sun_open='1100',
        sun_close='2200',
      ),
      Business(
         #197
        owner_id=24,
        category_id=4,
        address=' 2031 Abrams Rd',
        city='Dallas',
        state='TX',
        zip_code='75214',
        name='Hollywood Feed',
        description="Hollywood Feed offers a wide selection of premium and natural pet foods and supplies. Pets are welcome to browse the store with their owners.",
        website='https://locations.hollywoodfeed.com/texas/dallas/2031-abrams-rd/',
        phone='9726850036',
        set_hours="yes",
        mon_open='0900',
        mon_close='1930',
        tue_open='0900',
        tue_close='1930',
        wed_open='0900',
        wed_close='1930',
        thu_open='0900',
        thu_close='1930',
        fri_open='0900',
        fri_close='1930',
        sat_open='0900',
        sat_close='1930',
        sun_open='1000',
        sun_close='1830',
      ),
      Business(
         #198
        owner_id=30,
        category_id=2,
        address='4660 W Lovers Ln',
        city='Dallas',
        state='TX',
        zip_code='75209',
        name='VCA Lovers Lane Animal Hospital',
        description="Lovers Lane Animal Hospital provides comprehensive veterinary care including preventive health care, surgery, and dental care.",
        website='https://vcahospitals.com/lovers-lane',
        phone='2143505696',
        set_hours="yes",
        mon_open='0700',
        mon_close='1800',
        tue_open='0700',
        tue_close='1800',
        wed_open='0700',
        wed_close='1800',
        thu_open='0700',
        thu_close='1800',
        fri_open='0700',
        fri_close='1800',
        sat_open='0800',
        sat_close='1200',
      ),
      Business(
         #199
        owner_id=5,
        category_id=5,
        address='1033 Young St',
        city='Dallas',
        state='TX',
        zip_code='75202',
        name='Aloft Dallas Downtown',
        description="Aloft Dallas Downtown is a pet-friendly hotel that offers comfortable accommodation for guests and their pets. It provides modern amenities and a convenient downtown location.",
        website='https://www.marriott.com/en-us/hotels/daldl-aloft-dallas-downtown/overview/',
        phone='2147610000',
        price='$$$',
        set_hours="no",
      ),
      Business(
         #200
        owner_id=14,
        category_id=6,
        address='1570 FM 1382',
        city='Cedar Hill',
        state='TX',
        zip_code='75104',
        name='Cedar Hill State Park',
        description="Cedar Hill State Park offers hiking trails, picnic areas, and scenic views, making it a great destination for outdoor activities with pets.",
        website='https://tpwd.texas.gov/state-parks/cedar-hill',
        phone='9722913900',
        set_hours="yes",
        mon_open='0600',
        mon_close='2200',
        tue_open='0600',
        tue_close='2200',
        wed_open='0600',
        wed_close='2200',
        thu_open='0600',
        thu_close='2200',
        fri_open='0600',
        fri_close='2200',
        sat_open='0600',
        sat_close='2200',
        sun_open='0600',
        sun_close='2200',
      ),
      Business(
         #201
        owner_id=21,
        category_id=3,
        city='Dallas',
        state='TX',
        zip_code='75206',
        name='DogFit Dallas',
        description="DogFit Dallas offers in-home dog training sessions, board & train and immersion programs, group classes, online workshops, and a community of support.",
        website='https://dogfitdallas.com/',
        email='INFO@DOGFITDALLAS.COM',
        phone='2145855212',
        set_hours="no",
      ),
      Business(
         #202
        owner_id=32,
        category_id=7,
        address='4140 Valley View Ln',
        city='Irving',
        state='TX',
        zip_code='75038',
        name='DFW Humane Society',
        description="DFW Humane Society is a non-profit, no-kill animal shelter dedicated to rescuing and finding homes for unwanted and neglected pets.",
        website='https://www.dfwhumane.com/',
        phone='9727217788',
        set_hours="yes",
        tue_open='1200',
        tue_close='1800',
        wed_open='1200',
        wed_close='1800',
        thu_open='1200',
        thu_close='1800',
        fri_open='1200',
        fri_close='1800',
        sat_open='1000',
        sat_close='1700',
      ),
      Business(
         #203
        owner_id=45,
        category_id=8,
        city='Dallas',
        state='TX',
        zip_code='75206',
        name='Haute Dog Pet & Equestrian Photography',
        description="Dallas pet photographer with a 7-acre studio and vintage truck specializing in personality-packed dog portraits and vibrant horse photography for people and companies.",
        website='https://www.urbanpawspetcare.com/',
        email='Bark@HauteDogPetPhotography.com',
        phone='4695734364',
        set_hours="yes",
        mon_open='0800',
        mon_close='2000',
        tue_open='0800',
        tue_close='2000',
        wed_open='0800',
        wed_close='2000',
        thu_open='0800',
        thu_close='2000',
        fri_open='0800',
        fri_close='2000',
        sat_open='0800',
        sat_close='2000',
        sun_open='0800',
        sun_close='2000',
      ),
      Business(
         #204
        owner_id=13,
        category_id=1,
        address='2000 Lyons Ave',
        city='Houston',
        state='TX',
        zip_code='77020',
        name='Saint Arnold Brewing Company',
        description='Pet-friendly brewery offering a wide selection of beers, a beer garden, and a restaurant with a diverse menu.',
        website='https://www.saintarnold.com/',
        phone='7136869494',
        price='$',
        set_hours="yes",
        mon_open='1100',
        mon_close='2200',
        tue_open='1100',
        tue_close='2200',
        wed_open='1100',
        wed_close='2200',
        thu_open='1100',
        thu_close='2200',
        fri_open='1100',
        fri_close='2300',
        sat_open='1100',
        sat_close='2300',
        sun_open='1100',
        sun_close='2200',
      ),
      Business(
        #205
        owner_id=34,
        category_id=2,
        address='2030 W Alabama St',
        city='Houston',
        state='TX',
        zip_code='77098',
        name='West Alabama Animal Clinic',
        description='Veterinary clinic offering comprehensive pet care services, including wellness exams, vaccinations, and emergency care.',
        website='https://www.westalabamaanimalclinic.com/',
        phone='7135280818',
        set_hours="yes",
        mon_open='0700',
        mon_close='1800',
        tue_open='0700',
        tue_close='1800',
        wed_open='0700',
        wed_close='1800',
        thu_open='0700',
        thu_close='1800',
        fri_open='0700',
        fri_close='1800',
        sat_open='0800',
        sat_close='1400',
      ),
      Business(
        #206
        owner_id=27,
        category_id=3,
        address='3641 Westheimer Rd, Suite B',
        city='Houston',
        state='TX',
        zip_code='77027',
        name='The Pet Barber',
        description='Premier pet grooming salon offering a range of grooming services for dogs and cats in a pet-friendly environment.',
        website='https://thepetbarberhouston.com/',
        email='info@thepetbarberhouston.com',
        phone='2815013400',
        price='$$$',
        set_hours="yes",
        mon_open='0730',
        mon_close='1730',
        wed_open='0730',
        wed_close='1730',
        thu_open='0730',
        thu_close='1730',
        fri_open='0730',
        fri_close='1730',
        sat_open='0900',
        sat_close='1700',
      ),
      Business(
      #207
        owner_id=8,
        category_id=4,
        address='2929 Weslayan St STE 103',
        city='Houston',
        state='TX',
        zip_code='77027',
        name='Rocky & Maggie\'s',
        description='Rocky & Maggie\'s offers expert grooming & a huge selection of pet supplies.',
        website='https://rockyandmaggies.com/',
        phone='7134920656',
        set_hours="yes",
        mon_open='1000',
        mon_close='1800',
        tue_open='1000',
        tue_close='1800',
        wed_open='1000',
        wed_close='1800',
        thu_open='1000',
        thu_close='1800',
        fri_open='1000',
        fri_close='1900',
        sat_open='1000',
        sat_close='1900',
        sun_open='1200',
        sun_close='1700',
      ),
      Business(
        #208
        owner_id=41,
        category_id=6,
        address='3600 Allen Parkway',
        city='Houston',
        state='TX',
        zip_code='77007',
        name='Buffalo Bayou Park',
        description='A sprawling urban park offering trails, green spaces, and dog parks for pet-friendly outdoor activities.',
        website='https://buffalobayou.org/location/buffalo-bayou-park/',
      ),
      Business(
        #209
        owner_id=22,
        category_id=7,
        address='14700 Almeda Rd.',
        city='Houston',
        state='TX',
        zip_code='77053',
        name='Houston Humane Society',
        description='Animal shelter providing pet adoption services, spay/neuter programs, and community outreach initiatives.',
        website='https://www.houstonhumane.org/',
        phone='7134336421',
        set_hours="yes",
        mon_open='1100',
        mon_close='1800',
        tue_open='1100',
        tue_close='1800',
        wed_open='1100',
        wed_close='1800',
        thu_open='1100',
        thu_close='1800',
        fri_open='1100',
        fri_close='1800',
        sat_open='1100',
        sat_close='1730',
        sun_open='1100',
        sun_close='1730',
      ),
      Business(
        #210
        owner_id=3,
        category_id=8,
        city='Houston',
        state='TX',
        zip_code='77019',
        name='Kelly J. Russo Photography',
        description='Houston Pet & Equine Photographer.',
        website='https://www.kellyjrusso.com/',
        email='kelly@kellyjrusso.com',
        phone='2817056771',
        set_hours="no",
      ),
      Business(
        #211
        owner_id=45,
        category_id=5,
        address='1300 Lamar St',
        city='Houston',
        state='TX',
        zip_code='77010',
        name='The Four Seasons Hotel Houston',
        description='Luxurious pet-friendly hotel offering premium accommodations and amenities for travelers and their pets.',
        website='https://www.fourseasons.com/houston/',
        phone='7136501300',
        price='$$$$',
        set_hours="no",
      )
    ]

    db.session.add_all(businesses_2A)
    db.session.commit()


# Uses a raw SQL query to TRUNCATE or DELETE the users table. SQLAlchemy doesn't
# have a built in function to do this. With postgres in production TRUNCATE
# removes all the data from the table, and RESET IDENTITY resets the auto
# incrementing primary key, CASCADE deletes any dependent entities.  With
# sqlite3 in development you need to instead use DELETE to remove all data and
# it will reset the primary keys for you as well.
def undo_businesses_2A():
    if environment == "production":
      db.session.execute(f"TRUNCATE table {SCHEMA}.businesses RESTART IDENTITY CASCADE;")
    else:
      db.session.execute(text("DELETE FROM businesses"))
    db.session.commit()
