"""empty message

Revision ID: 6c2fde3fdc92
Revises: ae58fbbd4faa
Create Date: 2024-03-14 20:34:10.405323

"""
import os
from alembic import op
import sqlalchemy as sa

environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = '6c2fde3fdc92'
down_revision = 'ae58fbbd4faa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=SCHEMA) as batch_op:
        batch_op.add_column(sa.Column('uploader_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('id', 'users', ['uploader_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=SCHEMA) as batch_op:
        batch_op.drop_constraint('id', type_='foreignkey')
        batch_op.drop_column('uploader_id')

    # ### end Alembic commands ###
