"""empty message

Revision ID: d17deb0e3ad9
Revises: a9081588034a
Create Date: 2024-03-27 18:39:54.987261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd17deb0e3ad9'
down_revision = 'a9081588034a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.alter_column('set_hours',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=3),
               existing_nullable=False,
               existing_server_default=sa.text("'True'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.alter_column('set_hours',
               existing_type=sa.String(length=3),
               type_=sa.BOOLEAN(),
               existing_nullable=False,
               existing_server_default=sa.text("'True'"))

    # ### end Alembic commands ###
