"""create images table

Revision ID: 3d54fc52c9f9
Revises: f20eec27a8da
Create Date: 2024-03-12 19:38:01.588321

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.orm import sessionmaker

Session = sessionmaker()
# revision identifiers, used by Alembic.
revision = '3d54fc52c9f9'
down_revision = 'f20eec27a8da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imageable_id', sa.Integer(), nullable=False),
    sa.Column('imageable_type', postgresql.ENUM('business', 'review', 'user', name='imageable_types'), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_table('images')
  bind = op.get_bind()
  session = Session(bind=bind)
  session.execute('DROP TYPE imageable_types')
    # ### end Alembic commands ###
