"""added category_id col to biz

Revision ID: bd8e0e4a4e76
Revises: 6c8bf09e645f
Create Date: 2024-03-21 13:26:06.012666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd8e0e4a4e76'
down_revision = '6c8bf09e645f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('id', 'categories', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_constraint('id', type_='foreignkey')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
