"""Added city, state to users table

Revision ID: 826adb161f1c
Revises: 8da042020b37
Create Date: 2024-03-12 13:34:33.754959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '826adb161f1c'
down_revision = '8da042020b37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('state', sa.String(length=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('state')
        batch_op.drop_column('city')

    # ### end Alembic commands ###
